#!/bin/bash
# publish org files.

# find emacs binary.
kernel=`uname -s`
emacs="emacs"
if [ $kernel"X" == "DarwinX" ]; then
    emacs="/Applications/Emacs.app/Contents/MacOS/Emacs"
fi

git210 pull origin master
# generate html files.
$emacs --batch --script ./scripts/publish.el
if [ $? != 0 ]
then
    echo "publish failed!"
    exit 1
fi

# post processing html files.
python ./scripts/pp-html
find .  -name "*.html~" | xargs rm -f
git210 add .
git210 commit -a -m '[R] publish org files'
git210 push origin master
