#+title: 李永乐老师
https://www.youtube.com/channel/UCSs4A6HYKmHA2MG_0z-F0xw/playlists




** 火热视频推荐
https://www.youtube.com/playlist?list=PLOrDt87s8A3qsXmW6Hb9lJlHRRkA8xBer



https://i.ytimg.com/vi/o1MdiW5UZh0/sddefault.jpg


*** 基因编辑是啥？CRISPR/cas9技术如何修改DNA？李永乐老师讲基因工程（1）

http://www.youtube.com/watch?v=o1MdiW5UZh0

#+BEGIN_EXPORT HTML
最近，中国深圳的科学家贺建奎宣布：</br>自己通过CRISPR/cas9技术修改了人类胚胎细胞的基因</br>并且利用这个胚胎降生了一对双胞胎</br>这个消息犹如一颗炸弹迅速在全世界范围内引发了激烈了批评</br>许多科学家斥责贺建奎不负责任，打破了人类的共识</br>基因工程是最近发展起来的生物技术</br>CRISPR/cas9是人类从细菌对抗噬菌体的过程中获得启发开拓的新方法</br>让人类可以高效低价的修改DNA</br>利用基因工程，人类可以“随心所欲”的更改动植物甚至人类自身的基因</br>从而让农作物和牲畜生长的更好，或者对抗人类自身的疾病</br>但是， 如果允许修改人类的胚胎细胞</br>除了面临医学风险外，还可能不可逆的改变人类基因库</br>造成不平等或引发更深刻的伦理学问题</br>世界各国都对人体胚胎细胞修改有严格的限制</br>CRISPR/cas9技术到底是什么？ </br>为什么能够修改基因？ </br>点开视频看看吧！</br></br>火热视频推荐：</br>————————————————————————————————</br>为什么久赌必输？https://youtu.be/AadaEc6pJpw</br></br>人造太阳EAST装置啥原理？https://youtu.be/q-9wxg9tQRk</br></br>什么样的投资值得做？https://youtu.be/RwbsL0JUmbM</br></br>怎么做生意更吸引顾客？https://youtu.be/xlmep_us15I</br>————————————————————————————————</br></br>
#+END_EXPORT


*** 什么能源可以取之不尽？中国的人造太阳EAST装置啥原理？李永乐老师讲托卡马克

http://www.youtube.com/watch?v=q-9wxg9tQRk

#+BEGIN_EXPORT HTML
上一个视频：</br>太阳为啥不会瞬间就炸掉？https://youtu.be/vqXkZOL1nQs</br></br>我们在上一回讲了太阳的核聚变原理</br>那有小朋友就问我</br>那我们中国的人造太阳到底是怎么回事呢</br>它有什么作用呢</br>今天我们就来研究一下这个问题</br></br>火热视频推荐：</br>————————————————————————————————</br>为什么久赌必输？https://youtu.be/AadaEc6pJpw</br></br>输了钱就加倍下注吗？https://youtu.be/yoOocF47BRI</br></br>什么样的投资值得做？https://youtu.be/RwbsL0JUmbM</br></br>怎么做生意更吸引顾客？https://youtu.be/xlmep_us15I</br>————————————————————————————————</br></br>
#+END_EXPORT


*** 双11优惠规则为啥这么复杂？穷人和富人被区别对待了？李永乐老师讲价格歧视

http://www.youtube.com/watch?v=CDORrtQu3fE

#+BEGIN_EXPORT HTML
双11马上就要到了</br>不知大家准备好剁手了没有</br>有一个小朋友给我发来私信说</br>双11的优惠政策他实在是看不懂</br>除了传统的打折以外</br>还有满减 反券 积分换好礼 跨店铺等等</br>他说双11的优惠为什么设置成这么复杂的规矩</br>为什么不直接来一个打折就完事了呢</br>今天我们就来研究一下这个问题</br></br>通过视频的内容解读，你可以了解到以下内容：</br>为什么苹果手机的内存为没有64G或者128G的情况？</br>对于讨价还价，为什么最赚钱的是卖方？</br>同一款车，为什么为了个配置却贵了这么多？</br>收集优惠券是一种什么心态？</br></br>大家有什么喜欢的视频可以在下方留言。</br></br>火热视频推荐：</br>————————————————————————————————</br>为什么久赌必输？https://youtu.be/AadaEc6pJpw</br>输了钱就加倍下注吗？https://youtu.be/yoOocF47BRI</br>什么样的投资值得做？https://youtu.be/RwbsL0JUmbM</br>————————————————————————————————</br></br>
#+END_EXPORT


*** 输了钱就加倍下注，能回本？股票下跌就补仓？李永乐老师讲赌徒谬误

http://www.youtube.com/watch?v=yoOocF47BRI

#+BEGIN_EXPORT HTML
上一回咱们讲了雅各布·伯努力所提出的大数定律</br>有小朋友非常高兴地跟我说</br>他终于找到了一种可以提高彩票中奖率的方法</br>彩票中每一个数字出现的概率都是相等的</br>因此根据大数定律在很长的时间开出这些数字也应该是等频率的</br>所以如果有一个数字很长时间没有开出来 我们就应该买它</br>这样中奖的概率就特别大</br>这个说法对不对 今天我们就来研究一下这个问题</br>其实这个问题很早以前人们就提出来了</br>并被称之为赌徒谬误</br></br>具体内容，打开视频看看吧！</br></br>
#+END_EXPORT


*** 什么是爱情？怎么谈恋爱，才能有效的找到自己的真命天子？李永乐老师讲爱情数学

http://www.youtube.com/watch?v=pelPCK22W7k

#+BEGIN_EXPORT HTML
曾有弟子问苏格拉底，什么是爱情？</br>苏格拉底让他走过一个麦田，只能向前，只能捡一个麦穗</br>要求他捡到最大的麦穗</br>有的弟子没走几步就捡了一个</br>然后发现了更大的后悔不已</br>有的弟子总觉得后面有更大的麦穗，结果空手而归</br>苏格拉底说：这就是爱情！</br>这个问题在近代被称为秘书问题</br>所解决的是如何在类似的情况中找出最优秀的人</br>我们的策略是在全部备选中划出一部分样本</br>考察并拒绝所有的样本</br>从样本后面的第一个人开始</br>只要发现比所有样本都好的人，就接受他</br>我们选择自己伴侣的时候，也可以使用这个策略</br>样本应该占备选者的百分之多少？</br>我们有多大概率找到真命天子？</br>打开视频看看吧！</br></br>火热视频推荐：</br>——————————————————————————————————————</br>宇宙中最大的数是啥？https://youtu.be/eSYN2UN3SXM</br>————————————————————————————————</br>支配宇宙的法则：什么是因果？https://youtu.be/0auDcESroEA</br></br></br>经济学视频推荐：</br>——————————————————————————————————————</br>你存银行的钱都去哪了？https://youtu.be/OTe3Bbcixow</br>————————————————————————————————</br>贷款 买房，利息怎么算？https://youtu.be/T6FBfNpiBYw</br></br>大家有什么喜欢的视频可以评论留言！</br></br>
#+END_EXPORT


*** 时间到底是什么？1秒究竟有多长？李永乐老师讲石英钟和原子钟

http://www.youtube.com/watch?v=cXX_f_pWLQI

#+BEGIN_EXPORT HTML
相关视频：</br>打火机为啥一按就打火？什么是压电效应？https://youtu.be/-ZjlExDxE0o</br>————————————————————————————————————</br>激光啥原理？能级的概念是怎么解释？https://youtu.be/U-WlZxjIGUU</br>————————————————————————————————————</br></br>时间是什么？</br>从物理学角度讲，时间其实代表了物体有规律的运动！</br>我们观察日月星辰，就有了一年 一天 一时和一秒的概念</br>最近一百年， 随着科技的进步，人们已经不满足于使用自然规律计时</br>而希望通过物理规律定义时间，就发明了石英钟和原子钟</br>石英钟利用石英晶体的振动计时，大约每270年才会差出1秒</br>原子钟利用铯原子两个精细结构之间辐射的电磁波计时</br>精确度可以达到几千万年甚至几十亿年才差1秒</br>因为它的精确度如此之高，人们就用它来作为“秒”的定义</br>高精度的原子钟在航天领域和物理学研究上都有很重要的作用</br>具体怎么回事？</br>点开视频看看吧！</br></br>火热视频推荐：</br>————————————————————————————————</br>基因编辑是啥？CRISPR/cas9技术如何修改DNA？https://youtu.be/o1MdiW5UZh0</br></br>为什么久赌必输？https://youtu.be/AadaEc6pJpw</br></br>人造太阳EAST装置啥原理？https://youtu.be/q-9wxg9tQRk</br></br>什么样的投资值得做？https://youtu.be/RwbsL0JUmbM</br>————————————————————————————————</br></br>
#+END_EXPORT


*** 1+2+3+4+...=-1/12？李永乐老师讲黎曼猜想（1）

http://www.youtube.com/watch?v=T93SayXhw2w

#+BEGIN_EXPORT HTML
最近数学圈爆出一个大新闻</br>英国数学家阿蒂亚(Michael Atiyah)爵士</br>宣布自己证明了黎曼猜想</br>并将在9月24号的获奖者论坛上宣读自己的论文</br>因为阿蒂亚爵士是阿贝尔奖和菲尔兹奖的双料得主</br>世界顶级的数学家之一</br>而黎曼猜想又是150多年来没有人能够解决</br>但是又特别重要的数学猜想</br>所以这则新闻一出一下子就引爆了人们的神经</br>那么许多小朋友就问我说 黎曼猜想到底是什么呢</br>因为黎曼猜想的内容实在是太丰富了</br>所以我们一期内容没有办法讲完</br>我们准备用三期的时间给大家介绍一下黎曼猜想</br>那今天我们不妨先来解决一下</br>小朋友们以前一直在问我的问题</br>全体自然数的和到底是不是-1/12</br></br>——————————————————————————————————</br>最美的数学公式是哪个？自然数是如何拓展出复数的？https://youtu.be/eEiNep19W5U</br></br>
#+END_EXPORT


*** 烧脑面试题：老鼠和毒药问题怎么解？二进制和易经八卦有啥关系？李永乐老师告诉你

http://www.youtube.com/watch?v=jYQEkkwUBxQ

#+BEGIN_EXPORT HTML
视频题目：</br>有100瓶液体 其中99瓶是水儿 有1瓶是毒药</br>如果老鼠吃了带毒药的水的话。那么这个老鼠在一周后就会死亡</br>现在问，给你一周的时间至少需要多少只小白鼠</br>才能知道哪一瓶是毒药</br></br>类似题目：</br>有 1000 个一模一样的瓶子，其中有 999 瓶是普通的水，有一瓶是毒药</br>任何喝下毒药的生物都会在一星期之后死亡</br>现在，你只有 10 只小白鼠和一星期的时间</br>如何检验出哪个瓶子里有毒药？</br>答案详见视频</br></br>火热视频推荐：</br>——————————————————————————————————————</br>宇宙中最大的数是啥？https://youtu.be/eSYN2UN3SXM</br>————————————————————————————————</br>支配宇宙的法则：什么是因果？https://youtu.be/0auDcESroEA</br></br>相对论视频推荐：</br>——————————————————————————————————————</br>光速为什么不能被超越？https://youtu.be/zY11529Uia0</br>————————————————————————————————</br>支配宇宙的法则：什么是因果？https://youtu.be/0auDcESroEA</br>————————————————————————————————</br>狭义相对论：时间膨胀是怎么回事？https://youtu.be/h6tbHSyVmfo</br></br>
#+END_EXPORT


*** 宇宙中最大的数是啥？居然能让人脑变黑洞？李永乐老师讲葛立恒数（2018最新）

http://www.youtube.com/watch?v=eSYN2UN3SXM

#+BEGIN_EXPORT HTML
历史上的三次数学危机</br>——————————————————————————————————</br>第一次数学危机是什么？https://youtu.be/nAOVQEcqjSM</br>————————————————————————————————</br>第二次数学危机是什么？https://youtu.be/S5z7xYfGNXs</br>————————————————————————————————</br>第三次数学危机是什么？https://youtu.be/GWTVAYQytJ8</br></br>经济学视频推荐：</br>——————————————————————————————————————</br>你存银行的钱都去哪了？https://youtu.be/OTe3Bbcixow</br>————————————————————————————————</br>贷款 买房，利息怎么算？https://youtu.be/T6FBfNpiBYw</br>————————————————————————————————</br></br>值得深思的视频推荐：</br>——————————————————————————————————————</br>你真的看懂《皇帝的新装》了吗？https://youtu.be/b7NZfkqFc6k</br>————————————————————————————————</br>帝王为啥总要杀有功之臣？https://youtu.be/qXg1r_FwkvA</br>————————————————————————————————</br></br>有想看的内容可能在下面留言！</br></br>
#+END_EXPORT


*** 假疫苗事件：疫苗到底有啥用？天花是怎么被消灭的？李永乐老师讲免疫系统（2018最新）

http://www.youtube.com/watch?v=Sxl_zoy1HoQ

#+BEGIN_EXPORT HTML
最近疫苗这个词非常流行</br>很多小朋友问我说疫苗到底是干嘛用的</br>不打疫苗行不行</br>今天我们就想讨论一下这个问题</br>我们都知道疫苗是为了防止传染病的</br>我们不妨就从人类历史上一个谈虎色变的传染病天花说起</br>天花这种传染病历史非常悠久</br></br>天花这种疾病非常可怕 首先是因为它死亡率高</br>它有30%的死亡率这么高 1/3</br>同时就算你不死</br>那么你康复了之后你的身上也会留下非常难看的疤痕</br>让人感觉非常恐怖 所以这个人基本就废了</br></br>那么人们是怎么攻克天花病毒的？</br>人们又是如何防御外界病毒或者细菌的呢？</br>疫苗对人到底有多重要呢？</br>今天这个视频给大家讲讲覆盖全身的防卫网络——免疫系统</br>人的免疫系统有基本可分有三道防线</br>具体情况，打开视频看看吧</br></br>
#+END_EXPORT


*** 从比较优势理论分析：中美为何会爆发贸易战？与鸦片战争有什么相似之处？李永乐老师告诉你

http://www.youtube.com/watch?v=nwLqo83iqks

#+BEGIN_EXPORT HTML
最近中美贸易战愈演愈烈 从最开始双方进行反倾销调查</br>到后来互加关税 再到现在美国直接对中国的个别企业进行制裁</br>甚至演变成外交风波</br>有小朋友就问我说 为什么中美之间会爆发这样一场贸易战</br>很显然这个问题是非常复杂的</br>那今天我们想从一个侧面贸易的角度来理解一下这个问题</br></br>视频中包含以下知识点：</br>1、什么是绝对优势？</br>2、什么是比较优势？</br>3、中英为什么会爆发鸦片战争？</br>4、中美为什么会爆发贸易战？</br>详见视频！</br></br>火热视频推荐：</br>基因编辑是啥？CRISPR/cas9技术如何修改DNA？https://youtu.be/o1MdiW5UZh0</br>为什么久赌必输？https://youtu.be/AadaEc6pJpw</br>输了钱就加倍下注，能回本吗？https://youtu.be/yoOocF47BRI</br>贷款/买房，利息怎么算？https://youtu.be/T6FBfNpiBYw</br></br>
#+END_EXPORT




** 基因工程
https://www.youtube.com/playlist?list=PLOrDt87s8A3pE8m-yvsqWOU8W6ZwlRmDi



https://i.ytimg.com/vi/2UtZHz3OfJg/sddefault.jpg


*** 基因工程对人类的重大贡献：胰岛素是如何制作的？李永乐老师讲糖尿病医疗简史

http://www.youtube.com/watch?v=2UtZHz3OfJg

#+BEGIN_EXPORT HTML
上一回咱们讲了基因工程是什么</br>那么这一回</br>咱们就来聊一下 基因工程对人类最大的一个贡献</br>那就是糖尿病人使用的药物 胰岛素的生产</br>我们首先从糖尿病说起</br>... ...</br></br>详见视频！</br></br>基因编辑是啥？CRISPR/cas9技术如何修改DNA？https://youtu.be/o1MdiW5UZh0</br></br>
#+END_EXPORT


*** 基因编辑是啥？CRISPR/cas9技术如何修改DNA？李永乐老师讲基因工程（1）

http://www.youtube.com/watch?v=o1MdiW5UZh0

#+BEGIN_EXPORT HTML
最近，中国深圳的科学家贺建奎宣布：</br>自己通过CRISPR/cas9技术修改了人类胚胎细胞的基因</br>并且利用这个胚胎降生了一对双胞胎</br>这个消息犹如一颗炸弹迅速在全世界范围内引发了激烈了批评</br>许多科学家斥责贺建奎不负责任，打破了人类的共识</br>基因工程是最近发展起来的生物技术</br>CRISPR/cas9是人类从细菌对抗噬菌体的过程中获得启发开拓的新方法</br>让人类可以高效低价的修改DNA</br>利用基因工程，人类可以“随心所欲”的更改动植物甚至人类自身的基因</br>从而让农作物和牲畜生长的更好，或者对抗人类自身的疾病</br>但是， 如果允许修改人类的胚胎细胞</br>除了面临医学风险外，还可能不可逆的改变人类基因库</br>造成不平等或引发更深刻的伦理学问题</br>世界各国都对人体胚胎细胞修改有严格的限制</br>CRISPR/cas9技术到底是什么？ </br>为什么能够修改基因？ </br>点开视频看看吧！</br></br>火热视频推荐：</br>————————————————————————————————</br>为什么久赌必输？https://youtu.be/AadaEc6pJpw</br></br>人造太阳EAST装置啥原理？https://youtu.be/q-9wxg9tQRk</br></br>什么样的投资值得做？https://youtu.be/RwbsL0JUmbM</br></br>怎么做生意更吸引顾客？https://youtu.be/xlmep_us15I</br>————————————————————————————————</br></br>
#+END_EXPORT




** 大国重器
https://www.youtube.com/playlist?list=PLOrDt87s8A3rxcYRiHkp0yDGupkAIFiB4



https://i.ytimg.com/vi/q-9wxg9tQRk/sddefault.jpg


*** 什么能源可以取之不尽？中国的人造太阳EAST装置啥原理？李永乐老师讲托卡马克

http://www.youtube.com/watch?v=q-9wxg9tQRk

#+BEGIN_EXPORT HTML
上一个视频：</br>太阳为啥不会瞬间就炸掉？https://youtu.be/vqXkZOL1nQs</br></br>我们在上一回讲了太阳的核聚变原理</br>那有小朋友就问我</br>那我们中国的人造太阳到底是怎么回事呢</br>它有什么作用呢</br>今天我们就来研究一下这个问题</br></br>火热视频推荐：</br>————————————————————————————————</br>为什么久赌必输？https://youtu.be/AadaEc6pJpw</br></br>输了钱就加倍下注吗？https://youtu.be/yoOocF47BRI</br></br>什么样的投资值得做？https://youtu.be/RwbsL0JUmbM</br></br>怎么做生意更吸引顾客？https://youtu.be/xlmep_us15I</br>————————————————————————————————</br></br>
#+END_EXPORT




** 赌徒系列 | 赌博/股票/投资/做生意
https://www.youtube.com/playlist?list=PLOrDt87s8A3qVVaSmxpttNKzP80tSEH83



https://i.ytimg.com/vi/xlmep_us15I/sddefault.jpg


*** 如何说话让人喜欢？怎么做生意更吸引顾客？李永乐老师讲框架效应

http://www.youtube.com/watch?v=xlmep_us15I

#+BEGIN_EXPORT HTML
有小朋友跟我说他是办公室的一个科员</br>每当他向领导汇报工作的时候 领导总是很不开心</br>但他的同事向领导汇报工作的时候 领导就很开心</br>他说本来都是同一个工作 为什么不同的人汇报差别会这么大</br>今天我们就来研究一下这个问题</br></br>火热视频推荐：</br>————————————————————————————————</br>为什么久赌必输？https://youtu.be/AadaEc6pJpw</br>输了钱就加倍下注吗？https://youtu.be/yoOocF47BRI</br>双11优惠规则为啥这么复杂？https://youtu.be/CDORrtQu3fE</br>什么样的投资值得做？https://youtu.be/RwbsL0JUmbM</br>————————————————————————————————</br></br>
#+END_EXPORT


*** 输了钱就加倍下注，能回本？股票下跌就补仓？李永乐老师讲赌徒谬误

http://www.youtube.com/watch?v=yoOocF47BRI

#+BEGIN_EXPORT HTML
上一回咱们讲了雅各布·伯努力所提出的大数定律</br>有小朋友非常高兴地跟我说</br>他终于找到了一种可以提高彩票中奖率的方法</br>彩票中每一个数字出现的概率都是相等的</br>因此根据大数定律在很长的时间开出这些数字也应该是等频率的</br>所以如果有一个数字很长时间没有开出来 我们就应该买它</br>这样中奖的概率就特别大</br>这个说法对不对 今天我们就来研究一下这个问题</br>其实这个问题很早以前人们就提出来了</br>并被称之为赌徒谬误</br></br>具体内容，打开视频看看吧！</br></br>
#+END_EXPORT


*** 为什么久赌必输？股票加杠杆，风险为啥这么大？李永乐老师讲赌徒输光原理

http://www.youtube.com/watch?v=AadaEc6pJpw

#+BEGIN_EXPORT HTML
有一个经典的问题：如果有两个赌徒</br>他们玩一个公平的游戏：每局游戏输赢1元钱</br>且每次游戏两个人获胜的概率都是50%</br>游戏重复多次，直到一方输光，另一方赢到全部的钱为止</br>那么，最终两人谁输谁赢的概率与两人最初的资金量有关</br>资金量大的一方有更大的概率赢到全部的钱</br>资金量小的一方有更大的概率输光所有的钱</br>如果有一方的资金量是无限的</br>那么另一方有100%的概率会输光</br></br>赌徒与赌场对赌</br>由于赌场的资金相比于赌徒接近于无限</br>只要赌徒一直下注，即使是公平游戏，最终也一定会输光</br>这个问题同样可以解释在股票市场上加杠杆时的风险性</br>杠杆比例越高，输光的概率就越大</br>普希金的童话《渔夫与金鱼》也说明了同样的问题：</br>贪婪的人最终将一无所有</br>数学原理是什么？</br>点开视频看看吧！</br></br>
#+END_EXPORT


*** 双11优惠规则为啥这么复杂？穷人和富人被区别对待了？李永乐老师讲价格歧视

http://www.youtube.com/watch?v=CDORrtQu3fE

#+BEGIN_EXPORT HTML
双11马上就要到了</br>不知大家准备好剁手了没有</br>有一个小朋友给我发来私信说</br>双11的优惠政策他实在是看不懂</br>除了传统的打折以外</br>还有满减 反券 积分换好礼 跨店铺等等</br>他说双11的优惠为什么设置成这么复杂的规矩</br>为什么不直接来一个打折就完事了呢</br>今天我们就来研究一下这个问题</br></br>通过视频的内容解读，你可以了解到以下内容：</br>为什么苹果手机的内存为没有64G或者128G的情况？</br>对于讨价还价，为什么最赚钱的是卖方？</br>同一款车，为什么为了个配置却贵了这么多？</br>收集优惠券是一种什么心态？</br></br>大家有什么喜欢的视频可以在下方留言。</br></br>火热视频推荐：</br>————————————————————————————————</br>为什么久赌必输？https://youtu.be/AadaEc6pJpw</br>输了钱就加倍下注吗？https://youtu.be/yoOocF47BRI</br>什么样的投资值得做？https://youtu.be/RwbsL0JUmbM</br>————————————————————————————————</br></br>
#+END_EXPORT


*** 什么样的投资值得做？圣彼得堡悖论是怎么回事？李永乐老师讲边际效用递减

http://www.youtube.com/watch?v=RwbsL0JUmbM

#+BEGIN_EXPORT HTML
最近有小朋友问我说 他的朋友让他进行一项投资</br>他知道这个投资有一定的概率会赚到很多钱</br>但是也有亏本的可能</br>他问我如何去评估这个项目该不该投呢</br>我们今天就来研究一下这个问题</br></br>详见视频！</br>大家有喜欢的话题内容可以在评论区留言。</br></br>火热视频推荐：</br>————————————————————————————————</br>为什么久赌必输？https://youtu.be/AadaEc6pJpw</br>输了钱就加倍下注吗？https://youtu.be/yoOocF47BRI</br>1+2+3+4+...=-1/12？https://youtu.be/T93SayXhw2w</br>————————————————————————————————</br></br>
#+END_EXPORT


*** 面对风险、机遇和挑战，你为什么总是赚小亏大？李永乐老师讲阿莱悖论

http://www.youtube.com/watch?v=8Tz1WAp4vRE

#+BEGIN_EXPORT HTML
火热视频推荐：</br>————————————————————————————————</br>为什么久赌必输？https://youtu.be/AadaEc6pJpw</br>输了钱就加倍下注吗？https://youtu.be/yoOocF47BRI</br>1+2+3+4+...=-1/12？https://youtu.be/T93SayXhw2w</br>什么样的投资值得做？https://youtu.be/RwbsL0JUmbM</br>————————————————————————————————</br>上一回我们讲了期望效用理论</br>我们知道了获得两块钱的满意度提升</br>并不等于获得一块钱满意度提升的两倍</br>但是无论是期望还是效用</br>这都属于传统经济学范畴</br>传统经济学认为人是理性的</br>但是现在我们在投资股票证券的时候</br>发现了很多的非理性行为</br>这又如何解释呢</br>今天我们就来研究一下这个问题</br></br>详见视频！</br>大家有喜欢的话题内容可以在评论区留言。</br></br>
#+END_EXPORT


*** 凯利公式是啥？按这个炒股能成巴菲特？如何分配手里的钱进行最优投资，李永乐老师告诉你

http://www.youtube.com/watch?v=v2JGTi5lhY4

#+BEGIN_EXPORT HTML
前几期我一直在讲风险与投资的问题</br>于是就有小朋友不停的给我发私信</br>让我讲一讲凯利公式</br>他听说巴菲特就是靠这个公式成为一个投资大佬的</br>那么我们今天就来讲一讲这个公式：凯利公式</br></br>火热视频推荐：</br>————————————————————————————————</br>为什么久赌必输？https://youtu.be/AadaEc6pJpw</br>输了钱就加倍下注吗？https://youtu.be/yoOocF47BRI</br>双11优惠规则为啥这么复杂？https://youtu.be/CDORrtQu3fE</br>什么样的投资值得做？https://youtu.be/RwbsL0JUmbM</br>怎么做生意更吸引顾客？https://youtu.be/xlmep_us15I</br>————————————————————————————————</br></br>
#+END_EXPORT




** 来龙去脉
https://www.youtube.com/playlist?list=PLOrDt87s8A3oqJe9W6FXvI8GDVpxVhYxt



https://i.ytimg.com/vi/InA9uxljb1w/sddefault.jpg


*** 怪病：酸性恐惧症是啥？酸性体质容易生病？李永乐老师讲PH值

http://www.youtube.com/watch?v=InA9uxljb1w

#+BEGIN_EXPORT HTML
最近有小朋友给我发来私信</br>告诉我说他们家的老人得了一种怪病</br>这种怪病叫做酸性恐惧症</br>就是说别人告诉这位老人酸性体质会造成生病</br>所以这个老人吃饭的时候要吃碱性的饭</br>喝水的时候要喝碱性的水</br>就连呼吸空气都希望这空气是碱性的</br>他想问我到底什么是酸性 碱性</br>酸性 碱性对人体真的这么重要吗</br>今天我们就来说一下这个问题</br></br>主要内容说明</br>什么是PH值</br>人体的血液 血液酸碱度是在7.35～7.45之间</br>人体的血液是碱性的</br>人体系统必须维持一定酸碱度</br>人体会通过以下三个调节系统</br>1 血液缓冲</br>2 呼吸系统</br>3 泌尿系统</br></br>如果酸碱性有问题我们应该去医院检查</br>而不要想着说我只要通过吃食物的办法</br></br>
#+END_EXPORT


*** 揭秘：这个学霸，他为啥不怕百万伏的高压电？李永乐老师讲《加油向未来》的精彩实验

http://www.youtube.com/watch?v=3DLg84Eku8g

#+BEGIN_EXPORT HTML
不知大家有没有看上周末晚上</br>中央一套的节目《加油! 向未来》</br>里面有一个清华大学大二物理系的学生陈鲲羽</br>他凭借自己精彩的表现震惊了全场 被授予“鲲神”的称号</br>而且在一周的时间内刷爆了朋友圈</br>他最精彩的一个实验是坐在一个装到盐水的水池里</br>然后通上了高压电 结果发现他什么事都没有</br>他甚至用手去接触这个高压电</br>结果发现他还是镇定自若</br>有同学就问我说 那这个事到底是为啥呢</br>今天呢 我们就来解释一下这个现象</br></br>大家有什么相看的视频内容可以在评论区留言！</br></br>火热视频推荐：</br>——————————————————————————————————————</br>宇宙中最大的数是啥？https://youtu.be/eSYN2UN3SXM</br>————————————————————————————————</br>支配宇宙的法则：什么是因果？https://youtu.be/0auDcESroEA</br>————————————————————————————————</br>特斯拉线圈 | 如何制造百万伏级的闪电？https://youtu.be/_d5USXhvd6U</br>————————————————————————————————</br>烧脑面试题：老鼠和毒药问题怎么解？https://youtu.be/jYQEkkwUBxQ</br></br>
#+END_EXPORT


*** WIFI和微波炉加热食物会对人有害吗？致癌吗？李永乐老师讲微波炉原理

http://www.youtube.com/watch?v=4h-h2vYmMtg

#+BEGIN_EXPORT HTML
大家如果有想看的内容可能在评论区留言！</br></br>相关视频推荐：</br>——————————————————————————————————————</br>闪电是如何形成的？如何快速回避闪电？https://youtu.be/qyshX7qiG2I</br></br>火热视频推荐：</br>——————————————————————————————————————</br>老哥的一句“我先走了”，成了生命中最后一句话！https://youtu.be/Yn851GQBsWw</br>————————————————————————————————</br>宇宙中最大的数是啥？https://youtu.be/eSYN2UN3SXM</br>————————————————————————————————</br>支配宇宙的法则：什么是因果？https://youtu.be/0auDcESroEA</br></br>相对论视频推荐：</br>——————————————————————————————————————</br>光速为什么不能被超越？https://youtu.be/zY11529Uia0</br>————————————————————————————————</br>支配宇宙的法则：什么是因果？https://youtu.be/0auDcESroEA</br>————————————————————————————————</br>狭义相对论：时间膨胀是怎么回事？https://youtu.be/h6tbHSyVmfo</br></br>经济学视频推荐：</br>——————————————————————————————————————</br>你存银行的钱都去哪了？https://youtu.be/OTe3Bbcixow</br>————————————————————————————————</br>贷款 买房，利息怎么算？https://youtu.be/T6FBfNpiBYw</br>————————————————————————————————</br></br>值得深思的视频推荐：</br>——————————————————————————————————————</br>你真的看懂《皇帝的新装》了吗？https://youtu.be/b7NZfkqFc6k</br>————————————————————————————————</br>帝王为啥总要杀有功之臣？https://youtu.be/qXg1r_FwkvA</br>————————————————————————————————</br></br>
#+END_EXPORT


*** 老哥的一句“我先走了”，成了生命中最后一句话！高空跳水有多危险？李永乐老师讲重力加速度与缓冲

http://www.youtube.com/watch?v=Yn851GQBsWw

#+BEGIN_EXPORT HTML
火热视频推荐：</br>——————————————————————————————————————</br>宇宙中最大的数是啥？https://youtu.be/eSYN2UN3SXM</br>————————————————————————————————</br>支配宇宙的法则：什么是因果？https://youtu.be/0auDcESroEA</br></br>历史上的三次数学危机推荐：</br>——————————————————————————————————————</br>第一次数学危机是什么？https://youtu.be/nAOVQEcqjSM</br>————————————————————————————————</br>第二次数学危机是什么？https://youtu.be/S5z7xYfGNXs</br>————————————————————————————————</br>第三次数学危机是什么？https://youtu.be/GWTVAYQytJ8</br></br>经济学视频推荐：</br>——————————————————————————————————————</br>你存银行的钱都去哪了？https://youtu.be/OTe3Bbcixow</br>————————————————————————————————</br>贷款 买房，利息怎么算？https://youtu.be/T6FBfNpiBYw</br>————————————————————————————————</br></br>值得深思的视频推荐：</br>——————————————————————————————————————</br>你真的看懂《皇帝的新装》了吗？https://youtu.be/b7NZfkqFc6k</br>————————————————————————————————</br>帝王为啥总要杀有功之臣？https://youtu.be/qXg1r_FwkvA</br>————————————————————————————————</br></br>有想看的内容可能在下面留言！</br></br>
#+END_EXPORT


*** 贷款/买房，利息怎么算？不要被忽悠了！李永乐老师讲等额本金和等额本息算法（2018最新）

http://www.youtube.com/watch?v=T6FBfNpiBYw

#+BEGIN_EXPORT HTML
你真的看懂《皇帝的新装》了吗？https://youtu.be/b7NZfkqFc6k</br>——————————————————————————————————————</br>帝王为啥总要杀有功之臣？https://youtu.be/qXg1r_FwkvA</br>——————————————————————————————————————</br></br>最近有小朋友跟我说他最近买了个房子</br>这买房子有两种还款方式</br>等额本金和等额本息</br>他问我这两种方式有什么区别</br>还有人跟他说你如果贷了款就不要提前还款</br>因为提前还款的话前面的利息就白还了</br>这些说法都对不对</br></br>咱们今天就研究一下贷款利息怎么算</br>以及如何防止小额贷款公司算高利息</br>要不要提前还款的问题</br>详见视频</br></br>
#+END_EXPORT


*** 电影里车轮为啥会倒转？水滴为啥会向上流？李永乐老师讲频闪效应

http://www.youtube.com/watch?v=fMxRxk-HQ4c

#+BEGIN_EXPORT HTML
大家如果有想看的内容可能在评论区留言！</br></br>引用的不同车速下车轮的转动情况链接：https://youtu.be/nR5JSk06_l0</br></br>引用的水滴逆流视频链接：https://www.masters.tw/138111/strobe-light</br></br>火热视频推荐：</br>——————————————————————————————————————</br>WIFI和微波炉加热食物会对人有害吗？致癌吗？https://youtu.be/4h-h2vYmMtg</br>————————————————————————————————</br>老哥的一句“我先走了”，成了生命中最后一句话！https://youtu.be/Yn851GQBsWw</br>————————————————————————————————</br>宇宙中最大的数是啥？https://youtu.be/eSYN2UN3SXM</br>————————————————————————————————</br>支配宇宙的法则：什么是因果？https://youtu.be/0auDcESroEA</br></br>相对论视频推荐：</br>——————————————————————————————————————</br>光速为什么不能被超越？https://youtu.be/zY11529Uia0</br>————————————————————————————————</br>支配宇宙的法则：什么是因果？https://youtu.be/0auDcESroEA</br>————————————————————————————————</br>狭义相对论：时间膨胀是怎么回事？https://youtu.be/h6tbHSyVmfo</br></br>经济学视频推荐：</br>——————————————————————————————————————</br>你存银行的钱都去哪了？https://youtu.be/OTe3Bbcixow</br>————————————————————————————————</br>贷款 买房，利息怎么算？https://youtu.be/T6FBfNpiBYw</br>————————————————————————————————</br></br>值得深思的视频推荐：</br>——————————————————————————————————————</br>你真的看懂《皇帝的新装》了吗？https://youtu.be/b7NZfkqFc6k</br>————————————————————————————————</br>帝王为啥总要杀有功之臣？https://youtu.be/qXg1r_FwkvA</br>————————————————————————————————</br></br>
#+END_EXPORT


*** 假疫苗事件：疫苗到底有啥用？天花是怎么被消灭的？李永乐老师讲免疫系统（2018最新）

http://www.youtube.com/watch?v=Sxl_zoy1HoQ

#+BEGIN_EXPORT HTML
最近疫苗这个词非常流行</br>很多小朋友问我说疫苗到底是干嘛用的</br>不打疫苗行不行</br>今天我们就想讨论一下这个问题</br>我们都知道疫苗是为了防止传染病的</br>我们不妨就从人类历史上一个谈虎色变的传染病天花说起</br>天花这种传染病历史非常悠久</br></br>天花这种疾病非常可怕 首先是因为它死亡率高</br>它有30%的死亡率这么高 1/3</br>同时就算你不死</br>那么你康复了之后你的身上也会留下非常难看的疤痕</br>让人感觉非常恐怖 所以这个人基本就废了</br></br>那么人们是怎么攻克天花病毒的？</br>人们又是如何防御外界病毒或者细菌的呢？</br>疫苗对人到底有多重要呢？</br>今天这个视频给大家讲讲覆盖全身的防卫网络——免疫系统</br>人的免疫系统有基本可分有三道防线</br>具体情况，打开视频看看吧</br></br>
#+END_EXPORT


*** 《我不是药神》里的格列卫凭什么这么贵？仿制药到底是不是假药？李永乐老师讲白血病（2018最新）

http://www.youtube.com/watch?v=Jzror32wTos

#+BEGIN_EXPORT HTML
最近一部电影《我不是药神》大热</br>电影里的慢性粒细胞性白血病经过人类几十年的研究</br>已经了解了致病原因</br>并且人类也研发出了针对这种疾病的靶向药物格列卫</br>长期使用格列卫可以非常好的控制病情</br>但是，因为新药研发需要投入大量的资金人力和时间</br>格列卫这种药物非常昂贵</br>于是就出现了仿制药仿制</br>药与原研药的药效相差无几</br>但是价格却非常便宜，印度在这方面做得比较多</br>慢性粒细胞性白血病到底是怎么回事？</br>格列卫为什么这么神奇？</br>仿制药是怎么做出来的？</br>为什么印度可以仿制我们却不仿制？</br>点开视频，一起了解一下</br></br>
#+END_EXPORT


*** 抖音世纪难题：一根牙签也能把一大瓶水挂在桌边？跑步为什么比骑车更累？李永乐老师讲解重心（2018最新）

http://www.youtube.com/watch?v=jliQAF71EXQ

#+BEGIN_EXPORT HTML
有同学在网上给我发来一段视频</br>问我这个实验怎么回事</br>今天我就把这个实验还原出来了</br>我是用几根牙签加个绳子连了一瓶矿泉水</br>然后 我松开我的右手</br>这个瓶子也不会掉下来</br>说这个实验原因是什么</br></br>为了解释实验的原因</br>——————————————————————</br>第一我们要理解重心</br>我们可以通过找悬线法重心</br>大部分跳高运动员比赛的过程中</br>都采用背越式 而不采用跨越式</br>这是为什么</br></br>——————————————————————</br>第一我们要理解稳定性</br>不倒翁就非常稳定</br>就是重心是低于球心的</br>跑车一般都是比较矮的</br>因为重心低 不容易翻车 它比较稳定</br></br>
#+END_EXPORT


*** 飞机被雷击会发生什么？手机防辐射贴有用吗？李永乐老师讲静电屏蔽

http://www.youtube.com/watch?v=rT4dnHyXyGE

#+BEGIN_EXPORT HTML
相关视频推荐：</br>——————————————————————————————————————</br>闪电是如何形成的？如何快速回避闪电？https://youtu.be/qyshX7qiG2I</br></br>火热视频推荐：</br>——————————————————————————————————————</br>老哥的一句“我先走了”，成了生命中最后一句话！https://youtu.be/Yn851GQBsWw</br>————————————————————————————————</br>宇宙中最大的数是啥？https://youtu.be/eSYN2UN3SXM</br>————————————————————————————————</br>支配宇宙的法则：什么是因果？https://youtu.be/0auDcESroEA</br></br>相对论视频推荐：</br>——————————————————————————————————————</br>光速为什么不能被超越？https://youtu.be/zY11529Uia0</br>————————————————————————————————</br>支配宇宙的法则：什么是因果？https://youtu.be/0auDcESroEA</br>————————————————————————————————</br>狭义相对论：时间膨胀是怎么回事？https://youtu.be/h6tbHSyVmfo</br></br>经济学视频推荐：</br>——————————————————————————————————————</br>你存银行的钱都去哪了？https://youtu.be/OTe3Bbcixow</br>————————————————————————————————</br>贷款 买房，利息怎么算？https://youtu.be/T6FBfNpiBYw</br>————————————————————————————————</br></br>值得深思的视频推荐：</br>——————————————————————————————————————</br>你真的看懂《皇帝的新装》了吗？https://youtu.be/b7NZfkqFc6k</br>————————————————————————————————</br>帝王为啥总要杀有功之臣？https://youtu.be/qXg1r_FwkvA</br>————————————————————————————————</br></br>有想看的内容可能在下面留言！</br></br>
#+END_EXPORT


*** “永动机”、“水变油”为啥都是骗局？李永乐老师讲热力学第一定律

http://www.youtube.com/watch?v=u-6gHRvFm2w

#+BEGIN_EXPORT HTML
有小朋友跟我说他的老乡正在鼓动他参与一个集资项目</br>要造一个滴水变石油的工程</br>他问我这个工程有没有前途</br>那么要说滴水变石油</br>咱们不妨先从一个概念永动机说起</br></br>第一类永动机是什么样子的？</br>水真的能变成油吗？</br>永动机有很多骗局，详见视频。</br></br>热力学第二定律视频推荐：</br>“麦克斯韦妖”是什么鬼？https://youtu.be/4JbgLx4_Ets</br></br>
#+END_EXPORT




** 感悟人生系列
https://www.youtube.com/playlist?list=PLOrDt87s8A3pCbRuOaW8FF76qxNZpf90B



https://i.ytimg.com/vi/b7NZfkqFc6k/sddefault.jpg


*** 你真的看懂《皇帝的新装》了吗？心知肚明和说出来有啥区别？李永乐老师讲“呐喊”的力量（2018最新）

http://www.youtube.com/watch?v=b7NZfkqFc6k

#+BEGIN_EXPORT HTML
有小朋友学习了《皇帝的新装》这篇课文，他问我明明大家都知道皇帝没有穿衣服，为什么小孩喊出这句话却造成了这么大的影响呢</br>这是因为:“大家都知道”和“大家知道大家都知道”是不一样的</br>在这个视频中，我通过一个经典逻辑问题:红眼睛和蓝眼睛来带大家了解一下共有知识和公共知识的区别</br>在社会中，有许多大家彼此心知肚明的事情，就是共有知识</br>而经过讨论之后，共有知识才能变成公共知识</br>比如一只垃圾股票，大家都知道它是垃圾</br>但是大家不知道别人是不是知道它是垃圾，所以股票的价格可能还会很高</br>一旦大家都清楚大家都知道这个股票是没有价值的，那么就不会有人再买它，它的价格就会一下子跌下来</br>这个过程很可能是一个事件一篇报道等，这就是呐喊的力量</br></br>
#+END_EXPORT


*** 特斯拉和爱迪生谁更猛？李永乐老师9分钟解读特斯拉的传奇一生

http://www.youtube.com/watch?v=VYZGKj3Iyx8

#+BEGIN_EXPORT HTML
今天我们想一起带大家了解一下</br>科学界的一个传奇人物尼古拉特斯拉</br>我们今天生活的方方面面都在得益于特斯拉的贡献</br>但是特斯拉却没有因此获得巨大的商业成功</br>晚年的时候穷困潦倒 究竟是怎么一回事</br>详见视频</br></br>科学界一直有公认说有两个科学家是一直被人类低估的</br>这两个科学家 一个是尼古拉·特斯达</br>还有一个就是莱奥纳多·达芬奇</br></br>
#+END_EXPORT


*** 人生中最重要的概念：复利，是什么？想贷款和分期就必须要了解它；李永乐老师讲自然对数的底e （2018最新）

http://www.youtube.com/watch?v=2a6gDHfWQGA

#+BEGIN_EXPORT HTML
有同学问我</br>这个自然对数的底e到底是什么</br>这个复利和单利到底有什么样的差别</br>今天我们把这两个问题一起来讨论一下</br></br>首先我们先来讨论一下自然对数的底</br>自然对数的底</br>其实这个数还有一个名字叫欧拉数</br>它一般是用字母e来表示的</br></br>当n趋近无穷大的时候，(1+1/n)^n=e</br>有一个更好计算的方法就是泰勒展开</br>1/0! +1/1! +1/2! +1/3! +…</br></br>那么e在工程应用非常多</br>在利息计算中，连续复利就是跟e有很大关系</br></br>PV×(1+r/n)^n=FV</br></br>当n趋于无穷时，FV=PV×e^r</br></br>连续复利它跟这个利率关系很大</br>如果这个利息比较高的话</br>那么连续复利就比普通利息要高出很多了</br></br>
#+END_EXPORT


*** 成功学有用吗？幸存者偏差，一个活着就该明白的事！李永乐老师聊聊大牌球星的身价（2018最新）

http://www.youtube.com/watch?v=AbMTG8bzVfY

#+BEGIN_EXPORT HTML
高考刚刚结束 世界杯马上就要开始了</br>有人看到的这些天价球员 梅西 C罗</br>就说呀 唉 我运气不好</br>没有当一个踢足球 否则我现在就像他们一样有钱了</br>事实上真的是这样吗</br>今天我们来讨论一下这个问题</br>我们首先从高考全国二卷一个作文题目开始讲解</br></br>二战 " 期间，为了加强对战机的防护，英美军方调查了作战后幸存飞机上弹痕的分布，决定哪里弹痕多就加强哪里。然而统计学家沃德力排众议，指出更应该注意弹痕少的部位，因为这些部位受到重创的战机，很难有机会返航，而这部分数据被忽略了。事实证明，沃德是正确的。</br></br>为充分解答这个问题</br>得先明白幸存者偏差是什么</br></br>幸存者偏差的意思就是说</br>你只考察了幸存者所满足的特征</br>这并不能得出一个有说服力的结论来</br></br>这个结论能解释很多现象</br>比如</br>淹死的拜神者</br>用了20年不钝的刀</br>验证药物疗效的双房实验</br></br>比如，我们看到世界杯上那些天价球员</br>梅西 C罗 内马尔他们，就以为踢足球都会很有钱</br>但事实上中国许多球员工资还不到10万元</br></br>还有许多人研究成功学</br>从许多成功人士身上找到共同点</br>但却忽视了那些也具有同样特征的失败者</br>等等</br></br>反正就是</br>幸存者偏差，一个活着就该明白的事！</br></br>
#+END_EXPORT


*** 《我不是药神》里的格列卫凭什么这么贵？仿制药到底是不是假药？李永乐老师讲白血病（2018最新）

http://www.youtube.com/watch?v=Jzror32wTos

#+BEGIN_EXPORT HTML
最近一部电影《我不是药神》大热</br>电影里的慢性粒细胞性白血病经过人类几十年的研究</br>已经了解了致病原因</br>并且人类也研发出了针对这种疾病的靶向药物格列卫</br>长期使用格列卫可以非常好的控制病情</br>但是，因为新药研发需要投入大量的资金人力和时间</br>格列卫这种药物非常昂贵</br>于是就出现了仿制药仿制</br>药与原研药的药效相差无几</br>但是价格却非常便宜，印度在这方面做得比较多</br>慢性粒细胞性白血病到底是怎么回事？</br>格列卫为什么这么神奇？</br>仿制药是怎么做出来的？</br>为什么印度可以仿制我们却不仿制？</br>点开视频，一起了解一下</br></br>
#+END_EXPORT


*** 不能赚钱的股票就要割肉；不能爱的人就要分手；不会做的题就要跳过；李永乐老师讲经济学原理沉没成本（2018最新）

http://www.youtube.com/watch?v=IUDIz1WwBXg

#+BEGIN_EXPORT HTML
有同学问我 说万一他在考场上遇到了一道题</br>他做了半天发现还是不会做</br>这个时候它是应该继续做下去</br>还是应该果断放弃</br>今天我们来讨论一下这个问题</br></br>
#+END_EXPORT


*** 人们为啥总闯红灯？小企业开拓市场咋这么难？囚徒困境又是什么？李永乐老师讲解纳什均衡理论（2018最新）

http://www.youtube.com/watch?v=Upd1ESkn-Bo

#+BEGIN_EXPORT HTML
博弈论里面不得不提的一个人物就是约翰纳什</br>他提出了著名的理论，纳什均衡理论</br>纳什均衡中最著名的一个例子就是囚徒困境</br></br>纳什均衡还有一个很有意思的例子叫智猪博弈</br>智猪博弈实际上和大企业与小企业的关系比较像</br>A好像是大企业，这个大企业他可以开拓市场</br>同时他也可以在市场中获得更大的收益</br>B就是小企业，小企业也可以开拓市场</br>同时也可以从市场中获得收益</br>那么对于小企业来讲，它的最优策略是什么？</br>是等待，等待着什么时候，等待着把大企业把市场开拓好了</br>他直接上车，他如果非要自己去开拓市场的话</br>那么如果大企业也开始了，你的收益就是很少的</br></br>
#+END_EXPORT


*** 数学家有嫉妒心是有多可怕？李永乐老师讲最速降线和伯努利家族“宫斗”

http://www.youtube.com/watch?v=GKetjzfQG70

#+BEGIN_EXPORT HTML
最速降线问题最早是由伽利略提出的</br>从某一个A点建立一个光滑的轨道到侧下方的一点B</br>使得小球在重力作用下从A运动到B的时间最短</br></br>伽利略认为这个轨道应该是圆，但是很快被人否定了</br>伯努利家族的约翰伯努利解出了这个问题，并且向全欧洲的数学家挑战</br>最终他收到了来自老师莱布尼兹、老师的死敌牛顿、哥哥雅各布伯努利、学生洛必达以及自己的五份答案</br>这些答案都指向了同样的结果: 摆线</br>雅各布去世后，约翰的儿子丹尼尔伯努利也成长成一名出色的数学家</br>并且写出了巨著 《流体力学》。约翰由于嫉妒儿子</br>居然抄袭自己儿子的书，并抢在儿子之前发表</br>好在丹尼尔写书的过程中与很多科学家交流过</br>人们才戳穿了约翰的伎俩，这成为了伯努利家族的笑话</br>具体怎么回事？</br>点开视频看看吧！</br></br>
#+END_EXPORT


*** 帝王为啥总要杀有功之臣？美国为啥要对中国搞贸易战？李永乐老师用数学带你看清现实（2018最新）

http://www.youtube.com/watch?v=qXg1r_FwkvA

#+BEGIN_EXPORT HTML
中间最好是暂停下来思考一下</br></br>三姬分金</br>————————————————————</br>A B C 三人分100金币</br></br>规则：</br>A B C，依次提议分金币的方案</br>若提议未获半数以上通过，提议人处死；</br>处死之后呢，剩下那两个人，第二个人接着提</br>那如果要是通过了，获得半数以上通过，不包括半数</br>那么这个就按这个规则来分金币</br></br>假设：</br>三人都是聪明的，理性的</br>并且是人性本恶的</br>————————————————————————————————</br></br>以上规则，如果是四个人来提呢？情形会发生什么</br>老板意谓着是什么</br>低端人群意谓着什么</br>如果打破你的阶级固化</br>你是否需要与人共谋</br>老板为什么能赚最多</br></br></br>国家之间的关系也是一样</br>例如美国作为世界老大，总是联合一些三四流国家整老二</br>当年的苏联是老二，他通过意识形态把苏联搞散了</br>后来的日本是老二，广场协定把日本搞残了</br>后来俄罗斯越来越厉害，通过石油把俄罗斯搞废了</br>现在中国是老二，美国又通过贸易战开始搞中国</br>因为他担心，老二总想取代自己的位置。</br></br>李永乐老师带你分析以上数学模型，并给出此数学模型所代表的现实意义</br></br>
#+END_EXPORT


*** 支配宇宙的法则：什么是因果？过去、现在、未来如何区分？李永乐老师讲时光锥（2018最新）

http://www.youtube.com/watch?v=0auDcESroEA

#+BEGIN_EXPORT HTML
狭义相对论：时间膨胀是怎么回事？如何实现星际旅行？</br>https://youtu.be/h6tbHSyVmfo</br>————————————————————————————————</br>狭义相对论：运动的物体长度为啥会变短？</br>https://youtu.be/Zr0hpemgOuQ</br>————————————————————————————————</br>在相对论看来不同参考系下同时性会被破坏</br>也就是说在某个参考系下看事件A先发生</br>换一个参考系很可能是事件B先发生</br>那这会不会违背因果律？</br></br>首先我们要了解什么是空间间隔和时间间隔</br>然后学习三大间隔：类时间隔，类光间隔，类空间隔</br>如何判定事件是属于哪个间隔</br></br>最后就可以讲时光锥是怎么回事了</br>详见视频</br></br>
#+END_EXPORT


*** 光速为什么不能被超越？李永乐老师老师6分钟讲狭义相对论之质量增加（2018最新）

http://www.youtube.com/watch?v=zY11529Uia0

#+BEGIN_EXPORT HTML
狭义相对论：时间膨胀是怎么回事？如何实现星际旅行？</br>https://youtu.be/h6tbHSyVmfo</br>————————————————————————————————</br>狭义相对论：运动的物体长度为啥会变短？</br>https://youtu.be/Zr0hpemgOuQ</br>————————————————————————————————</br>今天我们继续来讨论相对论的话题</br>有人问我说为什么宇宙中光速是最快的速度</br>为什么一个物体不能够通过加速的方式加到光速</br>我们今天就来解释一下这个问题</br>首先为了解释这件事 我们得先明白加速是怎么来的</br></br>物体的加速过程到底是怎么回事</br></br>牛顿第二定律又是什么</br></br>为什么在相对论的情况下物体无法超过光速</br>在相对论的情况下</br>爱因斯坦的相对论有一个结论</br>就是物体的质量会随着它的速度而发生变化</br>物体质量等于m0/√(1-(v/c)^2)</br></br>
#+END_EXPORT


*** 看懂了这个，你再去炒股；股市暴跌，为啥散户炒股票总赔钱？李永乐老师用数学告诉你！（2018最新）

http://www.youtube.com/watch?v=g-wCpEZBEdw

#+BEGIN_EXPORT HTML
今天中国的股市又暴跌了一下</br>这么多年以来，无论国际形势如何变化</br>中国的股民总是不忘初心，为祖国提供流动性</br>关于炒股赔钱这件事，每个人都有不同的想法</br></br>有的人想可能是我智商不够</br>也有人想可能我运气不好，总是踩不上点</br>但是大家会发现大部分股民都是赔钱的</br>那么这里有没有什么深刻的数学内涵？</br></br></br>美女与男人的游戏，数学模型中.....</br>男人和女人代表了什么</br>女人就像股市里的庄家一样，她可以拉升股价也可以打压股价</br>而男人就像我们散户一样</br>他可以买多，也可以买空，融券买空，对吧</br>如果庄家拉升股价而我们做多，我就会有很高的收益</br>如果庄家打压股价，我们做空我们也会有收益</br>但是如果庄家拉升股价，我们去做空我们就输了</br>如果庄家要是打压股价我们又做多，我们也输了</br>表面上看好像有涨有跌我们是可以赚到钱的</br>赚不到钱是你运气不好</br>但是庄家总是可以通过一定的策略让你一直赚不到钱</br></br>————————————————————————</br>第一个建议就是把自己的心态调整好</br>把自己的钱和时间用在更有意义的事情上</br>第二个建议，如果你一定要买股票的话</br>那么请你买那些基本面良好有发展前景的股票</br>而不要去买这些题材股，因为在题材股上有很多的庄家</br>它会通过一定的策略让你一直输钱 </br></br>这里是李永乐老师唯一Youtube频道</br></br>
#+END_EXPORT


*** 《复仇者联盟3》 灭霸为什么要杀掉宇宙一半的人？人类会无限增涨吗？李永乐老师带你了解马尔萨斯人口论（2018最新）

http://www.youtube.com/watch?v=NZcqNE5NgGY

#+BEGIN_EXPORT HTML
最近有一部电影叫做《复仇者联盟3》</br>里面有一个超级大反派 叫做灭霸</br>灭霸这个人 他为了维持宇宙的平衡</br>要消灭宇宙中一半的生物</br></br>地球上的人欲望太膨胀 所以资源不够</br>于是就要把地球上的人杀一半</br>大家可能觉得这只不过是天方夜谭</br>但是实际上历史上真的有人</br>把这种理论当作一种科学理论进行研究</br>还有 依据这种理论造成了跟灭霸一样的后果</br></br>马尔萨斯人口论是马尔萨斯于1798年所创立的</br>关于人口增加与食物增加速度相对比的一种人口理论</br>其主要论点和结论为</br>生活资料按算术级数增加，而人口是按几何级数增长的，因此生活资料的增加赶不上人口的增长是自然的、永恒的规律</br>只有通过饥饿、繁重的劳动、限制结婚以及战争等手段来消灭社会“下层”，才能削弱这个规律的作用——马尔萨斯陷阱</br></br>马尔萨斯这个理论到底对 还是不对</br>我们现在还处于很大的争论之中</br></br>但是我们都要明白人是区别于动物最大的特点就是人具有人性</br>我们不能因为说穷人吃的粮食 我们就把穷人赶紧杀绝 对不对 </br></br>有一个年轻人读到了马尔萨斯人口论</br>他就想说这种东西用在人身上可能不太合理</br>至少不太合道德 但是如果用在动物身上就非常的合理</br>这个年轻人就写了一本书叫做《物种起源》</br>这个年轻人就是达尔文</br></br>
#+END_EXPORT


*** 爱因斯坦的数学很差吗？什么是罗氏几何和黎曼几何？它们曾经可是数学家的噩梦！

http://www.youtube.com/watch?v=_l7gyzguikE

#+BEGIN_EXPORT HTML
爱因斯坦的数学是不是非常差</br>其实这是一个谬误</br>爱因斯坦的数学其实很厉害</br>只是他在最开始自己解释广义相对论的时候</br>一直找不到合适的数学工具来阐述自己的思想</br>直到他发现了非欧几何这个有力的工具</br>广义相对论才得以提出</br>那么什么叫非欧几何</br>详见视频</br></br>
#+END_EXPORT


*** 老哥的一句“我先走了”，成了生命中最后一句话！高空跳水有多危险？李永乐老师讲重力加速度与缓冲

http://www.youtube.com/watch?v=Yn851GQBsWw

#+BEGIN_EXPORT HTML
火热视频推荐：</br>——————————————————————————————————————</br>宇宙中最大的数是啥？https://youtu.be/eSYN2UN3SXM</br>————————————————————————————————</br>支配宇宙的法则：什么是因果？https://youtu.be/0auDcESroEA</br></br>历史上的三次数学危机推荐：</br>——————————————————————————————————————</br>第一次数学危机是什么？https://youtu.be/nAOVQEcqjSM</br>————————————————————————————————</br>第二次数学危机是什么？https://youtu.be/S5z7xYfGNXs</br>————————————————————————————————</br>第三次数学危机是什么？https://youtu.be/GWTVAYQytJ8</br></br>经济学视频推荐：</br>——————————————————————————————————————</br>你存银行的钱都去哪了？https://youtu.be/OTe3Bbcixow</br>————————————————————————————————</br>贷款 买房，利息怎么算？https://youtu.be/T6FBfNpiBYw</br>————————————————————————————————</br></br>值得深思的视频推荐：</br>——————————————————————————————————————</br>你真的看懂《皇帝的新装》了吗？https://youtu.be/b7NZfkqFc6k</br>————————————————————————————————</br>帝王为啥总要杀有功之臣？https://youtu.be/qXg1r_FwkvA</br>————————————————————————————————</br></br>有想看的内容可能在下面留言！</br></br>
#+END_EXPORT


*** 无穷大和无穷大+1谁更大？直线上的点多还是平面上的点多？李永乐老师讲神奇的希尔伯特旅馆

http://www.youtube.com/watch?v=M2apWwvOqko

#+BEGIN_EXPORT HTML
数学家希尔伯特提出了一个著名的问题：</br>如果一个旅店有无穷多个房间，每个房间都住满了人，现在又来了一个人，还能把所有人安排进旅店吗？</br>这个问题还有许多变形，</br>例如来了3个人，来了无穷多个人， 来了无穷多个巴士，每个巴士上有无穷多个人，又能不能安排好呢？</br>按照数学原理，这些情况下旅客其实都可以住进去。</br>这涉及到无限集合中“势”的概念。</br>只要能够建立一一对应的关系， 两个集合就是等势的，元素个数就是一样多的。</br>所以全体正整数和全体正偶数一样多，全体正数和全体实数一样多，</br>直线上的点和平面上的点一样多。。。</br>具体怎么回事？点开视频看看吧!</br></br>大家有什么喜欢看的视频内容可以在评论区留言！</br></br>火热视频推荐：</br>——————————————————————————————————————</br>宇宙中最大的数是啥？https://youtu.be/eSYN2UN3SXM</br>————————————————————————————————</br>支配宇宙的法则：什么是因果？https://youtu.be/0auDcESroEA</br></br>
#+END_EXPORT


*** 如何利用太阳光压飞出太阳系？李永乐老师10分钟讲光帆飞船！

http://www.youtube.com/watch?v=cNwAwMg_agU

#+BEGIN_EXPORT HTML
爱因斯坦告诉我们</br>光具有粒子性</br>所以光撞击到物体表面上也会产生压力</br>叫做光压</br> 光帆飞船就是利用太阳光的光压前进的飞船</br>它曾经是人们的设想</br></br>但是2010年</br>日本发射的飞船伊卡洛斯号实践了这一梦想</br>它成功的利用光帆飞行到金星附近</br></br>有朝一日</br>人们可能会乘坐光帆飞船，飞出太阳系，飞向更加遥远的宇宙</br></br>
#+END_EXPORT


*** 为什么久赌必输？股票加杠杆，风险为啥这么大？李永乐老师讲赌徒输光原理

http://www.youtube.com/watch?v=AadaEc6pJpw

#+BEGIN_EXPORT HTML
有一个经典的问题：如果有两个赌徒</br>他们玩一个公平的游戏：每局游戏输赢1元钱</br>且每次游戏两个人获胜的概率都是50%</br>游戏重复多次，直到一方输光，另一方赢到全部的钱为止</br>那么，最终两人谁输谁赢的概率与两人最初的资金量有关</br>资金量大的一方有更大的概率赢到全部的钱</br>资金量小的一方有更大的概率输光所有的钱</br>如果有一方的资金量是无限的</br>那么另一方有100%的概率会输光</br></br>赌徒与赌场对赌</br>由于赌场的资金相比于赌徒接近于无限</br>只要赌徒一直下注，即使是公平游戏，最终也一定会输光</br>这个问题同样可以解释在股票市场上加杠杆时的风险性</br>杠杆比例越高，输光的概率就越大</br>普希金的童话《渔夫与金鱼》也说明了同样的问题：</br>贪婪的人最终将一无所有</br>数学原理是什么？</br>点开视频看看吧！</br></br>
#+END_EXPORT


*** 什么样的投资值得做？圣彼得堡悖论是怎么回事？李永乐老师讲边际效用递减

http://www.youtube.com/watch?v=RwbsL0JUmbM

#+BEGIN_EXPORT HTML
最近有小朋友问我说 他的朋友让他进行一项投资</br>他知道这个投资有一定的概率会赚到很多钱</br>但是也有亏本的可能</br>他问我如何去评估这个项目该不该投呢</br>我们今天就来研究一下这个问题</br></br>详见视频！</br>大家有喜欢的话题内容可以在评论区留言。</br></br>火热视频推荐：</br>————————————————————————————————</br>为什么久赌必输？https://youtu.be/AadaEc6pJpw</br>输了钱就加倍下注吗？https://youtu.be/yoOocF47BRI</br>1+2+3+4+...=-1/12？https://youtu.be/T93SayXhw2w</br>————————————————————————————————</br></br>
#+END_EXPORT


*** 如何说话让人喜欢？怎么做生意更吸引顾客？李永乐老师讲框架效应

http://www.youtube.com/watch?v=xlmep_us15I

#+BEGIN_EXPORT HTML
有小朋友跟我说他是办公室的一个科员</br>每当他向领导汇报工作的时候 领导总是很不开心</br>但他的同事向领导汇报工作的时候 领导就很开心</br>他说本来都是同一个工作 为什么不同的人汇报差别会这么大</br>今天我们就来研究一下这个问题</br></br>火热视频推荐：</br>————————————————————————————————</br>为什么久赌必输？https://youtu.be/AadaEc6pJpw</br>输了钱就加倍下注吗？https://youtu.be/yoOocF47BRI</br>双11优惠规则为啥这么复杂？https://youtu.be/CDORrtQu3fE</br>什么样的投资值得做？https://youtu.be/RwbsL0JUmbM</br>————————————————————————————————</br></br>
#+END_EXPORT


*** 基因编辑是啥？CRISPR/cas9技术如何修改DNA？李永乐老师讲基因工程（1）

http://www.youtube.com/watch?v=o1MdiW5UZh0

#+BEGIN_EXPORT HTML
最近，中国深圳的科学家贺建奎宣布：</br>自己通过CRISPR/cas9技术修改了人类胚胎细胞的基因</br>并且利用这个胚胎降生了一对双胞胎</br>这个消息犹如一颗炸弹迅速在全世界范围内引发了激烈了批评</br>许多科学家斥责贺建奎不负责任，打破了人类的共识</br>基因工程是最近发展起来的生物技术</br>CRISPR/cas9是人类从细菌对抗噬菌体的过程中获得启发开拓的新方法</br>让人类可以高效低价的修改DNA</br>利用基因工程，人类可以“随心所欲”的更改动植物甚至人类自身的基因</br>从而让农作物和牲畜生长的更好，或者对抗人类自身的疾病</br>但是， 如果允许修改人类的胚胎细胞</br>除了面临医学风险外，还可能不可逆的改变人类基因库</br>造成不平等或引发更深刻的伦理学问题</br>世界各国都对人体胚胎细胞修改有严格的限制</br>CRISPR/cas9技术到底是什么？ </br>为什么能够修改基因？ </br>点开视频看看吧！</br></br>火热视频推荐：</br>————————————————————————————————</br>为什么久赌必输？https://youtu.be/AadaEc6pJpw</br></br>人造太阳EAST装置啥原理？https://youtu.be/q-9wxg9tQRk</br></br>什么样的投资值得做？https://youtu.be/RwbsL0JUmbM</br></br>怎么做生意更吸引顾客？https://youtu.be/xlmep_us15I</br>————————————————————————————————</br></br>
#+END_EXPORT




** 相对论
https://www.youtube.com/playlist?list=PLOrDt87s8A3r4X6gzfA2wIwqmARLcYMXw



https://i.ytimg.com/vi/zY11529Uia0/sddefault.jpg


*** 光速为什么不能被超越？李永乐老师老师6分钟讲狭义相对论之质量增加（2018最新）

http://www.youtube.com/watch?v=zY11529Uia0

#+BEGIN_EXPORT HTML
狭义相对论：时间膨胀是怎么回事？如何实现星际旅行？</br>https://youtu.be/h6tbHSyVmfo</br>————————————————————————————————</br>狭义相对论：运动的物体长度为啥会变短？</br>https://youtu.be/Zr0hpemgOuQ</br>————————————————————————————————</br>今天我们继续来讨论相对论的话题</br>有人问我说为什么宇宙中光速是最快的速度</br>为什么一个物体不能够通过加速的方式加到光速</br>我们今天就来解释一下这个问题</br>首先为了解释这件事 我们得先明白加速是怎么来的</br></br>物体的加速过程到底是怎么回事</br></br>牛顿第二定律又是什么</br></br>为什么在相对论的情况下物体无法超过光速</br>在相对论的情况下</br>爱因斯坦的相对论有一个结论</br>就是物体的质量会随着它的速度而发生变化</br>物体质量等于m0/√(1-(v/c)^2)</br></br>
#+END_EXPORT


*** 支配宇宙的法则：什么是因果？过去、现在、未来如何区分？李永乐老师讲时光锥（2018最新）

http://www.youtube.com/watch?v=0auDcESroEA

#+BEGIN_EXPORT HTML
狭义相对论：时间膨胀是怎么回事？如何实现星际旅行？</br>https://youtu.be/h6tbHSyVmfo</br>————————————————————————————————</br>狭义相对论：运动的物体长度为啥会变短？</br>https://youtu.be/Zr0hpemgOuQ</br>————————————————————————————————</br>在相对论看来不同参考系下同时性会被破坏</br>也就是说在某个参考系下看事件A先发生</br>换一个参考系很可能是事件B先发生</br>那这会不会违背因果律？</br></br>首先我们要了解什么是空间间隔和时间间隔</br>然后学习三大间隔：类时间隔，类光间隔，类空间隔</br>如何判定事件是属于哪个间隔</br></br>最后就可以讲时光锥是怎么回事了</br>详见视频</br></br>
#+END_EXPORT


*** 狭义相对论：时间膨胀是怎么回事？如何实现星际旅行？李永乐老师讲双生子佯谬思想实验！

http://www.youtube.com/watch?v=h6tbHSyVmfo

#+BEGIN_EXPORT HTML
火热视频推荐：</br>《我不是药神》里的格列卫凭什么这么贵？仿制药到底是不是假药？</br>视频链接：https://youtu.be/Jzror32wTos</br>———————————————————————————————————————</br>上一回我们讲了狭义相对论的两个基本原理</br>一个是光速不变原理 一个是相对论原理</br>而且还讲了狭义相对论中两个有意思的特点</br>第一个就是运动的物体长度会收缩</br>第二个是同时的相对性</br>那么我们这一次再来讲一下</br>狭义相对论中另外一个有意思的地方 就是时间膨胀</br>什么叫时间膨胀</br>时间膨胀意思是说运动的物体它的时间会变慢</br></br>太空旅客中男主角的飞船要飞多久才能到达目的地</br></br>著名的"双生子佯谬"思想试验又该怎么解释</br></br>打开视频看看吧</br></br>
#+END_EXPORT


*** 光在引力场中会弯曲吗？黑洞里时间会停滞？李永乐老师讲广义相对论（2018最新）

http://www.youtube.com/watch?v=xyWfXAmcFPE

#+BEGIN_EXPORT HTML
热门视频：</br>霍金研究的黑洞到底是什么？https://youtu.be/uK3_tg6qeiE</br>宇宙大爆炸是怎么回事？https://youtu.be/o-E3_zxajmQ</br>——————————————————————————————————</br>爱因斯坦为了把引力场纳入自己的理论，提出了广义相对论</br>广义相对论中，他把引力与加速度等同起来</br>在这样的基本原则下,光线会由于引力而发生弯曲</br>而且，时间也会因为引力场而变慢。</br>如果物体接近黑洞,时钟就会越走越慢</br>这就是所谓的引力红移现象</br>在视界边缘,时钟就会停滞</br> 广义相对论是我们理解宇宙的重要武器</br>在这个视频中给大家做一个简单的介绍</br></br>
#+END_EXPORT


*** 狭义相对论：运动的物体长度为啥会变短？李永乐老师讲相对论之火车隧道悖论（2018最新）

http://www.youtube.com/watch?v=Zr0hpemgOuQ

#+BEGIN_EXPORT HTML
火热视频推荐：《我不是药神》里的格列卫凭什么这么贵？仿制药到底是不是假药？</br>视频链接：https://youtu.be/Jzror32wTos</br></br>爱因斯坦在1905年提出狭义相对论</br>他有两个基本假设：相对性原理和光速不变原理</br>根据这两个原理</br>运动的物体在运动方向上会发生长度收缩</br>在某个参考系下同时发生的事,在另一个参考系下就不是同时发生的了</br>这些结论与生活中的常识非常不一致</br>以至于会引发一些悖论</br>比如著名的梯子悖论(火车隧道悖论)</br>相对论的假设究竟是什么?</br>悖论如何产生?又如何解释?</br>点开视频看看吧</br></br>
#+END_EXPORT


*** 光速是如何测量的？李永乐老师7分钟讲光速测量史

http://www.youtube.com/watch?v=1Y3p1EUGXxE

#+BEGIN_EXPORT HTML
狭义相对论：时间膨胀是怎么回事？如何实现星际旅行？</br>https://youtu.be/h6tbHSyVmfo</br>---------------------------------------------------------</br>狭义相对论：运动的物体长度为啥会变短？</br>https://youtu.be/Zr0hpemgOuQ</br>---------------------------------------------------------</br></br>
#+END_EXPORT




** 量子物理
https://www.youtube.com/playlist?list=PLOrDt87s8A3rTu_XAg7GZODkRA_FqoOm7



https://i.ytimg.com/vi/BzyOoo4AOxs/sddefault.jpg


*** 18个量子比特纠缠是什么？量子计算机为何如此强大？李永乐老师讲量子的纠缠态与叠加态（2018最新）

http://www.youtube.com/watch?v=BzyOoo4AOxs

#+BEGIN_EXPORT HTML
PRL上发表的论文名称：</br>18-Qubit Entanglement with Six Photons’ Three Degrees of Freedom</br></br>中国科学技术大学潘建伟实验室</br>在量子领域又获得了突破</br>实现了18个比特的量子纠缠</br>那么这18个比特量子纠缠到底是什么意思</br>它又有什么用</br>今天 就想带大家来了解一下这个问题</br></br>首先说一下量子的纠缠态与叠加态</br>其中涉及到光子的路径 偏振和角动量相关的内容</br></br>然后讲潘建伟团队实现18个光量子比特纠缠大概是怎么回事</br>经典计算机可能与量子计算机的区别</br>量子计算机是为什么这么强大</br></br>详见视频</br></br>最后，特别鸣谢中科院量子信息重点实验室崔超涵同志</br></br>
#+END_EXPORT


*** 量子加密是什么原理？李永乐老师讲量子隐形传输！

http://www.youtube.com/watch?v=dgNyGjwwYpk

#+BEGIN_EXPORT HTML
推荐视频</br>世界杯火爆视频  如何买足彩稳赚不赔：https://www.youtube.com/watch?v=YXW6GxYafp8</br>世界杯火爆视频  C罗电梯球踢法：https://www.youtube.com/watch?v=aT4zV96sjVE</br></br>什么是量子隐形传输</br>为什么量子隐形传输可以保证我们的通讯是安全的</br>要理解这个问题</br>首先我们得先理解一下密码学的基本原理</br>详见视频</br></br>关于量子通讯</br>我们首先要明白</br>量子力学的两个基本原理</br>第一个叫做量子不可克隆原理</br>第二个叫做量子的观测不对异性</br></br>量子或小兔子有以下两个状态</br>一个是圆偏振状态  它分左旋和右旋</br>一个是线偏振状态  它分水平和竖直</br></br>理解了以上概念后，我们就可以知道量子加密的原理了</br></br>
#+END_EXPORT


*** 量子力学和相对论的开端是什么？李永乐老师8分钟告诉你（2018最新）

http://www.youtube.com/watch?v=deBr1ybSf_8

#+BEGIN_EXPORT HTML
19世纪物理学的天空中还有两朵乌云是什么</br>量子力学和相对论到底是啥玩意？</br>黑体具有哪些性质？</br>光是波还是粒子？</br>什么是瑞利-金斯公式？</br>爱因斯坦光电效应最后就得了诺贝尔奖；这里都会告诉你</br>这里是李永乐老师唯一Youtube频道</br></br>
#+END_EXPORT


*** “千克”是如何被重新定义的？它和量子霍尔效应有啥关系？李永乐老师讲功率秤

http://www.youtube.com/watch?v=E-IBVXNHyKc

#+BEGIN_EXPORT HTML
在2018年11月16号的时候 国际计量局召开一个会议</br>决定自2019年5月20号重新更改千克的定义</br>有同学就问我说这个千克是为什么要重新定义呢</br>它是怎么重新定义的呢</br>今天我们就来研究一下这个问题</br>为了研究这件事 我们首先来研究一下量子霍尔效应</br>详见视频！</br></br>火热视频推荐：</br>————————————————————————————————</br>基因编辑是啥？CRISPR/cas9技术如何修改DNA？https://youtu.be/o1MdiW5UZh0</br></br>为什么久赌必输？https://youtu.be/AadaEc6pJpw</br></br>人造太阳EAST装置啥原理？https://youtu.be/q-9wxg9tQRk</br></br>什么样的投资值得做？https://youtu.be/RwbsL0JUmbM</br>————————————————————————————————</br></br>
#+END_EXPORT




** 世界杯
https://www.youtube.com/playlist?list=PLOrDt87s8A3q3drJDotVIutdISXMPqL37



https://i.ytimg.com/vi/gWC6OoWasMo/sddefault.jpg


*** 世界杯中的足球有几个面？欧拉都会证明错的问题被谁证明了？李永乐老师讲正多面体（2018最新）

http://www.youtube.com/watch?v=gWC6OoWasMo

#+BEGIN_EXPORT HTML
2018年俄罗斯世界杯 开始了</br>那么</br>大家看了这么多年足球比赛</br>有没有仔细观察过足球</br>足球是不是一个正多面体</br>它有什么数学的内涵在里面</br>今天我们就来研究一下足球</br></br>足球其实是由12个正五边形，一般是涂成黑色</br>还有20个正六边形，一般是白色的</br>组成的</br></br>由此视频讲解了多面体的由来及性质</br>正多面体只有五种，分别是</br>正4面体</br>正6面体</br>正8面体</br>正12面体</br>正20面体</br></br>它们都有一个性质就是F+V-E=2</br>就是正多面体的面数加顶点数减去边数等于2</br>这个定理的证明连欧拉的证明过程都是有漏洞的</br></br>最后这个定理被柯西给出的严格证明</br>通过柯西证明的这个欧拉提示性定理</br>人们就可以证明柏拉图立体或者说正多面体就只有这五种</br></br>
#+END_EXPORT


*** 2018世界杯足彩竞猜：一个稳赚不赔的方法是什么？李永乐老师教你足球彩票对冲套利（2018最新）

http://www.youtube.com/watch?v=YXW6GxYafp8

#+BEGIN_EXPORT HTML
世界杯还在如火如荼的进行</br>昨晚德国队爆冷 输给了墨西哥</br>然后很多买了彩票的小朋友 这个都输了很多钱</br>于是有同学就问我说</br>有没有什么办法在下注足球彩票的时候一定能赢钱</br>今天就给大家支个招</br>如何猜准世界杯胜负平</br></br>首先有以下几个概念要讲清楚</br>什么赔率</br>什么是期望</br>什么是返还率</br></br>然后我们再根据自己的判断</br>在一定条件一下</br>通过对冲的方法可以让你一定获利</br>而且可以保证每一场不会受到损失</br>详见视频</br></br>
#+END_EXPORT


*** 2018世界杯 C罗绝技电梯球上演帽子戏法，精妙绝伦！李永乐老师讲解如何踢出电梯球 香蕉球和落叶球

http://www.youtube.com/watch?v=aT4zV96sjVE

#+BEGIN_EXPORT HTML
C罗进球视频：https://www.youtube.com/watch?v=1EmAwblXnIY</br>世界杯火爆视频  如何买足彩稳赚不赔：https://www.youtube.com/watch?v=YXW6GxYafp8</br></br>2018世界杯 小组赛中</br>葡萄牙 对战 西班牙的那一场比赛</br>C罗宝刀未老 上演了一出帽子戏法</br>尤其是第88分钟的那一粒进球</br>绝对可以说是教科书式的进球</br>那么对于这个进球</br>有人说它是香蕉球 有人说是落叶球 也有人说是电梯球</br>那么这个球到底是什么球</br>今天我们就来讲解一下这三种球各有什么特点以及它们的原理</br></br>香蕉球和落叶球</br>它的共同特点就是在足球踢的过程中有旋转</br>但是</br>香蕉球是水平方向旋转的</br>落叶球是上下方向旋转的</br></br>电梯球并没有旋转</br>但是它的速度非常快</br>它开始的时候接近于直线运行</br>然后又急速下坠</br>就好像电梯一样急速到六楼一下子降下来了</br>人们就管这种球就叫电梯球</br></br>
#+END_EXPORT


*** 世界杯球场上的诡异足球轨迹，如何用爱因斯坦的理论来解释？李永乐老师讲布朗运动（2018最新）

http://www.youtube.com/watch?v=22Ho2YfP6bw

#+BEGIN_EXPORT HTML
世界杯火爆视频  如何买足彩稳赚不赔：https://www.youtube.com/watch?v=YXW6GxYafp8</br>世界杯火爆视频  C罗电梯球踢法：https://www.youtube.com/watch?v=aT4zV96sjVE</br></br>为什么足球的不确定性比篮球大得多</br>足球中，一个强队也未必会一定打得过弱队</br>足球有这么多不确定性</br>我们还是可以从某些科学的角度对它进行一些分析</br>比如今天我们想研究一下足球的轨迹</br></br>足球的这个运动轨迹看起来是杂乱无章的</br>但是我们在物理上有一个运动可以跟它非常非常像</br>那就是布朗运动</br>爱因斯坦是怎么研究布朗运动的</br>详见视频</br></br>从足球这个运动中抽象出一些科学内涵</br>而科学就是这样 从中找到一个比较重要的模型</br>它不见得完全符合实际</br>但是它可能对实际有一定的指导意义</br></br>
#+END_EXPORT


*** 成功学有用吗？幸存者偏差，一个活着就该明白的事！李永乐老师聊聊大牌球星的身价（2018最新）

http://www.youtube.com/watch?v=AbMTG8bzVfY

#+BEGIN_EXPORT HTML
高考刚刚结束 世界杯马上就要开始了</br>有人看到的这些天价球员 梅西 C罗</br>就说呀 唉 我运气不好</br>没有当一个踢足球 否则我现在就像他们一样有钱了</br>事实上真的是这样吗</br>今天我们来讨论一下这个问题</br>我们首先从高考全国二卷一个作文题目开始讲解</br></br>二战 " 期间，为了加强对战机的防护，英美军方调查了作战后幸存飞机上弹痕的分布，决定哪里弹痕多就加强哪里。然而统计学家沃德力排众议，指出更应该注意弹痕少的部位，因为这些部位受到重创的战机，很难有机会返航，而这部分数据被忽略了。事实证明，沃德是正确的。</br></br>为充分解答这个问题</br>得先明白幸存者偏差是什么</br></br>幸存者偏差的意思就是说</br>你只考察了幸存者所满足的特征</br>这并不能得出一个有说服力的结论来</br></br>这个结论能解释很多现象</br>比如</br>淹死的拜神者</br>用了20年不钝的刀</br>验证药物疗效的双房实验</br></br>比如，我们看到世界杯上那些天价球员</br>梅西 C罗 内马尔他们，就以为踢足球都会很有钱</br>但事实上中国许多球员工资还不到10万元</br></br>还有许多人研究成功学</br>从许多成功人士身上找到共同点</br>但却忽视了那些也具有同样特征的失败者</br>等等</br></br>反正就是</br>幸存者偏差，一个活着就该明白的事！</br></br>
#+END_EXPORT


*** 2018世界杯骗局：你见过半夜两点的太阳吗？李永乐老师讲经纬度和时差（2018最新）

http://www.youtube.com/watch?v=PBI9TxeaOrM

#+BEGIN_EXPORT HTML
世界杯火爆视频  如何买足彩稳赚不赔：https://www.youtube.com/watch?v=YXW6GxYafp8</br>世界杯火爆视频  C罗电梯球踢法：https://www.youtube.com/watch?v=aT4zV96sjVE</br></br>今天我在朋友圈里看别人发了个帖子</br>说本届世界杯就是最大的骗局</br>因为很多比赛都是半夜两点钟举行</br>你见过半夜两点钟还有太阳的吗</br></br>为了从科学角度解释这个问题</br>我们今天来讲一讲经纬度和时区的概念</br></br>视频中还解释了</br>极昼和极夜现象</br>日照时间是多少</br>什么叫中时区或者中央区</br>国际日期变更线又是怎么回事</br></br>详见视频</br></br>
#+END_EXPORT


*** 德国为啥被韩国绝杀？世界杯以弱战强的比赛策略是什么？李永乐老师告诉你（2018最新）

http://www.youtube.com/watch?v=8fAw1MQYW9c

#+BEGIN_EXPORT HTML
世界杯火爆视频  如何买足彩稳赚不赔：https://www.youtube.com/watch?v=YXW6GxYafp8</br>世界杯火爆视频  C罗电梯球踢法：https://www.youtube.com/watch?v=aT4zV96sjVE</br></br>世界杯爆出了本届以来的最大冷门</br>卫冕冠军德国队 以0:2输给了韩国队</br>小组垫底 直接回家了</br>为什么一个弱队 像韩国</br>可以战胜这么强大的德国</br>这里面有没有什么数学内涵</br>今天我们就想来探讨一下这个问题</br>详见视频</br></br>像这种弱队防守强队进攻的策略在历史上非常多</br>比如说楚汉争霸的时候</br>这个刘邦弱小的时候就跟项羽去求和 </br>刘邦强大的时候就拼命的打项羽</br>那这所以这种情况下刘邦采用了一个正确的策略</br>而这个项羽就相反</br>项羽他自己强大的时候不去打刘邦</br>不去进攻反而是防守</br>反而跟这个刘邦要划江而治</br>那这样一来项羽就失败了</br></br>
#+END_EXPORT


*** 2018世界杯决赛预测：法国VS克罗地亚谁的胜率更大？李永乐用泊松分布预测世界杯冠军

http://www.youtube.com/watch?v=cNOT4gE5IDA

#+BEGIN_EXPORT HTML
火热视频推荐：《我不是药神》里的格列卫凭什么这么贵？仿制药到底是不是假药？</br>视频链接：https://youtu.be/Jzror32wTos</br></br>本届世界杯的冠军争夺将在法国和克罗地亚中展开</br>关于两队谁能走到最后，各路网友也展开了激烈讨论</br>在预测决赛结果时，有没有更为科学的方式</br>答案是有的</br>详见视频...</br></br>
#+END_EXPORT




** 视频大片
https://www.youtube.com/playlist?list=PLOrDt87s8A3pX0eOU1RgY0rYCXOIpVbO-



https://i.ytimg.com/vi/OKWRNzB5b10/sddefault.jpg


*** 一滴水如何浮起万吨巨轮？如何测量人的心脏体积？李永乐老师带你学阿基米德浮力原理（2018最新）

http://www.youtube.com/watch?v=OKWRNzB5b10

#+BEGIN_EXPORT HTML
不知道大家最近有没有看一个新闻</br>说我国新建造的一艘航母</br>这艘航母和我们从国外买的那艘辽宁号</br>两艘航母在大连碰了个面，还拍了一个合影</br>有人就问我说 航母的排水量是多少多少吨</br>这是什么意思呢</br></br>我们为了想研究这个问题</br>我们首先呢 从一个故事开始</br>就是阿基米德的王冠（详见视频）</br></br>这是一个故事 是不是真实的 不一定</br>但是阿基米德的确由这个问题出发</br>思考出了阿基米德浮力定律</br>他得出物体浮力大小</br>只跟物体排开的水的重力有关</br></br>所以舰船排水量就是舰船的质量</br>当然这还要分空载和满载</br></br>视频中还讲解了一个奇葩的问题</br>就是如何测量心脏的体积</br>详见视频</br></br>
#+END_EXPORT


*** 三体和嫦娥四号有什么联系？中继星鹊桥在拉格朗日点的哪个位置？李永乐老师带你了解嫦娥工程（2018最新）

http://www.youtube.com/watch?v=-QZ3bjRTpng

#+BEGIN_EXPORT HTML
我们知道在5月21号的时候</br>我国的一颗月球中继卫星鹊桥上天了</br>而且发射到了地月轨道的拉格朗日点L2上</br>有同学就问我 这个鹊桥到底是干嘛用的</br>这个拉格朗日点又是怎么回事呢</br>今天我们就来说一下这个问题</br>为了系统了解这个问题</br>我们首先从中国的登月计划叫做嫦娥工程说起</br></br>我们的嫦娥工程主要的目的是为了登月</br>它在2004年 正式开始实施</br>一共可以分为三个阶段</br>第一个阶段就是无人登月</br>第二个阶段就是载人登月</br>第三个阶段就是在月球上建立我们的基地</br></br>2007年的时候</br>我们发射了第一颗月球探测卫星 嫦娥一号</br>绕月飞行 但它最终会撞月</br></br>在2010年的时候</br>我们发射了嫦娥二号卫星</br>它的功能 也是首先绕月</br>但它不会撞月</br></br>2013年的时候 发射了嫦娥三号探测卫星</br>嫦娥三号的主要作用就是登月</br></br>2018年年底</br>我们会发射嫦娥四号卫星</br>嫦娥四号也是要登月</br>只不过它要实现在月球的背面登月</br></br>关于嫦娥工程我们还要分析拉格朗日点是什么</br>请观看视频进行理解</br></br>
#+END_EXPORT


*** 《复仇者联盟3》 灭霸为什么要杀掉宇宙一半的人？人类会无限增涨吗？李永乐老师带你了解马尔萨斯人口论（2018最新）

http://www.youtube.com/watch?v=NZcqNE5NgGY

#+BEGIN_EXPORT HTML
最近有一部电影叫做《复仇者联盟3》</br>里面有一个超级大反派 叫做灭霸</br>灭霸这个人 他为了维持宇宙的平衡</br>要消灭宇宙中一半的生物</br></br>地球上的人欲望太膨胀 所以资源不够</br>于是就要把地球上的人杀一半</br>大家可能觉得这只不过是天方夜谭</br>但是实际上历史上真的有人</br>把这种理论当作一种科学理论进行研究</br>还有 依据这种理论造成了跟灭霸一样的后果</br></br>马尔萨斯人口论是马尔萨斯于1798年所创立的</br>关于人口增加与食物增加速度相对比的一种人口理论</br>其主要论点和结论为</br>生活资料按算术级数增加，而人口是按几何级数增长的，因此生活资料的增加赶不上人口的增长是自然的、永恒的规律</br>只有通过饥饿、繁重的劳动、限制结婚以及战争等手段来消灭社会“下层”，才能削弱这个规律的作用——马尔萨斯陷阱</br></br>马尔萨斯这个理论到底对 还是不对</br>我们现在还处于很大的争论之中</br></br>但是我们都要明白人是区别于动物最大的特点就是人具有人性</br>我们不能因为说穷人吃的粮食 我们就把穷人赶紧杀绝 对不对 </br></br>有一个年轻人读到了马尔萨斯人口论</br>他就想说这种东西用在人身上可能不太合理</br>至少不太合道德 但是如果用在动物身上就非常的合理</br>这个年轻人就写了一本书叫做《物种起源》</br>这个年轻人就是达尔文</br></br>
#+END_EXPORT


*** 不能赚钱的股票就要割肉；不能爱的人就要分手；不会做的题就要跳过；李永乐老师讲经济学原理沉没成本（2018最新）

http://www.youtube.com/watch?v=IUDIz1WwBXg

#+BEGIN_EXPORT HTML
有同学问我 说万一他在考场上遇到了一道题</br>他做了半天发现还是不会做</br>这个时候它是应该继续做下去</br>还是应该果断放弃</br>今天我们来讨论一下这个问题</br></br>
#+END_EXPORT


*** 宇宙大爆炸是怎么回事？爱因斯坦一生中最大的错误又是什么？李永乐老师讲宇宙为什么是膨胀的（2018最新）

http://www.youtube.com/watch?v=o-E3_zxajmQ

#+BEGIN_EXPORT HTML
有同学问我</br>我们为什么要认为宇宙是从一次大爆炸开始的</br>科学家是如何得到这个结论的</br></br>为了说明这个问题 首先我们要从一个佯谬开始</br>称之为奥伯斯佯谬</br></br>所谓佯谬就指的是</br>和现实生活中的感觉完全相反的结论 叫佯谬</br>他说假如我们常规的宇宙是稳态的</br>就是宏观来看 这个宇宙是静止的 均匀的 并且是无限的</br>无限包含无限空间和无限时间</br>那么 你在夜晚的时候看天空</br>这个整个天空应该是明亮的</br>这就是奥伯斯佯谬</br></br>到底是谁第一个提出大爆炸呢</br>我们要说明这件事仍然是由广义相对论得到的</br>首先呢 爱因斯坦提出了广义相对论</br>广义相对论从一开始提出它的目的就是为了解释宇宙</br>但是很遗憾爱因斯坦最开始提出广义相对论的时候</br>认为宇宙还是静止不动的</br>所以他引入了一个叫做宇宙常数的东西来修正这个模型</br>他还是以静态模型来进行处理的</br>后来有一个俄罗斯科学家 名字叫亚历山大·弗里德曼</br>这个亚历山大他通过爱因斯坦的方程进行求解</br>发现 你如果认为宇宙不是静态的 而宇宙是一个膨胀的</br>那么你就不需要这个宇宙常数了 可以约掉</br>亚历山大这个结论比爱因斯坦更先进了一步</br>而爱因斯坦的确承认他自己错了</br>被称为自己一生中最大的一个错误 就是爱因斯坦认为的</br></br>
#+END_EXPORT


*** 基因编辑是啥？CRISPR/cas9技术如何修改DNA？李永乐老师讲基因工程（1）

http://www.youtube.com/watch?v=o1MdiW5UZh0

#+BEGIN_EXPORT HTML
最近，中国深圳的科学家贺建奎宣布：</br>自己通过CRISPR/cas9技术修改了人类胚胎细胞的基因</br>并且利用这个胚胎降生了一对双胞胎</br>这个消息犹如一颗炸弹迅速在全世界范围内引发了激烈了批评</br>许多科学家斥责贺建奎不负责任，打破了人类的共识</br>基因工程是最近发展起来的生物技术</br>CRISPR/cas9是人类从细菌对抗噬菌体的过程中获得启发开拓的新方法</br>让人类可以高效低价的修改DNA</br>利用基因工程，人类可以“随心所欲”的更改动植物甚至人类自身的基因</br>从而让农作物和牲畜生长的更好，或者对抗人类自身的疾病</br>但是， 如果允许修改人类的胚胎细胞</br>除了面临医学风险外，还可能不可逆的改变人类基因库</br>造成不平等或引发更深刻的伦理学问题</br>世界各国都对人体胚胎细胞修改有严格的限制</br>CRISPR/cas9技术到底是什么？ </br>为什么能够修改基因？ </br>点开视频看看吧！</br></br>火热视频推荐：</br>————————————————————————————————</br>为什么久赌必输？https://youtu.be/AadaEc6pJpw</br></br>人造太阳EAST装置啥原理？https://youtu.be/q-9wxg9tQRk</br></br>什么样的投资值得做？https://youtu.be/RwbsL0JUmbM</br></br>怎么做生意更吸引顾客？https://youtu.be/xlmep_us15I</br>————————————————————————————————</br></br>
#+END_EXPORT




** 经济学与生活
https://www.youtube.com/playlist?list=PLOrDt87s8A3oV_INolHOLEyD8Sp6XcMFa



https://i.ytimg.com/vi/IUDIz1WwBXg/sddefault.jpg


*** 不能赚钱的股票就要割肉；不能爱的人就要分手；不会做的题就要跳过；李永乐老师讲经济学原理沉没成本（2018最新）

http://www.youtube.com/watch?v=IUDIz1WwBXg

#+BEGIN_EXPORT HTML
有同学问我 说万一他在考场上遇到了一道题</br>他做了半天发现还是不会做</br>这个时候它是应该继续做下去</br>还是应该果断放弃</br>今天我们来讨论一下这个问题</br></br>
#+END_EXPORT


*** 你存银行的钱都去哪了？国家是如何通过存款准备金调控经济的？李永乐老师讲货币体系（2018最新）

http://www.youtube.com/watch?v=OTe3Bbcixow

#+BEGIN_EXPORT HTML
世界杯火爆视频  如何买足彩稳赚不赔：https://www.youtube.com/watch?v=YXW6GxYafp8</br>世界杯火爆视频  C罗电梯球踢法：https://www.youtube.com/watch?v=aT4zV96sjVE</br></br>最近央行降低了0.5个百分点的存款准备金率</br>存款准备金这个词 我们可能经常听说</br>但是很多人可能不知道是什么意思</br>所以今天我们就来说一说存款准备金</br>到底是怎么回事</br>详见视频</br></br>货币的问题实际上是有一个杠杆系数在里面的</br>你的准备金率降低了</br>那么你的总存款量就会增加</br>而银行的总存款量或者说贷款能力增加了之后</br>他就可以通过改变利息的方式把这个钱都贷出去</br>也就是说释放给社会 这样社会整个的资金量就变多了</br>于是这个商品经济可能就比较繁荣</br></br>那么如果在这个时候准备金率提高了</br>那么我们可能就是收紧了这个银根</br>这样一来我们市场所有的钱就减少了</br>就可以使经济过热稍微缓和一些</br>所以国家是通过这种准备金率反复变化的方式</br>来调节经济的进程</br></br>
#+END_EXPORT


*** 贷款/买房，利息怎么算？不要被忽悠了！李永乐老师讲等额本金和等额本息算法（2018最新）

http://www.youtube.com/watch?v=T6FBfNpiBYw

#+BEGIN_EXPORT HTML
你真的看懂《皇帝的新装》了吗？https://youtu.be/b7NZfkqFc6k</br>——————————————————————————————————————</br>帝王为啥总要杀有功之臣？https://youtu.be/qXg1r_FwkvA</br>——————————————————————————————————————</br></br>最近有小朋友跟我说他最近买了个房子</br>这买房子有两种还款方式</br>等额本金和等额本息</br>他问我这两种方式有什么区别</br>还有人跟他说你如果贷了款就不要提前还款</br>因为提前还款的话前面的利息就白还了</br>这些说法都对不对</br></br>咱们今天就研究一下贷款利息怎么算</br>以及如何防止小额贷款公司算高利息</br>要不要提前还款的问题</br>详见视频</br></br>
#+END_EXPORT


*** 二手车市场中的交易秘密是什么？诺贝尔奖中的柠檬市场是什么原理？李永乐老师带你解决信息不对称问题（2018最新）

http://www.youtube.com/watch?v=rarFWlm76D0

#+BEGIN_EXPORT HTML
有同学私信里问我</br>说他想买一辆二手车</br>然后去二手车市场转了好几天</br>也买不到一辆适合的二手车</br>还有同学告诉我</br>说他买了一辆车不想开了 没开几天就想卖</br>但是怎么也卖不出去</br>为什么二手车 做这个买卖这么难</br>今天我们来讨论一下这个问题</br></br></br>有一个美国的经济学家名字叫阿克洛夫</br>写了一篇论文就叫《柠檬市场》</br>他所谓的柠檬市场就是次品市场</br>关注的就是二手车市场</br>在他这篇文献中 提到了一个词叫做信息不对称</br>什么叫信息不对称呢</br>就是指在一个交易中交易的双方</br>对于产品的信息有一方比较了解 而另外一方不了解</br>于是了解的一方就可以利用这个优势去获得更多的利益</br></br></br>其实这个柠檬市场中的过程</br>我们就称之为劣币驱逐良币的过程</br></br>解决办法有三个</br>第一种方法就是法律</br>比如地沟油 注水猪肉的使用要用法律制约</br></br>第二种方法就是价格引导</br>比如保险</br></br>第三种就是信息披露</br>比如股票</br></br>
#+END_EXPORT


*** 人生中最重要的概念：复利，是什么？想贷款和分期就必须要了解它；李永乐老师讲自然对数的底e （2018最新）

http://www.youtube.com/watch?v=2a6gDHfWQGA

#+BEGIN_EXPORT HTML
有同学问我</br>这个自然对数的底e到底是什么</br>这个复利和单利到底有什么样的差别</br>今天我们把这两个问题一起来讨论一下</br></br>首先我们先来讨论一下自然对数的底</br>自然对数的底</br>其实这个数还有一个名字叫欧拉数</br>它一般是用字母e来表示的</br></br>当n趋近无穷大的时候，(1+1/n)^n=e</br>有一个更好计算的方法就是泰勒展开</br>1/0! +1/1! +1/2! +1/3! +…</br></br>那么e在工程应用非常多</br>在利息计算中，连续复利就是跟e有很大关系</br></br>PV×(1+r/n)^n=FV</br></br>当n趋于无穷时，FV=PV×e^r</br></br>连续复利它跟这个利率关系很大</br>如果这个利息比较高的话</br>那么连续复利就比普通利息要高出很多了</br></br>
#+END_EXPORT


*** 面对风险、机遇和挑战，你为什么总是赚小亏大？李永乐老师讲阿莱悖论

http://www.youtube.com/watch?v=8Tz1WAp4vRE

#+BEGIN_EXPORT HTML
火热视频推荐：</br>————————————————————————————————</br>为什么久赌必输？https://youtu.be/AadaEc6pJpw</br>输了钱就加倍下注吗？https://youtu.be/yoOocF47BRI</br>1+2+3+4+...=-1/12？https://youtu.be/T93SayXhw2w</br>什么样的投资值得做？https://youtu.be/RwbsL0JUmbM</br>————————————————————————————————</br>上一回我们讲了期望效用理论</br>我们知道了获得两块钱的满意度提升</br>并不等于获得一块钱满意度提升的两倍</br>但是无论是期望还是效用</br>这都属于传统经济学范畴</br>传统经济学认为人是理性的</br>但是现在我们在投资股票证券的时候</br>发现了很多的非理性行为</br>这又如何解释呢</br>今天我们就来研究一下这个问题</br></br>详见视频！</br>大家有喜欢的话题内容可以在评论区留言。</br></br>
#+END_EXPORT


*** 什么样的投资值得做？圣彼得堡悖论是怎么回事？李永乐老师讲边际效用递减

http://www.youtube.com/watch?v=RwbsL0JUmbM

#+BEGIN_EXPORT HTML
最近有小朋友问我说 他的朋友让他进行一项投资</br>他知道这个投资有一定的概率会赚到很多钱</br>但是也有亏本的可能</br>他问我如何去评估这个项目该不该投呢</br>我们今天就来研究一下这个问题</br></br>详见视频！</br>大家有喜欢的话题内容可以在评论区留言。</br></br>火热视频推荐：</br>————————————————————————————————</br>为什么久赌必输？https://youtu.be/AadaEc6pJpw</br>输了钱就加倍下注吗？https://youtu.be/yoOocF47BRI</br>1+2+3+4+...=-1/12？https://youtu.be/T93SayXhw2w</br>————————————————————————————————</br></br>
#+END_EXPORT


*** 双11优惠规则为啥这么复杂？穷人和富人被区别对待了？李永乐老师讲价格歧视

http://www.youtube.com/watch?v=CDORrtQu3fE

#+BEGIN_EXPORT HTML
双11马上就要到了</br>不知大家准备好剁手了没有</br>有一个小朋友给我发来私信说</br>双11的优惠政策他实在是看不懂</br>除了传统的打折以外</br>还有满减 反券 积分换好礼 跨店铺等等</br>他说双11的优惠为什么设置成这么复杂的规矩</br>为什么不直接来一个打折就完事了呢</br>今天我们就来研究一下这个问题</br></br>通过视频的内容解读，你可以了解到以下内容：</br>为什么苹果手机的内存为没有64G或者128G的情况？</br>对于讨价还价，为什么最赚钱的是卖方？</br>同一款车，为什么为了个配置却贵了这么多？</br>收集优惠券是一种什么心态？</br></br>大家有什么喜欢的视频可以在下方留言。</br></br>火热视频推荐：</br>————————————————————————————————</br>为什么久赌必输？https://youtu.be/AadaEc6pJpw</br>输了钱就加倍下注吗？https://youtu.be/yoOocF47BRI</br>什么样的投资值得做？https://youtu.be/RwbsL0JUmbM</br>————————————————————————————————</br></br>
#+END_EXPORT


*** 如何说话让人喜欢？怎么做生意更吸引顾客？李永乐老师讲框架效应

http://www.youtube.com/watch?v=xlmep_us15I

#+BEGIN_EXPORT HTML
有小朋友跟我说他是办公室的一个科员</br>每当他向领导汇报工作的时候 领导总是很不开心</br>但他的同事向领导汇报工作的时候 领导就很开心</br>他说本来都是同一个工作 为什么不同的人汇报差别会这么大</br>今天我们就来研究一下这个问题</br></br>火热视频推荐：</br>————————————————————————————————</br>为什么久赌必输？https://youtu.be/AadaEc6pJpw</br>输了钱就加倍下注吗？https://youtu.be/yoOocF47BRI</br>双11优惠规则为啥这么复杂？https://youtu.be/CDORrtQu3fE</br>什么样的投资值得做？https://youtu.be/RwbsL0JUmbM</br>————————————————————————————————</br></br>
#+END_EXPORT


*** 从比较优势理论分析：中美为何会爆发贸易战？与鸦片战争有什么相似之处？李永乐老师告诉你

http://www.youtube.com/watch?v=nwLqo83iqks

#+BEGIN_EXPORT HTML
最近中美贸易战愈演愈烈 从最开始双方进行反倾销调查</br>到后来互加关税 再到现在美国直接对中国的个别企业进行制裁</br>甚至演变成外交风波</br>有小朋友就问我说 为什么中美之间会爆发这样一场贸易战</br>很显然这个问题是非常复杂的</br>那今天我们想从一个侧面贸易的角度来理解一下这个问题</br></br>视频中包含以下知识点：</br>1、什么是绝对优势？</br>2、什么是比较优势？</br>3、中英为什么会爆发鸦片战争？</br>4、中美为什么会爆发贸易战？</br>详见视频！</br></br>火热视频推荐：</br>基因编辑是啥？CRISPR/cas9技术如何修改DNA？https://youtu.be/o1MdiW5UZh0</br>为什么久赌必输？https://youtu.be/AadaEc6pJpw</br>输了钱就加倍下注，能回本吗？https://youtu.be/yoOocF47BRI</br>贷款/买房，利息怎么算？https://youtu.be/T6FBfNpiBYw</br></br>
#+END_EXPORT




** 宇宙物理
https://www.youtube.com/playlist?list=PLOrDt87s8A3q6Fnjc-sb_-OKRK_IVpo1B



https://i.ytimg.com/vi/Nfg8sglgGMk/sddefault.jpg


*** 亮剑里李云龙的“拇指测距”是啥原理？天体之间的距离又是如何测量的？李永乐老师教你视差法应用（2018最新）

http://www.youtube.com/watch?v=Nfg8sglgGMk

#+BEGIN_EXPORT HTML
在电视剧亮剑里面有一个情节</br>说是李云龙他指挥自己的部队</br>用拇指的办法测出了到敌人的距离</br>结果打了一枚炮弹过去 炸死了日本的指挥官</br>那么拇指测距到底是怎么回事呢</br>它本质是三角测量法，视频里会告诉你！</br></br>遥远的星球离我们非常遥远 </br>我们怎么知道地球到它距离的</br>其实这个方法和拇指测距类似</br>也是利用视差法</br></br>视频中还会讲到秒差距是什么</br>一般来讲在科技文献中都采用秒差距来研究</br>而不是采用光年这个单位</br></br>一个秒差距</br>大概是20.6万个天文单位</br>20.6万个日地距离  是3×10^16m</br></br>从太阳一直到银河系的中心大约是8000个秒差距</br>8000个秒差距大概是2.6万光年</br></br>
#+END_EXPORT


*** 宇宙大爆炸是怎么回事？爱因斯坦一生中最大的错误又是什么？李永乐老师讲宇宙为什么是膨胀的（2018最新）

http://www.youtube.com/watch?v=o-E3_zxajmQ

#+BEGIN_EXPORT HTML
有同学问我</br>我们为什么要认为宇宙是从一次大爆炸开始的</br>科学家是如何得到这个结论的</br></br>为了说明这个问题 首先我们要从一个佯谬开始</br>称之为奥伯斯佯谬</br></br>所谓佯谬就指的是</br>和现实生活中的感觉完全相反的结论 叫佯谬</br>他说假如我们常规的宇宙是稳态的</br>就是宏观来看 这个宇宙是静止的 均匀的 并且是无限的</br>无限包含无限空间和无限时间</br>那么 你在夜晚的时候看天空</br>这个整个天空应该是明亮的</br>这就是奥伯斯佯谬</br></br>到底是谁第一个提出大爆炸呢</br>我们要说明这件事仍然是由广义相对论得到的</br>首先呢 爱因斯坦提出了广义相对论</br>广义相对论从一开始提出它的目的就是为了解释宇宙</br>但是很遗憾爱因斯坦最开始提出广义相对论的时候</br>认为宇宙还是静止不动的</br>所以他引入了一个叫做宇宙常数的东西来修正这个模型</br>他还是以静态模型来进行处理的</br>后来有一个俄罗斯科学家 名字叫亚历山大·弗里德曼</br>这个亚历山大他通过爱因斯坦的方程进行求解</br>发现 你如果认为宇宙不是静态的 而宇宙是一个膨胀的</br>那么你就不需要这个宇宙常数了 可以约掉</br>亚历山大这个结论比爱因斯坦更先进了一步</br>而爱因斯坦的确承认他自己错了</br>被称为自己一生中最大的一个错误 就是爱因斯坦认为的</br></br>
#+END_EXPORT


*** 宇宙年龄是怎么计算的？地球会是宇宙的中心吗？李永乐老师8分钟讲解哈勃定律（2018最新）

http://www.youtube.com/watch?v=YAuXTVR9Vvc

#+BEGIN_EXPORT HTML
为了解释奥伯斯佯谬 人们提出了大爆炸的理论</br>大爆炸理论人们也通过了一些事例证明</br></br>但是，宇宙年龄是怎么计算的呢</br>今天我们就来研究一下这个问题</br>为了理解这些问题</br>要先了解多普勒效应</br></br>人们根据机械波多普勒效应又结合了相对论</br>就得出了相对论多普勒效应</br>会得到一个公式 频率 f=√((1-v/c)/(1+v/c))×f0</br>因为从这个公式上能看的出来</br>当出现星球相互远离的时候 星球相互远离的时候</br>这个频率是小于f0的 这个和普通多普勒效应是一样的</br>那么在这种情况下 它的频率下降了 波长就会变大</br>波长就大于发出来的波长</br>我们知道可见光中波长最长的就是红光</br>波长变大了 就会向红光频谱方向移动</br>所以这个现象就称之为红移现象</br></br>还有一个波长会变短现象 就称之为蓝移</br>但是蓝移现象不多 红移现象在宇宙中占了绝大多数</br></br>人们就知道了所有的发光星球好像都在离我们而去一样</br>于是人们把这个规律总结了一下 就提出了哈勃定律</br>根据哈勃定律我们就可以计算宇宙的年龄了</br></br>
#+END_EXPORT


*** 卫星天宫一号为什么要坠落？如何坠落？李永乐老师6分钟解释飞船变轨

http://www.youtube.com/watch?v=pyaOOyammQM

#+BEGIN_EXPORT HTML
万有引力提供向心力，卫星可以是离心运行也可以是向心运动！</br>李永乐老师唯一Youtube频道</br></br>
#+END_EXPORT


*** 霍金研究的黑洞到底是什么？李永乐老师6分钟带你了解奇妙的黑洞

http://www.youtube.com/watch?v=uK3_tg6qeiE

#+BEGIN_EXPORT HTML
李永乐老师唯一Youtube频道</br></br>
#+END_EXPORT


*** 三体和嫦娥四号有什么联系？中继星鹊桥在拉格朗日点的哪个位置？李永乐老师带你了解嫦娥工程（2018最新）

http://www.youtube.com/watch?v=-QZ3bjRTpng

#+BEGIN_EXPORT HTML
我们知道在5月21号的时候</br>我国的一颗月球中继卫星鹊桥上天了</br>而且发射到了地月轨道的拉格朗日点L2上</br>有同学就问我 这个鹊桥到底是干嘛用的</br>这个拉格朗日点又是怎么回事呢</br>今天我们就来说一下这个问题</br>为了系统了解这个问题</br>我们首先从中国的登月计划叫做嫦娥工程说起</br></br>我们的嫦娥工程主要的目的是为了登月</br>它在2004年 正式开始实施</br>一共可以分为三个阶段</br>第一个阶段就是无人登月</br>第二个阶段就是载人登月</br>第三个阶段就是在月球上建立我们的基地</br></br>2007年的时候</br>我们发射了第一颗月球探测卫星 嫦娥一号</br>绕月飞行 但它最终会撞月</br></br>在2010年的时候</br>我们发射了嫦娥二号卫星</br>它的功能 也是首先绕月</br>但它不会撞月</br></br>2013年的时候 发射了嫦娥三号探测卫星</br>嫦娥三号的主要作用就是登月</br></br>2018年年底</br>我们会发射嫦娥四号卫星</br>嫦娥四号也是要登月</br>只不过它要实现在月球的背面登月</br></br>关于嫦娥工程我们还要分析拉格朗日点是什么</br>请观看视频进行理解</br></br>
#+END_EXPORT


*** 椭圆，抛物线，双曲线为啥都是圆锥曲线？为什么长期能观测到的行星都是椭圆运行的？李永乐老师带你了解原因（2018最新）

http://www.youtube.com/watch?v=dmhgsLhLTM4

#+BEGIN_EXPORT HTML
有同学问 椭圆 抛物线 双曲线</br>这是几种曲线有什么联系呢</br>为什么它们一起叫做圆锥曲线呢</br>今天我们来讲一下这个问题</br></br>圆锥曲线这个词</br>其实是在古希腊的时候就已经被人提出了</br>那么 它的提出者名字叫做阿波罗尼斯</br></br>为什么名字叫圆锥曲线呢</br>因为它可以通过切割圆锥的办法得到</br></br>所以圆锥曲线可以大致分为三种</br>椭圆 抛物线和双曲线</br></br>而天体运动的轨迹也基本上是圆锥曲线</br>我们可以通过“牛顿大炮”来解决这个问题</br></br>在太阳系内部的这些行星都做椭圆运动</br>这就是因为它们速度不够</br>假如你把这个行星速度加速到一定程度</br>它就会做抛物线或双曲线运动</br>但问题是 一旦一个行星做抛物线和双曲线运动</br>它就再也不会回到太阳系了</br>我们知道抛物线和双曲线都不是闭合的</br>所以它会离我们而去</br>因此我们能长期观察到的行星都是椭圆运动的</br></br>
#+END_EXPORT


*** 太阳会死亡吗？红巨星、中子星和黑洞等都是哪来的？李永乐老师讲恒星演化

http://www.youtube.com/watch?v=Lf6srcoTpg8

#+BEGIN_EXPORT HTML
前两次我们一直在研究太阳的话题</br>有小朋友就问我说太阳也有寿命吗 它会死亡吗</br>听说白矮星 中子星 黑洞跟太阳之间有什么样的联系吗</br>今天我们就来研究一下这个问题</br></br>大家如何有喜欢的视频内容可以在下方留言！</br></br>火热视频推荐：</br>————————————————————————————————</br>为什么久赌必输？https://youtu.be/AadaEc6pJpw</br></br>人造太阳EAST装置啥原理？https://youtu.be/q-9wxg9tQRk</br></br>什么样的投资值得做？https://youtu.be/RwbsL0JUmbM</br></br>怎么做生意更吸引顾客？https://youtu.be/xlmep_us15I</br>————————————————————————————————</br></br>
#+END_EXPORT




** 烧脑影片
https://www.youtube.com/playlist?list=PLOrDt87s8A3rbac2koPGwNexaBeQqRpTU



https://i.ytimg.com/vi/35qKiTgXD60/sddefault.jpg


*** 别以为啥都是UFO！华北多地天空不明飞行物是什么情况？李永乐老师带你破局（2018最新）

http://www.youtube.com/watch?v=35qKiTgXD60

#+BEGIN_EXPORT HTML
前两天在北京山西等大片的华北地区</br>人们在晚上都看到了这样的一幕</br>有一个发光的云彩在那盘旋着上升</br>人们不知道是什么东西</br>还有人说这就是UFO</br>专家们给出了解释 说这实际上是一种航天器的现象</br></br>其实是航天器产生了一种叫做航线云（航迹云，飞机云）的东西</br>视频中会充分解释这种现象</br></br>另外，视频中还解释了夜光云，音障和音爆现象是怎么产生的</br>马赫锥又是什么</br>——————————————————————————————————————</br></br>看完以上视频，就别以为啥都是UFO了，老铁们</br></br>其实很多生活中的现象是可以使用科学进行解释的</br></br>
#+END_EXPORT


*** 爱因斯坦的数学很差吗？什么是罗氏几何和黎曼几何？它们曾经可是数学家的噩梦！

http://www.youtube.com/watch?v=_l7gyzguikE

#+BEGIN_EXPORT HTML
爱因斯坦的数学是不是非常差</br>其实这是一个谬误</br>爱因斯坦的数学其实很厉害</br>只是他在最开始自己解释广义相对论的时候</br>一直找不到合适的数学工具来阐述自己的思想</br>直到他发现了非欧几何这个有力的工具</br>广义相对论才得以提出</br>那么什么叫非欧几何</br>详见视频</br></br>
#+END_EXPORT


*** 四维空间到底是什么样子的？李永乐老师6分钟解释高维空间

http://www.youtube.com/watch?v=_8PYYnuoZP8

#+BEGIN_EXPORT HTML
频道中有字幕，看不到的请自己设置一下！</br>四维空间过一个点能做出四条相互垂直的直线，你能想象吗？</br>空间距离s=-√(x^2+y^2+z^2+m^2)</br>三体里的降维打击是什么？</br></br>这里都会告诉你！</br></br>这里是李永乐老师唯一Youtube频道</br></br>
#+END_EXPORT


*** 霍金研究的黑洞到底是什么？李永乐老师6分钟带你了解奇妙的黑洞

http://www.youtube.com/watch?v=uK3_tg6qeiE

#+BEGIN_EXPORT HTML
李永乐老师唯一Youtube频道</br></br>
#+END_EXPORT


*** 银行密码系统安全吗？质数（素数）到底有啥用？李永乐老师11分钟讲RSA加密算法（2018最新）

http://www.youtube.com/watch?v=D_kMadCtKp8

#+BEGIN_EXPORT HTML
人们花这么大力气去研究这些数学问题有什么意义</br>今天我就给大家来说一下数学的意义</br>比如说我们去银行存钱取钱 用到密码</br>那么密码就是基于数学的</br></br>有一种加密算法叫对称加密</br>对称加密是以前比较常见的一种加密方式</br>另一种最典型的非对称加密方式</br>叫做RSA加密算法 </br></br>RSA加密算法</br>是在1978年的时候 麻省理工MIT有三位数学教授</br>他们一起发明了这种算法</br>这种算法 三个人的名字分别叫R S和A打头</br>所以就叫RSA算法</br>RSA加密算法的原理在视频可以了解</br></br>有没有什么方式可以比较快的计算大数的质因数分解</br>有 那就是量子计算机</br>普通计算机算十年大数的质因数分解 它可能算一个星期就算出来了</br>那如果这样的话 这个我们的银行系统什么的可能都要更新</br>否则就没有办法保证安全</br>我们现在也知道每隔一段时间我们银行的系统都需要更新一次的</br>我们的数字证书都是要重新更新 否则就不能用了 这是为什么</br>因为我们要不停的更换我们算法和密钥以保证我们的安全性</br></br>
#+END_EXPORT


*** 手机支付中的数字签名是如何保证信息安全的？李永乐老师讲解生日碰撞和哈希函数（2018最新）

http://www.youtube.com/watch?v=uS1ZIAsvT5w

#+BEGIN_EXPORT HTML
今天 我们想给大家介绍一下</br>大家耳熟能详的一个词叫 数字签名</br>为了解这个问题我们得先讲解一下</br>生日碰撞和哈希函数</br></br>数字签名是指</br>发送方用自己的私钥对数字指纹进行加密后所得的数据</br>其中包括非对称密钥加密和数字签名两个过程</br>在可以给数据加密的同时</br>也可用于接收方验证发送方身份的合法性</br>采用数字签名时</br>接收方需要使用发送方的公钥才能解开数字签名得到数字指纹</br></br>但是生日碰撞对于这个数字签名来讲是一个威胁</br>我们应该避免这个问题</br></br>我们以前说过这样一句话</br>说这个世界上大部分的物理学家都是数学家</br>但是并不是所有都是这样</br>有一些实验物理学家他数学能力可能没有那么强</br>但是 世界上所有的计算机科学家都是数学家</br>100% 为什么</br>因为计算机科学本质上其实就是一个用电脑实现的数学问题</br></br>
#+END_EXPORT


*** 18个量子比特纠缠是什么？量子计算机为何如此强大？李永乐老师讲量子的纠缠态与叠加态（2018最新）

http://www.youtube.com/watch?v=BzyOoo4AOxs

#+BEGIN_EXPORT HTML
PRL上发表的论文名称：</br>18-Qubit Entanglement with Six Photons’ Three Degrees of Freedom</br></br>中国科学技术大学潘建伟实验室</br>在量子领域又获得了突破</br>实现了18个比特的量子纠缠</br>那么这18个比特量子纠缠到底是什么意思</br>它又有什么用</br>今天 就想带大家来了解一下这个问题</br></br>首先说一下量子的纠缠态与叠加态</br>其中涉及到光子的路径 偏振和角动量相关的内容</br></br>然后讲潘建伟团队实现18个光量子比特纠缠大概是怎么回事</br>经典计算机可能与量子计算机的区别</br>量子计算机是为什么这么强大</br></br>详见视频</br></br>最后，特别鸣谢中科院量子信息重点实验室崔超涵同志</br></br>
#+END_EXPORT


*** 科学家才能弄懂这十个公式！李永乐老师带你了解十个最美物理公式（2018最新）

http://www.youtube.com/watch?v=ngLMlJ9hbPA

#+BEGIN_EXPORT HTML
最近 中科院的科学开放日</br>科学家们在井盖上绘制发不同的科学公式和图案 非常皮</br>现在的中科院里面有很多年轻的科学家</br>我们将带大家了解一下这些公式到底是什么含义</br></br>第一个公式称之为傅里叶变换</br>第二个公式叫斯涅耳定律 </br>第三个公式麦克斯韦方程组</br>第四个公式称之为伯努利方程</br>第五个公式称之为薛定谔方程</br>第六个公式叫做海森堡不确定性原理</br>第七个公式是阿基米德浮力原理</br>第八个公式叫做质能方程</br>第九个公式叫做卡诺定理</br>第十个公式表示的叫熵</br></br>
#+END_EXPORT


*** 光速为什么不能被超越？李永乐老师老师6分钟讲狭义相对论之质量增加（2018最新）

http://www.youtube.com/watch?v=zY11529Uia0

#+BEGIN_EXPORT HTML
狭义相对论：时间膨胀是怎么回事？如何实现星际旅行？</br>https://youtu.be/h6tbHSyVmfo</br>————————————————————————————————</br>狭义相对论：运动的物体长度为啥会变短？</br>https://youtu.be/Zr0hpemgOuQ</br>————————————————————————————————</br>今天我们继续来讨论相对论的话题</br>有人问我说为什么宇宙中光速是最快的速度</br>为什么一个物体不能够通过加速的方式加到光速</br>我们今天就来解释一下这个问题</br>首先为了解释这件事 我们得先明白加速是怎么来的</br></br>物体的加速过程到底是怎么回事</br></br>牛顿第二定律又是什么</br></br>为什么在相对论的情况下物体无法超过光速</br>在相对论的情况下</br>爱因斯坦的相对论有一个结论</br>就是物体的质量会随着它的速度而发生变化</br>物体质量等于m0/√(1-(v/c)^2)</br></br>
#+END_EXPORT


*** 无穷大和无穷大+1谁更大？直线上的点多还是平面上的点多？李永乐老师讲神奇的希尔伯特旅馆

http://www.youtube.com/watch?v=M2apWwvOqko

#+BEGIN_EXPORT HTML
数学家希尔伯特提出了一个著名的问题：</br>如果一个旅店有无穷多个房间，每个房间都住满了人，现在又来了一个人，还能把所有人安排进旅店吗？</br>这个问题还有许多变形，</br>例如来了3个人，来了无穷多个人， 来了无穷多个巴士，每个巴士上有无穷多个人，又能不能安排好呢？</br>按照数学原理，这些情况下旅客其实都可以住进去。</br>这涉及到无限集合中“势”的概念。</br>只要能够建立一一对应的关系， 两个集合就是等势的，元素个数就是一样多的。</br>所以全体正整数和全体正偶数一样多，全体正数和全体实数一样多，</br>直线上的点和平面上的点一样多。。。</br>具体怎么回事？点开视频看看吧!</br></br>大家有什么喜欢看的视频内容可以在评论区留言！</br></br>火热视频推荐：</br>——————————————————————————————————————</br>宇宙中最大的数是啥？https://youtu.be/eSYN2UN3SXM</br>————————————————————————————————</br>支配宇宙的法则：什么是因果？https://youtu.be/0auDcESroEA</br></br>
#+END_EXPORT


*** 一片雪花的周长竟然能超过地球的直径？1.26维的图形是啥样？李永乐老师讲分形几何（2018最新）

http://www.youtube.com/watch?v=tEqKrJUwiHQ

#+BEGIN_EXPORT HTML
有小朋友给我提出了这样一个奇怪的问题</br>他说一片雪花的周长有多大</br>一片雪花和地球的直径相比哪个更大</br>他所问的这个问题其实涉及到分形几何的问题</br>所以今天我们就来研究一下分形几何</br></br>视频中的主要知识点：</br>英国的海岸线有多长？</br>科赫雪花是什么样子的？</br>谢尔宾斯基地毯斯是怎么回事？</br>豪斯托夫维度怎么计算？</br></br>想看，就打开视频看看吧！</br></br>
#+END_EXPORT




** 十部必看视频（李永乐老师推荐）
https://www.youtube.com/playlist?list=PLOrDt87s8A3o7clMOxRr5TOGqyDWLaZv7



https://i.ytimg.com/vi/_8PYYnuoZP8/sddefault.jpg


*** 四维空间到底是什么样子的？李永乐老师6分钟解释高维空间

http://www.youtube.com/watch?v=_8PYYnuoZP8

#+BEGIN_EXPORT HTML
频道中有字幕，看不到的请自己设置一下！</br>四维空间过一个点能做出四条相互垂直的直线，你能想象吗？</br>空间距离s=-√(x^2+y^2+z^2+m^2)</br>三体里的降维打击是什么？</br></br>这里都会告诉你！</br></br>这里是李永乐老师唯一Youtube频道</br></br>
#+END_EXPORT


*** 宇宙大爆炸是怎么回事？爱因斯坦一生中最大的错误又是什么？李永乐老师讲宇宙为什么是膨胀的（2018最新）

http://www.youtube.com/watch?v=o-E3_zxajmQ

#+BEGIN_EXPORT HTML
有同学问我</br>我们为什么要认为宇宙是从一次大爆炸开始的</br>科学家是如何得到这个结论的</br></br>为了说明这个问题 首先我们要从一个佯谬开始</br>称之为奥伯斯佯谬</br></br>所谓佯谬就指的是</br>和现实生活中的感觉完全相反的结论 叫佯谬</br>他说假如我们常规的宇宙是稳态的</br>就是宏观来看 这个宇宙是静止的 均匀的 并且是无限的</br>无限包含无限空间和无限时间</br>那么 你在夜晚的时候看天空</br>这个整个天空应该是明亮的</br>这就是奥伯斯佯谬</br></br>到底是谁第一个提出大爆炸呢</br>我们要说明这件事仍然是由广义相对论得到的</br>首先呢 爱因斯坦提出了广义相对论</br>广义相对论从一开始提出它的目的就是为了解释宇宙</br>但是很遗憾爱因斯坦最开始提出广义相对论的时候</br>认为宇宙还是静止不动的</br>所以他引入了一个叫做宇宙常数的东西来修正这个模型</br>他还是以静态模型来进行处理的</br>后来有一个俄罗斯科学家 名字叫亚历山大·弗里德曼</br>这个亚历山大他通过爱因斯坦的方程进行求解</br>发现 你如果认为宇宙不是静态的 而宇宙是一个膨胀的</br>那么你就不需要这个宇宙常数了 可以约掉</br>亚历山大这个结论比爱因斯坦更先进了一步</br>而爱因斯坦的确承认他自己错了</br>被称为自己一生中最大的一个错误 就是爱因斯坦认为的</br></br>
#+END_EXPORT


*** 霍金研究的黑洞到底是什么？李永乐老师6分钟带你了解奇妙的黑洞

http://www.youtube.com/watch?v=uK3_tg6qeiE

#+BEGIN_EXPORT HTML
李永乐老师唯一Youtube频道</br></br>
#+END_EXPORT


*** WIFI和微波炉加热食物会对人有害吗？致癌吗？李永乐老师讲微波炉原理

http://www.youtube.com/watch?v=4h-h2vYmMtg

#+BEGIN_EXPORT HTML
大家如果有想看的内容可能在评论区留言！</br></br>相关视频推荐：</br>——————————————————————————————————————</br>闪电是如何形成的？如何快速回避闪电？https://youtu.be/qyshX7qiG2I</br></br>火热视频推荐：</br>——————————————————————————————————————</br>老哥的一句“我先走了”，成了生命中最后一句话！https://youtu.be/Yn851GQBsWw</br>————————————————————————————————</br>宇宙中最大的数是啥？https://youtu.be/eSYN2UN3SXM</br>————————————————————————————————</br>支配宇宙的法则：什么是因果？https://youtu.be/0auDcESroEA</br></br>相对论视频推荐：</br>——————————————————————————————————————</br>光速为什么不能被超越？https://youtu.be/zY11529Uia0</br>————————————————————————————————</br>支配宇宙的法则：什么是因果？https://youtu.be/0auDcESroEA</br>————————————————————————————————</br>狭义相对论：时间膨胀是怎么回事？https://youtu.be/h6tbHSyVmfo</br></br>经济学视频推荐：</br>——————————————————————————————————————</br>你存银行的钱都去哪了？https://youtu.be/OTe3Bbcixow</br>————————————————————————————————</br>贷款 买房，利息怎么算？https://youtu.be/T6FBfNpiBYw</br>————————————————————————————————</br></br>值得深思的视频推荐：</br>——————————————————————————————————————</br>你真的看懂《皇帝的新装》了吗？https://youtu.be/b7NZfkqFc6k</br>————————————————————————————————</br>帝王为啥总要杀有功之臣？https://youtu.be/qXg1r_FwkvA</br>————————————————————————————————</br></br>
#+END_EXPORT


*** 第三次数学危机是什么？这次数学家都弄疯了！（2018最新）

http://www.youtube.com/watch?v=GWTVAYQytJ8

#+BEGIN_EXPORT HTML
第三次数学危机是咋回事？李永乐老师带你了解刮胡子的理发师悖论。数学家罗素对康托尔的诘难！</br>集合理论永久的瑕疵，现在人们还没有完美解决</br>这里是李永乐老师唯一Youtube频道</br></br>
#+END_EXPORT


*** 光速为什么不能被超越？李永乐老师老师6分钟讲狭义相对论之质量增加（2018最新）

http://www.youtube.com/watch?v=zY11529Uia0

#+BEGIN_EXPORT HTML
狭义相对论：时间膨胀是怎么回事？如何实现星际旅行？</br>https://youtu.be/h6tbHSyVmfo</br>————————————————————————————————</br>狭义相对论：运动的物体长度为啥会变短？</br>https://youtu.be/Zr0hpemgOuQ</br>————————————————————————————————</br>今天我们继续来讨论相对论的话题</br>有人问我说为什么宇宙中光速是最快的速度</br>为什么一个物体不能够通过加速的方式加到光速</br>我们今天就来解释一下这个问题</br>首先为了解释这件事 我们得先明白加速是怎么来的</br></br>物体的加速过程到底是怎么回事</br></br>牛顿第二定律又是什么</br></br>为什么在相对论的情况下物体无法超过光速</br>在相对论的情况下</br>爱因斯坦的相对论有一个结论</br>就是物体的质量会随着它的速度而发生变化</br>物体质量等于m0/√(1-(v/c)^2)</br></br>
#+END_EXPORT


*** 宇宙中最大的数是啥？居然能让人脑变黑洞？李永乐老师讲葛立恒数（2018最新）

http://www.youtube.com/watch?v=eSYN2UN3SXM

#+BEGIN_EXPORT HTML
历史上的三次数学危机</br>——————————————————————————————————</br>第一次数学危机是什么？https://youtu.be/nAOVQEcqjSM</br>————————————————————————————————</br>第二次数学危机是什么？https://youtu.be/S5z7xYfGNXs</br>————————————————————————————————</br>第三次数学危机是什么？https://youtu.be/GWTVAYQytJ8</br></br>经济学视频推荐：</br>——————————————————————————————————————</br>你存银行的钱都去哪了？https://youtu.be/OTe3Bbcixow</br>————————————————————————————————</br>贷款 买房，利息怎么算？https://youtu.be/T6FBfNpiBYw</br>————————————————————————————————</br></br>值得深思的视频推荐：</br>——————————————————————————————————————</br>你真的看懂《皇帝的新装》了吗？https://youtu.be/b7NZfkqFc6k</br>————————————————————————————————</br>帝王为啥总要杀有功之臣？https://youtu.be/qXg1r_FwkvA</br>————————————————————————————————</br></br>有想看的内容可能在下面留言！</br></br>
#+END_EXPORT


*** 不能赚钱的股票就要割肉；不能爱的人就要分手；不会做的题就要跳过；李永乐老师讲经济学原理沉没成本（2018最新）

http://www.youtube.com/watch?v=IUDIz1WwBXg

#+BEGIN_EXPORT HTML
有同学问我 说万一他在考场上遇到了一道题</br>他做了半天发现还是不会做</br>这个时候它是应该继续做下去</br>还是应该果断放弃</br>今天我们来讨论一下这个问题</br></br>
#+END_EXPORT


*** 数学家曾经围攻的问题，至今未解决之世界近代三大数学难题之一哥德巴赫猜想（2018）

http://www.youtube.com/watch?v=XkVskCFA8r8

#+BEGIN_EXPORT HTML
1+1到底什么意思；哥德巴赫猜想又是什么；偶数都可以分解成两个质数的和；陈景润解决的1+2是什么；这里全都告诉你</br>这里是李永乐老师唯一Youtube频道</br></br>
#+END_EXPORT


*** 你真的看懂《皇帝的新装》了吗？心知肚明和说出来有啥区别？李永乐老师讲“呐喊”的力量（2018最新）

http://www.youtube.com/watch?v=b7NZfkqFc6k

#+BEGIN_EXPORT HTML
有小朋友学习了《皇帝的新装》这篇课文，他问我明明大家都知道皇帝没有穿衣服，为什么小孩喊出这句话却造成了这么大的影响呢</br>这是因为:“大家都知道”和“大家知道大家都知道”是不一样的</br>在这个视频中，我通过一个经典逻辑问题:红眼睛和蓝眼睛来带大家了解一下共有知识和公共知识的区别</br>在社会中，有许多大家彼此心知肚明的事情，就是共有知识</br>而经过讨论之后，共有知识才能变成公共知识</br>比如一只垃圾股票，大家都知道它是垃圾</br>但是大家不知道别人是不是知道它是垃圾，所以股票的价格可能还会很高</br>一旦大家都清楚大家都知道这个股票是没有价值的，那么就不会有人再买它，它的价格就会一下子跌下来</br>这个过程很可能是一个事件一篇报道等，这就是呐喊的力量</br></br>
#+END_EXPORT


*** “相互保”是骗局吗？保费会比普通保险贵吗？李永乐老师讲大数定律（2018最新）

http://www.youtube.com/watch?v=x3yToesPtzo

#+BEGIN_EXPORT HTML
最近支付宝上线了一种新型保险：相互保</br>相互保的特点是:</br>加入免费</br>一旦有参保人员生大病</br>则获得一定救助由其他参保人员平摊费用</br>短短几天时间，相互保吸引了近千万人加入</br></br>根据伯努利大数定律</br>在一个相当大的群体中</br>生病的人数比例几乎是固定的</br>只要参保人数足够多，相互保的保费不会大规模的波动</br>相比于传统保险，相互保保费相对较低，赔付率较高</br>而且具有去中心化的特点，更容易为大众接受</br> 相互保的具体原理是什么？</br>保费是如何计算出来的？</br>点开视频看看吧！</br></br>
#+END_EXPORT




** 博弈论
https://www.youtube.com/playlist?list=PLOrDt87s8A3qxPWhuKINN0I3ftdTcpjPm



https://i.ytimg.com/vi/g-wCpEZBEdw/sddefault.jpg


*** 看懂了这个，你再去炒股；股市暴跌，为啥散户炒股票总赔钱？李永乐老师用数学告诉你！（2018最新）

http://www.youtube.com/watch?v=g-wCpEZBEdw

#+BEGIN_EXPORT HTML
今天中国的股市又暴跌了一下</br>这么多年以来，无论国际形势如何变化</br>中国的股民总是不忘初心，为祖国提供流动性</br>关于炒股赔钱这件事，每个人都有不同的想法</br></br>有的人想可能是我智商不够</br>也有人想可能我运气不好，总是踩不上点</br>但是大家会发现大部分股民都是赔钱的</br>那么这里有没有什么深刻的数学内涵？</br></br></br>美女与男人的游戏，数学模型中.....</br>男人和女人代表了什么</br>女人就像股市里的庄家一样，她可以拉升股价也可以打压股价</br>而男人就像我们散户一样</br>他可以买多，也可以买空，融券买空，对吧</br>如果庄家拉升股价而我们做多，我就会有很高的收益</br>如果庄家打压股价，我们做空我们也会有收益</br>但是如果庄家拉升股价，我们去做空我们就输了</br>如果庄家要是打压股价我们又做多，我们也输了</br>表面上看好像有涨有跌我们是可以赚到钱的</br>赚不到钱是你运气不好</br>但是庄家总是可以通过一定的策略让你一直赚不到钱</br></br>————————————————————————</br>第一个建议就是把自己的心态调整好</br>把自己的钱和时间用在更有意义的事情上</br>第二个建议，如果你一定要买股票的话</br>那么请你买那些基本面良好有发展前景的股票</br>而不要去买这些题材股，因为在题材股上有很多的庄家</br>它会通过一定的策略让你一直输钱 </br></br>这里是李永乐老师唯一Youtube频道</br></br>
#+END_EXPORT


*** 帝王为啥总要杀有功之臣？美国为啥要对中国搞贸易战？李永乐老师用数学带你看清现实（2018最新）

http://www.youtube.com/watch?v=qXg1r_FwkvA

#+BEGIN_EXPORT HTML
中间最好是暂停下来思考一下</br></br>三姬分金</br>————————————————————</br>A B C 三人分100金币</br></br>规则：</br>A B C，依次提议分金币的方案</br>若提议未获半数以上通过，提议人处死；</br>处死之后呢，剩下那两个人，第二个人接着提</br>那如果要是通过了，获得半数以上通过，不包括半数</br>那么这个就按这个规则来分金币</br></br>假设：</br>三人都是聪明的，理性的</br>并且是人性本恶的</br>————————————————————————————————</br></br>以上规则，如果是四个人来提呢？情形会发生什么</br>老板意谓着是什么</br>低端人群意谓着什么</br>如果打破你的阶级固化</br>你是否需要与人共谋</br>老板为什么能赚最多</br></br></br>国家之间的关系也是一样</br>例如美国作为世界老大，总是联合一些三四流国家整老二</br>当年的苏联是老二，他通过意识形态把苏联搞散了</br>后来的日本是老二，广场协定把日本搞残了</br>后来俄罗斯越来越厉害，通过石油把俄罗斯搞废了</br>现在中国是老二，美国又通过贸易战开始搞中国</br>因为他担心，老二总想取代自己的位置。</br></br>李永乐老师带你分析以上数学模型，并给出此数学模型所代表的现实意义</br></br>
#+END_EXPORT


*** 人们为啥总闯红灯？小企业开拓市场咋这么难？囚徒困境又是什么？李永乐老师讲解纳什均衡理论（2018最新）

http://www.youtube.com/watch?v=Upd1ESkn-Bo

#+BEGIN_EXPORT HTML
博弈论里面不得不提的一个人物就是约翰纳什</br>他提出了著名的理论，纳什均衡理论</br>纳什均衡中最著名的一个例子就是囚徒困境</br></br>纳什均衡还有一个很有意思的例子叫智猪博弈</br>智猪博弈实际上和大企业与小企业的关系比较像</br>A好像是大企业，这个大企业他可以开拓市场</br>同时他也可以在市场中获得更大的收益</br>B就是小企业，小企业也可以开拓市场</br>同时也可以从市场中获得收益</br>那么对于小企业来讲，它的最优策略是什么？</br>是等待，等待着什么时候，等待着把大企业把市场开拓好了</br>他直接上车，他如果非要自己去开拓市场的话</br>那么如果大企业也开始了，你的收益就是很少的</br></br>
#+END_EXPORT


*** 科学很美——博弈论总结篇，李永乐老师海绵演讲（2018最新）

http://www.youtube.com/watch?v=BUn88WTmcOU

#+BEGIN_EXPORT HTML
三姬分金视频：https://www.youtube.com/watch?v=qXg1r_FwkvA</br>纳什均衡视频：https://www.youtube.com/watch?v=Upd1ESkn-Bo</br>股票博弈视频：https://www.youtube.com/watch?v=g-wCpEZBEdw</br></br>
#+END_EXPORT


*** 博弈论：赤壁之战关羽为啥在华容道放走曹操？李永乐老师讲三足鼎立（2018最新）

http://www.youtube.com/watch?v=i-4F4mCxAUY

#+BEGIN_EXPORT HTML
热门视频推荐：</br></br>疫苗到底有啥用？https://youtu.be/Sxl_zoy1HoQ</br>——————————————————————————————————————</br>你真的看懂《皇帝的新装》了吗？https://youtu.be/b7NZfkqFc6k</br>——————————————————————————————————————</br>帝王为啥总要杀有功之臣？https://youtu.be/qXg1r_FwkvA</br>——————————————————————————————————————</br></br>有同学在玩三国游戏时发现了一些令人费解的现象：</br>同盟之间前一刻可以像孙权刘备在赤壁联手对抗曹操</br>后一刻却像关羽在华容道故意放走曹操</br>明明消灭强敌的机会尽在咫尺，为何盟友会轻易放弃？</br>其实，游戏世界也像三国乱世一样充满了博弈，输赢并非如此简单</br>在这个视频中，我会通过建立一个三方博弈的模型</br>揭示赤壁之战孙刘联盟的原因和战后诸葛亮派关羽守华容道</br>故意放走曹操的原因</br>点开视频看看吧!</br></br>
#+END_EXPORT


*** 为啥家长“喜欢”对孩子进行超前教育？李永乐老师讲博弈论之旅行者困境（2018最新）

http://www.youtube.com/watch?v=Pqv6mcC7i5s

#+BEGIN_EXPORT HTML
你真的看懂《皇帝的新装》了吗？https://youtu.be/b7NZfkqFc6k</br>————————————————————————————</br>帝王为啥总要杀有功之臣？https://youtu.be/qXg1r_FwkvA</br>————————————————————————————</br></br>许多家长对孩子的学习非常焦虑</br>总觉得不能输在起跑线上，让孩子提前学习各种知识</br>参加各种补习班，造成孩子、家长都非常累</br>为什么会出现这种情况昵？</br>其实，许多家长并非真想让孩子承受这么大压力</br>只是看到其他孩子都学了，自己不学就落后了</br>所以硬着头皮也要上</br>其实，这并不符合教育规律</br>在经济学上有一个模型旅行者困境</br>讲的就是这样一个问题</br>点开视频看看这种心理如何从博弈论进行解释吧!</br></br>
#+END_EXPORT




** 贸易战
https://www.youtube.com/playlist?list=PLOrDt87s8A3pEWNkq-tkJ6GEphl3yJ6so



https://i.ytimg.com/vi/7MFly82e46Q/sddefault.jpg


*** 中兴禁令之芯片为什么这么难做？芯片的基本原理是什么？李永乐老师带你了解！（2018最新）

http://www.youtube.com/watch?v=7MFly82e46Q

#+BEGIN_EXPORT HTML
——————————以下网址是intel的芯片生产视频——————</br>https://www.youtube.com/watch?v=d9SWNLZvA8g&t=9s</br>4月16号美国政府宣布对中兴公司禁令</br>禁止任何美国公司向中兴公司销售电子技术或通讯元件，长达七年</br>为什么这个禁令对中兴公司乃至中国影响这么巨大？</br>芯片到底是什么？</br>我们中国的芯片产业到底发展到一个什么程度？</br></br>芯片实际上是一片载有集成电路的一个元件</br>第一类叫做功能芯片</br>第二种叫存储芯片</br>芯片的生产过程及惨杂的硼和磷元素是为什么</br></br>这里都有答案</br></br>
#+END_EXPORT


*** 帝王为啥总要杀有功之臣？美国为啥要对中国搞贸易战？李永乐老师用数学带你看清现实（2018最新）

http://www.youtube.com/watch?v=qXg1r_FwkvA

#+BEGIN_EXPORT HTML
中间最好是暂停下来思考一下</br></br>三姬分金</br>————————————————————</br>A B C 三人分100金币</br></br>规则：</br>A B C，依次提议分金币的方案</br>若提议未获半数以上通过，提议人处死；</br>处死之后呢，剩下那两个人，第二个人接着提</br>那如果要是通过了，获得半数以上通过，不包括半数</br>那么这个就按这个规则来分金币</br></br>假设：</br>三人都是聪明的，理性的</br>并且是人性本恶的</br>————————————————————————————————</br></br>以上规则，如果是四个人来提呢？情形会发生什么</br>老板意谓着是什么</br>低端人群意谓着什么</br>如果打破你的阶级固化</br>你是否需要与人共谋</br>老板为什么能赚最多</br></br></br>国家之间的关系也是一样</br>例如美国作为世界老大，总是联合一些三四流国家整老二</br>当年的苏联是老二，他通过意识形态把苏联搞散了</br>后来的日本是老二，广场协定把日本搞残了</br>后来俄罗斯越来越厉害，通过石油把俄罗斯搞废了</br>现在中国是老二，美国又通过贸易战开始搞中国</br>因为他担心，老二总想取代自己的位置。</br></br>李永乐老师带你分析以上数学模型，并给出此数学模型所代表的现实意义</br></br>
#+END_EXPORT


*** 从比较优势理论分析：中美为何会爆发贸易战？与鸦片战争有什么相似之处？李永乐老师告诉你

http://www.youtube.com/watch?v=nwLqo83iqks

#+BEGIN_EXPORT HTML
最近中美贸易战愈演愈烈 从最开始双方进行反倾销调查</br>到后来互加关税 再到现在美国直接对中国的个别企业进行制裁</br>甚至演变成外交风波</br>有小朋友就问我说 为什么中美之间会爆发这样一场贸易战</br>很显然这个问题是非常复杂的</br>那今天我们想从一个侧面贸易的角度来理解一下这个问题</br></br>视频中包含以下知识点：</br>1、什么是绝对优势？</br>2、什么是比较优势？</br>3、中英为什么会爆发鸦片战争？</br>4、中美为什么会爆发贸易战？</br>详见视频！</br></br>火热视频推荐：</br>基因编辑是啥？CRISPR/cas9技术如何修改DNA？https://youtu.be/o1MdiW5UZh0</br>为什么久赌必输？https://youtu.be/AadaEc6pJpw</br>输了钱就加倍下注，能回本吗？https://youtu.be/yoOocF47BRI</br>贷款/买房，利息怎么算？https://youtu.be/T6FBfNpiBYw</br></br>
#+END_EXPORT




** 生活
https://www.youtube.com/playlist?list=PLOrDt87s8A3rMMqrz_Sz2kSt4lzWiPg4h



https://i.ytimg.com/vi/Xw_Nb_dyi3A/sddefault.jpg


*** 雨中走路淋雨多还是跑步淋雨多？李永乐老师8分钟给你讲明白

http://www.youtube.com/watch?v=Xw_Nb_dyi3A

#+BEGIN_EXPORT HTML
这里是李永乐老师唯一Youtube频道</br></br>
#+END_EXPORT


*** 清明节为什么总是下雨？这可是自然规律！

http://www.youtube.com/watch?v=SQs4XalAVkE

#+BEGIN_EXPORT HTML
【清明时节雨纷纷】这句话，绝不仅仅源于文化传承，而是实实在在的自然规律</br>这里是李永乐老师唯一Youtube视频！</br></br>
#+END_EXPORT


*** 海市蜃楼的原理是什么？十个人有十人不懂；让李永乐老师带你了解其中的秘密

http://www.youtube.com/watch?v=4JWNdtXcT48

#+BEGIN_EXPORT HTML
光在不同介质中传播的速度不同</br>折射和全反射现象是什么</br>海市蜃楼</br>沙市蜃楼</br>它们的不同地方在哪？</br>这里都会告诉你</br></br>李永乐老师唯一Youtube频道</br></br>
#+END_EXPORT


*** 彩虹大家都见过，可你见过霓吗？李永乐老师为你讲述霓虹间的区别

http://www.youtube.com/watch?v=QQSUhBMJtN8

#+BEGIN_EXPORT HTML
李永乐老师唯一Youtube频道</br></br>
#+END_EXPORT


*** 手机触摸屏原理是什么？手机贴膜到底有没有影响？李永乐老师全都告诉你（2018最新）

http://www.youtube.com/watch?v=_eETsYymEZo

#+BEGIN_EXPORT HTML
什么是交流；什么是直流电；手机电容屏是怎么定位的；220V家用电怎么测最好；电容的交直流电充放电原理；为什么手机贴了膜还能用？这里都会告诉你！</br>这里是李永乐老师唯一Youtube频道，喜欢的朋友可以订阅，几乎每天频道都有更新</br></br>
#+END_EXPORT


*** 电磁波有哪几类，在生活中怎么应用的？被伽玛射线照了会怎么样，李永乐老师8分钟告诉你（2018最新）

http://www.youtube.com/watch?v=SA1C4ehtBb8

#+BEGIN_EXPORT HTML
视频有字幕，看不到的请自己设置一下！</br>那么电磁波究竟是什么？它有哪些种类？</br>波长最小的频率最大，波长最大的频率最小</br>波长最短的叫做γ射线</br>波长比γ射线更长一点的电磁波叫X射线</br>波长比X射线更长的叫光，光又可以分为三个区域</br>波长比较短的紫外，波长适中的可见和波长比较长的红外</br>比光波长更长的就叫无线电</br></br>其中一定要避免接触这种γ放射源</br>世界上第一张X光片是伦琴照的</br></br></br>这里是李永乐老师唯一Youtube频道！</br></br>
#+END_EXPORT


*** 电磁炉对人的危害有多大？电磁炉的原理是什么？李永乐老师告诉你（2018最新）

http://www.youtube.com/watch?v=NLvdi3tW3fw

#+BEGIN_EXPORT HTML
了解电磁炉的原理，首先必须得明白一个道理，叫电磁感应现象</br></br>变化的磁场上面就会产生一个与磁场垂直的电场，电场是一圈一圈，我们称之为涡旋电场，如果电场中有闭合回路中产生电流</br></br>金属探测器的原理也是一样的</br></br>这里是李永乐老师唯一Youtube频道</br></br>
#+END_EXPORT


*** 电脑显示器为啥能显示这么多种颜色？RGB颜色代码啥意思？李永乐老师5分钟讲三原色（2018最新）

http://www.youtube.com/watch?v=7JGIcnI_C5c

#+BEGIN_EXPORT HTML
红绿蓝三种颜色按照不同的比例配比可以得到许多种颜色</br>所以这种模式我们就叫它RGB模式</br>RGB其实就表示的是</br>红，RED</br>绿，GREED</br>蓝色，BLUE</br></br>这三个颜色我们称它为三元色 </br></br>电脑显示屏或者计算机显示屏或者是电视显示器</br>基本靠这种方式来产生各种颜色的</br></br>颜色代码是全都是零的意思是红绿蓝全都不给，就是黑色</br>如果全都是FFFFFF就是红绿蓝满的，就是白色</br>这个就是RGB模式的由来</br></br>
#+END_EXPORT


*** 手机定位和导航是啥原理？GPS和北斗有啥区别？李永乐老师讲卫星定位（2018最新）

http://www.youtube.com/watch?v=Rhq18MV6LtU

#+BEGIN_EXPORT HTML
现在世界上用得最多的是美国的卫星定位系统</br>也就是全球卫星定位系统GPS</br>这是美国在上世纪70年代开始由军队主导的一个项目</br>那么现在中国也开始研究卫星定位系统</br>我们已经逐渐的开始布置北斗卫星导航系统</br>除了中国和美国以外</br>你像欧盟还有俄罗斯，他们也有卫星定位系统</br>那么，不同国家的卫星定位系统基本原理都是一样的</br>那么它们提供的服务都是这么几个</br>一个叫授时，就告诉你的时间是什么</br>一个叫定位，告诉你你的位置是什么</br>一个是导航，告诉你前面可能会有拥堵，路怎么走这些功能，是吧！</br></br>修正误差实际上是卫星定位最大的障碍</br>比如说现在比较常见的一种方法，我们称为差分定位的方法</br>差分定位，什么叫差分定位？ </br>就是说，你想知道这个人的空间坐标和时间坐标</br>我旁边有一个非常精密的基站</br>这个基站上面有一个高精密的定位仪器</br>不光你和卫星联络，同时这个基站它也和这四颗卫星联动</br>那么因为基站的数据比较准确，所以它就可以通过跟这些卫星联络</br>知道到你这个位置的时候大概会有多少误差</br>因为你和基站离得比较近，比如说几十公里或者一百公里以内</br>这个时候它就可以把误差作用在你的手机上对你进行修正</br>这样一来你的效果就会比较好</br></br></br>比如我们现在一般的卫星定位都要求定位精度在十米范围以内的</br>我们大部分的时候是采用这种差分定位的方法进行修正</br>现在我们大部分的定位系统还是采用美国的GPS</br>比如我们的手机一般是这样的</br>但是随着我们的导航系统，北斗导航越来越先进之后</br>我们以后得很多定位设备都会采用我们国产的北斗导航系统</br></br>
#+END_EXPORT


*** 银行密码系统安全吗？质数（素数）到底有啥用？李永乐老师11分钟讲RSA加密算法（2018最新）

http://www.youtube.com/watch?v=D_kMadCtKp8

#+BEGIN_EXPORT HTML
人们花这么大力气去研究这些数学问题有什么意义</br>今天我就给大家来说一下数学的意义</br>比如说我们去银行存钱取钱 用到密码</br>那么密码就是基于数学的</br></br>有一种加密算法叫对称加密</br>对称加密是以前比较常见的一种加密方式</br>另一种最典型的非对称加密方式</br>叫做RSA加密算法 </br></br>RSA加密算法</br>是在1978年的时候 麻省理工MIT有三位数学教授</br>他们一起发明了这种算法</br>这种算法 三个人的名字分别叫R S和A打头</br>所以就叫RSA算法</br>RSA加密算法的原理在视频可以了解</br></br>有没有什么方式可以比较快的计算大数的质因数分解</br>有 那就是量子计算机</br>普通计算机算十年大数的质因数分解 它可能算一个星期就算出来了</br>那如果这样的话 这个我们的银行系统什么的可能都要更新</br>否则就没有办法保证安全</br>我们现在也知道每隔一段时间我们银行的系统都需要更新一次的</br>我们的数字证书都是要重新更新 否则就不能用了 这是为什么</br>因为我们要不停的更换我们算法和密钥以保证我们的安全性</br></br>
#+END_EXPORT


*** 别以为啥都是UFO！华北多地天空不明飞行物是什么情况？李永乐老师带你破局（2018最新）

http://www.youtube.com/watch?v=35qKiTgXD60

#+BEGIN_EXPORT HTML
前两天在北京山西等大片的华北地区</br>人们在晚上都看到了这样的一幕</br>有一个发光的云彩在那盘旋着上升</br>人们不知道是什么东西</br>还有人说这就是UFO</br>专家们给出了解释 说这实际上是一种航天器的现象</br></br>其实是航天器产生了一种叫做航线云（航迹云，飞机云）的东西</br>视频中会充分解释这种现象</br></br>另外，视频中还解释了夜光云，音障和音爆现象是怎么产生的</br>马赫锥又是什么</br>——————————————————————————————————————</br></br>看完以上视频，就别以为啥都是UFO了，老铁们</br></br>其实很多生活中的现象是可以使用科学进行解释的</br></br>
#+END_EXPORT


*** 天天在家用电，可是你知道电是怎么发出来的吗？李永乐老师讲科学巨匠法拉第的事迹，学着点（2018最新）

http://www.youtube.com/watch?v=hBIJXVsuXOs

#+BEGIN_EXPORT HTML
我们都知道家用电是有发电厂发出来的</br>但是发电厂为什么就可以发电</br></br>为了解释这个问题</br>我们首先必须从一个人物 法拉第说起</br>法拉第是英国的物理学家</br>在最开始的时候 人们认为电和磁是两个完全不同的现象</br>但是丹麦物理学家奥斯特发现电流可以产生磁场</br>于是法拉第又想 那么既然电流可以产生磁场</br>磁场能不能够产生电流</br></br></br>通过四年的实验法拉第终于发明了发电机</br></br>法拉第制作了最早的发电机之后 有人就问</br>英国的一个财务大臣就问他 说你这个东西有什么用</br>法拉第当时对英国财务大臣说</br>也许你很快就可以对它进行收税了</br>果然后来人们用电用的越来越多</br>从此之后就收了很多钱用做电费</br></br></br>我们的家用交流电是220V 50Hz</br>220V 50Hz交流电是什么意思</br>就是说 这个电压随着时间是一直在变化的</br>而且是正弦形式变化的 一个周期是0.02s，</br>所以一秒内有50个周期 这就叫50Hz</br>220V叫有效值</br>而电压的峰值并不是220V 峰值是220V×√2 大约是311V</br></br>
#+END_EXPORT


*** 无线电报是什么原理？李永乐老师带你了解什么是无线电报和摩尔斯电码！（2018最新）

http://www.youtube.com/watch?v=iKvDAwj4FXg

#+BEGIN_EXPORT HTML
为了说明电报</br>首先我们还是要从麦克斯韦说起</br>法拉第发现了电磁感应现象</br>但是他难以用数学去解释自己的观点</br></br>麦克斯韦预言了电磁波的存在</br>但是他没有亲手证实这件事就去世了</br></br>而证实麦克斯韦理论的人</br>是德国科学家海因里希·鲁道夫·赫兹</br></br></br>无线电报的发明者说起来比较乱</br>至少有三个人</br>第一个人就是咱们所熟知的尼古拉特斯拉</br>另外一个人是意大利人马可尼</br>还有一个人是俄国科学家波波夫</br></br>最开始使用无线电报的时候传输能力很有限</br>所以说人们必须把信号进行编码</br>而摩尔斯电码就是把A到Z这26个字母还有0到9这十个数字等符号</br>变成短的电磁脉和长的电磁脉冲进行编码</br></br>而摩尔斯电码中SOS本身没有任何含义</br>它只是因为在摩尔斯代码中</br>它的表式方法非常简单</br></br>摩尔斯代码现在用处很少</br>很多无线电爱好者喜欢用这种代码进行沟通</br></br>
#+END_EXPORT


*** FM和AM是啥意思？收音机是咋收到音乐的？李永乐老师讲广播信号传输（2018最新）

http://www.youtube.com/watch?v=ckAflJSt5-4

#+BEGIN_EXPORT HTML
如果想把一个信号发射出去</br>这个信号必须是高频信号</br>低频信号传不远</br>而 我们的声音也好 图像也好</br>往往都是低频信号</br>我们必须首先把它变成高频信号</br>那么这个过程就称之为调制</br></br>我们把它变成一个高频信号的振幅随着低频信号的变化而变化</br>这种信号就称之为调幅信号</br>调幅信号或者叫AM</br></br>如果我让高频信号的频率随着低频信号的变化而变化</br>那这种就叫调频</br>那就是FM</br></br>信号的传播方式</br>一共有三种</br>天波</br>地波</br>直线波</br></br>另外视频中还讲解了解调的基本原理，请大家慢慢体会</br>以上原理对于手机也是通用的</br></br>
#+END_EXPORT


*** 1080P什么意思？电视与电影原理相同吗？李永乐老师讲解电视成像原理（2018最新）

http://www.youtube.com/watch?v=Sq6LE1OKuPU

#+BEGIN_EXPORT HTML
有的时候在电视里边看到电影屏幕</br>电影屏幕一直在闪</br>因为电影是胶片记录影像数据的，它的胶片是每秒24个格</br>在传统的电视来讲 比如我们的PAL是的传统电视，它是每秒25帧的</br></br>你用每秒拍摄25张的电视摄像机</br>去拍摄每秒放映24张的电影画面</br>你就会发现它以每秒钟一次的频率在闪</br>这就是为什么电视里面经常会看到屏幕在不停的闪的原理</br></br>所谓1080P的意思</br>就是画面一共有1080行1920列</br>1920×1080这种 叫1080制式</br>那么P又是什么意思</br>这就涉及到两种不同扫描方式</br>第一种方式叫做隔行扫描，也称为I</br>第一种方式叫做逐行扫描，也称为P</br></br>视频中还讲解了PAL与NTSC两种不同制式的区别</br>详细请在视频中观看</br></br>
#+END_EXPORT


*** 植物中隐藏的数学—— 斐波那契数列是什么？李永乐老师讲神奇的斐波那契数列（2018最新）

http://www.youtube.com/watch?v=VCJsUYeuqaY

#+BEGIN_EXPORT HTML
在1202年的时候 有一个人名字叫斐波那契</br>这个斐波那契他是一个意大利人</br>这个人他写了一本书 名字叫算盘书</br>里面介绍了一些数学问题</br>在这本书里面它提出的一个著名的叫兔子数列的问题</br>兔子数列 那么兔子数列被称为斐波那契数列</br></br>在800年前提出的理论 上个世纪的时候突然就火了</br>因为人们发现现实生活中有很多东西跟斐波那契数列是很像的</br>人们发现生活中很多东西都具有斐波那契的性质</br>举个例子 比如说花瓣、树枝和向日葵等植物的生长特性</br></br>那么为什么自然界总是存在着斐波那契数规律来生长呢</br>开始人们并没有深刻的认识</br>后来人们才逐渐发现了</br>原来这样的一个排布可以使得种子它的堆积效率最高</br>所以自然界在进化过程中自然而然形成了这种效果</br></br>如果把斐波那契数做比</br>它总是往一个数靠近</br>其实就是0.618……</br>黄金分割</br></br>
#+END_EXPORT


*** 黄金分割是什么？如何拍摄出美丽的照片？李永乐老师带你了解黄金比例的美（2018最新）

http://www.youtube.com/watch?v=kKP08ozDjus

#+BEGIN_EXPORT HTML
斐波那契数列两个数之比会越来越接近黄金分割</br>那么黄金分割到底是什么呢</br></br>黄金分割相传最早是由古希腊的数学家毕达哥拉斯发现的</br>说达格拉斯 有一次在街上走</br>发现有一个铁匠敲打这个铁锤的声音特别有节奏特别美</br>结果他回去一研究发现 和原来敲击的频率有一个关系</br>于是他就提出了一个比例</br>这个比例就被人称之为黄金分割</br></br>黄金比例应该等于(-1+√5)/2</br>黄金分割被人们认为是非常美的</br></br>比如说断臂的维纳斯</br>比如说舞蹈演员穿高跟鞋</br>比如说金字塔</br>比如说东方明珠</br></br>所谓黄金矩形是指有这么一个矩形</br>这个矩形它的宽大概是0.618 而这个长大概是1</br>也就是说宽和长之比是黄金比例</br>在黄金矩形里就可以作出黄金曲线或者黄金螺旋</br></br>蒙娜丽莎在她的这幅画里边也大量运用了黄金螺旋和黄金分割</br></br>同时我们在学习绘画学习摄影过程中可能也会用到黄金分割点</br>摄影有九宫格的这种说法</br>而学会运用九宫格</br>你的摄影和拍照技术将有大大提高</br></br>
#+END_EXPORT


*** 马化腾和张一鸣等IT大佬们如果相互怼对方，有多少种方法？李永乐老师讲欧拉错装信封问题

http://www.youtube.com/watch?v=kENgV809i_Q

#+BEGIN_EXPORT HTML
今日头条的张一鸣和腾讯的马化腾两个人又怼起来了</br>在互联网圈互相怼不是什么新鲜事</br>360就跟QQ怼过 微信又跟支付宝怼过</br>那么假如有一天这些互联网大佬们坐在一块</br>研究说咱们每个人都怼一个人 请问有多少种方法</br>今天我们来研究一下这个问题</br></br>马云 马化腾 彦宏 刘强东 张一鸣 张一鸣</br>以上五个大佬互相怼对方的方法</br>根据视频内容可知</br>a5=4×(a3+a4)=44</br>四十四种方法</br>其实这个问题本质上叫做欧拉错装信封问题</br>它最早是伯努利和欧拉两个人研究的</br>它表示的是说 有一个人写了一百封信</br>这一百封信装到一百个信封里 但是每一封信都装错了</br>有多少种方法</br></br>就是和大佬们互相怼是一个意思</br></br>
#+END_EXPORT


*** 近视眼是怎么回事？眼镜度数又是什么意思？李永乐老师带你了解近视矫正（2018最新）

http://www.youtube.com/watch?v=ao327z6B60E

#+BEGIN_EXPORT HTML
凸透镜就是一个中间厚两边薄的一个透镜</br>凹透镜跟凸透镜相反 它是中间薄两边厚的透镜</br>它们都有一个固定的焦距</br></br>但是眼睛的焦距是可以自动调节的</br>因此眼睛相当于一个自动变焦的这么一个物体</br>焦距要改变的方法就是让人的睫状肌这个肌肉收缩</br></br>那么近视眼到底是怎么回事</br>近视眼就是假如有一个小朋友天天玩游戏机</br>他的晶状体一直都是在看近处的物体</br>所以他的肌肉一直都是紧张的</br>时间长了他的肌肉紧张到不能够放松了</br>所以呢 所以当他看远处物体的时候焦距依然比较小</br></br>这个就是近视眼 </br>近视眼的特点就是看远处的物体看不清</br>而是成像在视网膜前 那么视网膜上成像了一个光斑</br>所以就看不清楚</br>近视眼说来也不完全都是由于玩游戏机造成的</br>近视眼又可以主要分为两类</br>第一类就是先天遗传</br>还有一种近视眼叫做假性近视</br></br>近视眼的矫正 有两种方法</br>第一种方法就是佩戴眼镜</br>第二种方法就是手术</br></br>
#+END_EXPORT


*** 坐飞机什么时候最危险？当飞机撞上鸟会怎么样？李永乐老师讲解航空事故的主要原因（2018最新）

http://www.youtube.com/watch?v=waQ49sMU4gg

#+BEGIN_EXPORT HTML
我们知道在5月14号的时候</br>四川航空的一架飞机在飞行过程中</br>前挡风玻璃突然就脱落了</br>在机组人员的共同努力下</br>这架飞机安全的降落在成都的机场</br>机上所有人员平安无事</br>那么这个事故的原因到目前还在调查当中</br>飞机在飞行过程中可能会面临哪些问题呢</br>我们如何去解决这些飞行中的潜在危险呢</br>这次的视频给大家讲解一下</br></br>当飞机撞上鸟之后</br>相当于20吨的物体重力的一个物体撞到飞机上</br>这个数非常大</br>那这么大的力 加在这个飞机前挡风玻璃上</br>可能会把飞机前挡风玻璃撞碎</br>如果撞在机翼上 可能会把机翼撞折</br>如果撞在螺旋桨上  螺旋桨肯定就坏掉了</br></br>飞机除了撞鸟比较危险之外</br>第二个比较危险的就是碰到气流</br>第三个比较危险就是 人为因素</br></br>有人称这个四川航空机组就是中国版的萨利机长 </br>这个萨利机长又是怎么回事</br></br>历史上最大的空难又是发生在哪里呢</br>历史上最大的空难又是怎么引起的呢</br></br>李永乐老师给你一一道来</br></br>
#+END_EXPORT


*** 如何选择一个节能省电的空调？空调的原理又是什么？李永乐老师9分钟讲解热机原理和卡诺定理（2018最新）

http://www.youtube.com/watch?v=Wf0VRMiXD_4

#+BEGIN_EXPORT HTML
现在天气热起来了</br>许多家庭都把空调打开了</br>有一些人 可能要买新的空调</br>那么这就涉及到一个问题</br>空调的能效比到底是什么意思</br>一级 二级 三级 空调到底有什么区别呢</br></br>今天的视频我们就来讨论一下这个问题</br></br>视频中讲解了机热是什么</br>卡诺定理又是怎么一回事</br></br></br>能效比η</br>如果要是大于3.6 就叫一级空调</br>它是比较节能的</br>如果η大于3.4   就叫二级空调</br>如果η大于3.2   就叫三级空调</br>前面的三级空调就比较省电</br></br>如果η大于3.0   就叫四级空调</br>如果η大于2.8   就叫五级空调</br>如果一台η小于2.8的空调是不允许上市的</br>五级空调是上市的下限</br></br>大家选购空调的时候尽量选择一些能效比比较高的空调</br></br>
#+END_EXPORT


*** 《复仇者联盟3》 灭霸为什么要杀掉宇宙一半的人？人类会无限增涨吗？李永乐老师带你了解马尔萨斯人口论（2018最新）

http://www.youtube.com/watch?v=NZcqNE5NgGY

#+BEGIN_EXPORT HTML
最近有一部电影叫做《复仇者联盟3》</br>里面有一个超级大反派 叫做灭霸</br>灭霸这个人 他为了维持宇宙的平衡</br>要消灭宇宙中一半的生物</br></br>地球上的人欲望太膨胀 所以资源不够</br>于是就要把地球上的人杀一半</br>大家可能觉得这只不过是天方夜谭</br>但是实际上历史上真的有人</br>把这种理论当作一种科学理论进行研究</br>还有 依据这种理论造成了跟灭霸一样的后果</br></br>马尔萨斯人口论是马尔萨斯于1798年所创立的</br>关于人口增加与食物增加速度相对比的一种人口理论</br>其主要论点和结论为</br>生活资料按算术级数增加，而人口是按几何级数增长的，因此生活资料的增加赶不上人口的增长是自然的、永恒的规律</br>只有通过饥饿、繁重的劳动、限制结婚以及战争等手段来消灭社会“下层”，才能削弱这个规律的作用——马尔萨斯陷阱</br></br>马尔萨斯这个理论到底对 还是不对</br>我们现在还处于很大的争论之中</br></br>但是我们都要明白人是区别于动物最大的特点就是人具有人性</br>我们不能因为说穷人吃的粮食 我们就把穷人赶紧杀绝 对不对 </br></br>有一个年轻人读到了马尔萨斯人口论</br>他就想说这种东西用在人身上可能不太合理</br>至少不太合道德 但是如果用在动物身上就非常的合理</br>这个年轻人就写了一本书叫做《物种起源》</br>这个年轻人就是达尔文</br></br>
#+END_EXPORT


*** 二手车市场中的交易秘密是什么？诺贝尔奖中的柠檬市场是什么原理？李永乐老师带你解决信息不对称问题（2018最新）

http://www.youtube.com/watch?v=rarFWlm76D0

#+BEGIN_EXPORT HTML
有同学私信里问我</br>说他想买一辆二手车</br>然后去二手车市场转了好几天</br>也买不到一辆适合的二手车</br>还有同学告诉我</br>说他买了一辆车不想开了 没开几天就想卖</br>但是怎么也卖不出去</br>为什么二手车 做这个买卖这么难</br>今天我们来讨论一下这个问题</br></br></br>有一个美国的经济学家名字叫阿克洛夫</br>写了一篇论文就叫《柠檬市场》</br>他所谓的柠檬市场就是次品市场</br>关注的就是二手车市场</br>在他这篇文献中 提到了一个词叫做信息不对称</br>什么叫信息不对称呢</br>就是指在一个交易中交易的双方</br>对于产品的信息有一方比较了解 而另外一方不了解</br>于是了解的一方就可以利用这个优势去获得更多的利益</br></br></br>其实这个柠檬市场中的过程</br>我们就称之为劣币驱逐良币的过程</br></br>解决办法有三个</br>第一种方法就是法律</br>比如地沟油 注水猪肉的使用要用法律制约</br></br>第二种方法就是价格引导</br>比如保险</br></br>第三种就是信息披露</br>比如股票</br></br>
#+END_EXPORT


*** 3D电影和VR眼镜都是伪3D，你被骗了多久？李永乐老师带你了解眼睛的3D成像技术（2018最新）

http://www.youtube.com/watch?v=qgkXsbkBas8

#+BEGIN_EXPORT HTML
有同学问我</br>这个立体电影到底是什么原理？</br>今天我们就来讲一下这个原理</br></br>这个立体感的产生原因主要是因为双眼效应</br></br>利用双眼效应呈现3D效果的都有如下几种方式</br>第一种叫做红绿眼镜</br>还有一种叫VR 虚拟现实 </br>最后一种叫3D偏振眼镜，就是电影院看到的那种</br></br>以上的3D效果都是伪3D</br></br>我们真正的立体感必须你脑子往侧面一歪</br>就能看到他侧面</br>这才叫真正立体感</br>但这种技术呈现必须用全息摄影</br>但是全息这个东西现在还处于实验室阶段</br>白光的全息技术在电影院里还没有实现</br></br>
#+END_EXPORT


*** “老铁稳”有科学道理吗？李永乐老师讲核反应为高考考生祝福点赞！（2018最新）

http://www.youtube.com/watch?v=dR9DD52GhPo

#+BEGIN_EXPORT HTML
高考寄语“老铁稳”有科学道理吗</br></br>在原子核反应中</br>质量亏损会放出能量</br>但在所有元素中，铁元素是平均核子质量最低的</br>所以小核聚变成铁或者大核裂变成铁</br>都可以释放能量</br>而铁能量最稳定</br>不能裂变也不能聚变</br>这就是老铁稳的来历</br></br>2018年高考将至</br>李永乐老师祝全体考生金榜题名</br></br>
#+END_EXPORT


*** 考上清华和中500万彩票哪个更难？李永乐老师讲解正态分布的应用（2018最新）

http://www.youtube.com/watch?v=QMAaxvJlSck

#+BEGIN_EXPORT HTML
2018年高考呢马上就要来了</br>今天呢 我们继续为考生加油点赞</br></br>那么有同学就问我说 我人生有两大理想</br>第一大理想就是我要买彩票中500万</br>第二大理想就是我要考上清华</br>那大家有没有想过这两个是哪个更难一些呢</br></br>如果我们玩双色球的话</br>买彩票中500万的概率有多大</br>这个概率我之前算过</br>中头奖的概率为1772万分之一</br></br>学生模拟考试从没超过清华分数线</br>是不是一定考不上清华呢</br>我们可以通过正态分布模型来计算一个人考上清华的概率</br></br>正态分布也叫高斯分布</br>是科学上应用最广泛的分布</br>例如一年龄人群的身高分布</br></br>考试也有很多因素影响成绩</br>综合的结果其实也满足正态分布</br>利用这个分布</br>我们就可以计算自己考上清华的概率了</br></br>
#+END_EXPORT


*** 决胜21点中的“三门问题”是怎么回事？应该如何提高中奖的概率？李永乐老师讲解蒙提霍尔问题（2018最新）

http://www.youtube.com/watch?v=eYmSDnVFxT4

#+BEGIN_EXPORT HTML
有同学说</br>他最近看了一部电影叫做决胜21点</br>这里面有一个问题叫做三门问题</br>问我是怎么回事</br>今天我们就来讨论一下这个三门问题</br>这个三门问题 也称之为蒙提霍尔问题</br>为什么叫蒙提霍尔问题呢 </br>是因为 他是上个世纪美国有一个电视节目</br>这个电视节目里面有这么一个问题</br>然后那主持人叫蒙提霍尔</br>所以就叫蒙提霍尔问题</br></br>关于这个问题如何决策</br>详见视频</br></br>
#+END_EXPORT


*** 两个孩子，一个是女孩，另一个也是女孩的概率是多少？“三个囚犯”问题又是怎么回事？李永乐老师讲条件概率（2018最新）

http://www.youtube.com/watch?v=gQ-CxKaqeBQ

#+BEGIN_EXPORT HTML
今天我想回答一下网上一个非常火的问题</br>就是关于一个家庭里边</br>两个孩子是男是女的问题</br>那么这个问题本质上是一个条件概率问题</br></br>问题是这样的</br>这一个家庭里边有两个孩子</br>这两个孩子里面</br>其中之一是女孩</br>其中之一是女孩 但没有说另外一个是不是</br>求 另一个也是女孩的概率</br></br>这个问题有两种不同的回答</br>有人说那概率是1/3 有人说那概率是1/2</br></br>答案其实是根据不同的理解算出来的</br>第一种理解方法是说</br>这两个人中至少有一个女孩</br></br>第二种理解是说这两个孩子</br>其中一个孩子就是女孩</br></br>这两种理解是不一样的</br>算出来的结果也不一样</br></br>另一个比较经典的一个条件概率的问题</br>就是三个囚犯的问题</br>详细内容请见视频</br></br>
#+END_EXPORT


*** 成功学有用吗？幸存者偏差，一个活着就该明白的事！李永乐老师聊聊大牌球星的身价（2018最新）

http://www.youtube.com/watch?v=AbMTG8bzVfY

#+BEGIN_EXPORT HTML
高考刚刚结束 世界杯马上就要开始了</br>有人看到的这些天价球员 梅西 C罗</br>就说呀 唉 我运气不好</br>没有当一个踢足球 否则我现在就像他们一样有钱了</br>事实上真的是这样吗</br>今天我们来讨论一下这个问题</br>我们首先从高考全国二卷一个作文题目开始讲解</br></br>二战 " 期间，为了加强对战机的防护，英美军方调查了作战后幸存飞机上弹痕的分布，决定哪里弹痕多就加强哪里。然而统计学家沃德力排众议，指出更应该注意弹痕少的部位，因为这些部位受到重创的战机，很难有机会返航，而这部分数据被忽略了。事实证明，沃德是正确的。</br></br>为充分解答这个问题</br>得先明白幸存者偏差是什么</br></br>幸存者偏差的意思就是说</br>你只考察了幸存者所满足的特征</br>这并不能得出一个有说服力的结论来</br></br>这个结论能解释很多现象</br>比如</br>淹死的拜神者</br>用了20年不钝的刀</br>验证药物疗效的双房实验</br></br>比如，我们看到世界杯上那些天价球员</br>梅西 C罗 内马尔他们，就以为踢足球都会很有钱</br>但事实上中国许多球员工资还不到10万元</br></br>还有许多人研究成功学</br>从许多成功人士身上找到共同点</br>但却忽视了那些也具有同样特征的失败者</br>等等</br></br>反正就是</br>幸存者偏差，一个活着就该明白的事！</br></br>
#+END_EXPORT


*** 手机支付中的数字签名是如何保证信息安全的？李永乐老师讲解生日碰撞和哈希函数（2018最新）

http://www.youtube.com/watch?v=uS1ZIAsvT5w

#+BEGIN_EXPORT HTML
今天 我们想给大家介绍一下</br>大家耳熟能详的一个词叫 数字签名</br>为了解这个问题我们得先讲解一下</br>生日碰撞和哈希函数</br></br>数字签名是指</br>发送方用自己的私钥对数字指纹进行加密后所得的数据</br>其中包括非对称密钥加密和数字签名两个过程</br>在可以给数据加密的同时</br>也可用于接收方验证发送方身份的合法性</br>采用数字签名时</br>接收方需要使用发送方的公钥才能解开数字签名得到数字指纹</br></br>但是生日碰撞对于这个数字签名来讲是一个威胁</br>我们应该避免这个问题</br></br>我们以前说过这样一句话</br>说这个世界上大部分的物理学家都是数学家</br>但是并不是所有都是这样</br>有一些实验物理学家他数学能力可能没有那么强</br>但是 世界上所有的计算机科学家都是数学家</br>100% 为什么</br>因为计算机科学本质上其实就是一个用电脑实现的数学问题</br></br>
#+END_EXPORT


*** 人生中最重要的概念：复利，是什么？想贷款和分期就必须要了解它；李永乐老师讲自然对数的底e （2018最新）

http://www.youtube.com/watch?v=2a6gDHfWQGA

#+BEGIN_EXPORT HTML
有同学问我</br>这个自然对数的底e到底是什么</br>这个复利和单利到底有什么样的差别</br>今天我们把这两个问题一起来讨论一下</br></br>首先我们先来讨论一下自然对数的底</br>自然对数的底</br>其实这个数还有一个名字叫欧拉数</br>它一般是用字母e来表示的</br></br>当n趋近无穷大的时候，(1+1/n)^n=e</br>有一个更好计算的方法就是泰勒展开</br>1/0! +1/1! +1/2! +1/3! +…</br></br>那么e在工程应用非常多</br>在利息计算中，连续复利就是跟e有很大关系</br></br>PV×(1+r/n)^n=FV</br></br>当n趋于无穷时，FV=PV×e^r</br></br>连续复利它跟这个利率关系很大</br>如果这个利息比较高的话</br>那么连续复利就比普通利息要高出很多了</br></br>
#+END_EXPORT


*** 科学很美——博弈论总结篇，李永乐老师海绵演讲（2018最新）

http://www.youtube.com/watch?v=BUn88WTmcOU

#+BEGIN_EXPORT HTML
三姬分金视频：https://www.youtube.com/watch?v=qXg1r_FwkvA</br>纳什均衡视频：https://www.youtube.com/watch?v=Upd1ESkn-Bo</br>股票博弈视频：https://www.youtube.com/watch?v=g-wCpEZBEdw</br></br>
#+END_EXPORT


*** 海浪为什么总是平行海岸线？光为什么会折射？李永乐老师讲惠更斯原理（2018最新）

http://www.youtube.com/watch?v=PtA_QmlG19Y

#+BEGIN_EXPORT HTML
有同学问我说</br>这个海边的这个海浪为什么总是垂直于海岸奔袭过来</br>这个问题其实和光的折射是很类似的</br>我们先了解 光为什么会发生折射</br></br>讲到光的折射就不得不说惠更斯原理</br></br>视频中还谈到了</br>惠更斯的光是机械波和牛顿的光是微粒说的争论</br></br>其内容详见视频</br></br>
#+END_EXPORT


*** 为什么植物可以从地底吸取水份？为什么毛巾可以吸水？李永乐老师讲毛细现象（2018最新）

http://www.youtube.com/watch?v=bs4j7F0Yark

#+BEGIN_EXPORT HTML
有同学问我</br>为什么毛巾能够吸水</br>为什么植物也能够从土壤中吸水</br>还有同学问我 为什么水滴在玻璃板上就会散成一片</br>但是如果在荷叶上就会聚集成一团</br>这些问题其实都涉及到水的表面张力的问题</br>今天我们就来研究一下这个现象</br></br>首先我们得理解以下的概念</br>分子之间的作用力是怎么回事</br>什么是浸润，什么是不浸润</br></br>毛细现象（又称毛细管作用）</br>是指液体在细管状物体内侧</br>由于内聚力与附着力的差异</br>克服地心引力而上升的现象</br></br>
#+END_EXPORT


*** 超球现象——足球放乒乓球下面一起下落会发生什么？李永乐老师讲弹性碰撞（2018最新）

http://www.youtube.com/watch?v=j1BEulgbVWs

#+BEGIN_EXPORT HTML
大家会发现</br>当这一个小物体和大物体</br>一起从同一个高度往下落的时候</br>反弹的时候那个小物体上升的会非常高</br>这个现象我们称之为超球实验</br></br>为了解释这个问题大家必须懂得两个概念</br>1 什么情况下是动量守恒</br>2 什么情况下是能量守恒</br>3 牛顿摆又是怎么回事</br></br>详见视频</br></br>
#+END_EXPORT


*** 2018世界杯骗局：你见过半夜两点的太阳吗？李永乐老师讲经纬度和时差（2018最新）

http://www.youtube.com/watch?v=PBI9TxeaOrM

#+BEGIN_EXPORT HTML
世界杯火爆视频  如何买足彩稳赚不赔：https://www.youtube.com/watch?v=YXW6GxYafp8</br>世界杯火爆视频  C罗电梯球踢法：https://www.youtube.com/watch?v=aT4zV96sjVE</br></br>今天我在朋友圈里看别人发了个帖子</br>说本届世界杯就是最大的骗局</br>因为很多比赛都是半夜两点钟举行</br>你见过半夜两点钟还有太阳的吗</br></br>为了从科学角度解释这个问题</br>我们今天来讲一讲经纬度和时区的概念</br></br>视频中还解释了</br>极昼和极夜现象</br>日照时间是多少</br>什么叫中时区或者中央区</br>国际日期变更线又是怎么回事</br></br>详见视频</br></br>
#+END_EXPORT


*** 为什么会有极昼和极夜现象？春夏秋冬是怎么来的？李永乐老师讲二分二至（2018最新）

http://www.youtube.com/watch?v=me6dPnLc-zs

#+BEGIN_EXPORT HTML
最近在世界杯期间有一个国家全国只有33万人口</br>但是却去了10万人到俄罗斯看足球</br>这个国家就是冰岛 我琢磨着可能是因为最近夏至</br>所以冰岛这个国家有很大的地方都是极昼</br>所以晚上天还是亮的睡不着觉</br>于是干脆到俄罗斯看球 挺好的</br>那今天我就想讲一讲</br>什么是夏至 冬至 春分 秋分</br></br>
#+END_EXPORT


*** 这个世界是由什么构成的？五行论与元素论有什么区别？李永乐老师讲原子说（2018最新）

http://www.youtube.com/watch?v=QeCZt92BZCY

#+BEGIN_EXPORT HTML
有同学问我 这个世界是由什么构成的</br>这个问题也许很庞大</br>但是科学家的回答基本都是统一的</br></br>费曼曾经说过</br>如果这个世界就要毁灭了</br>只能给后世留下一句话的话</br>那就是——世界是由原子构成的</br></br>原子论的发展经历时间很长</br>相关的科学家、思想家和学派也很多</br>比如 柏拉图 五行学说 亚里士多德 留基伯 墨子</br>大雄 波义尔 拉瓦锡 道尔顿 阿佛加德罗等</br>但是他们的思想是基本大同的</br></br>想了解更多 打开视频看看吧</br></br>
#+END_EXPORT


*** 《我不是药神》里的格列卫凭什么这么贵？仿制药到底是不是假药？李永乐老师讲白血病（2018最新）

http://www.youtube.com/watch?v=Jzror32wTos

#+BEGIN_EXPORT HTML
最近一部电影《我不是药神》大热</br>电影里的慢性粒细胞性白血病经过人类几十年的研究</br>已经了解了致病原因</br>并且人类也研发出了针对这种疾病的靶向药物格列卫</br>长期使用格列卫可以非常好的控制病情</br>但是，因为新药研发需要投入大量的资金人力和时间</br>格列卫这种药物非常昂贵</br>于是就出现了仿制药仿制</br>药与原研药的药效相差无几</br>但是价格却非常便宜，印度在这方面做得比较多</br>慢性粒细胞性白血病到底是怎么回事？</br>格列卫为什么这么神奇？</br>仿制药是怎么做出来的？</br>为什么印度可以仿制我们却不仿制？</br>点开视频，一起了解一下</br></br>
#+END_EXPORT


*** 轮船在风浪中如何保持稳定？李永乐老师解读普吉岛翻船事故（2018最新）

http://www.youtube.com/watch?v=dHcqKG6T1NA

#+BEGIN_EXPORT HTML
轮船在海上遇到风浪,就会左右摇摆</br>如果轮船设计合理</br>轮船在重力和浮力作用下,就会恢复原状</br>这就是稳定平衡</br></br>轮船稳定平衡要求轮船的重心必须低于稳心</br>而且重心和稳心距离越大,轮船稳定性就越好</br>轮船依靠舭龙骨可以减弱摇摆振幅,防止船的侧翻</br>稳心到底在哪?</br>舭龙骨是啥? </br>点开视频看看吧</br></br>
#+END_EXPORT


*** 世界上的能量都是哪来的？李永乐老师6分钟解释能量源泉

http://www.youtube.com/watch?v=dSC9-MLD_0s

#+BEGIN_EXPORT HTML
火热视频：《我不是药神》里的格列卫凭什么这么贵？https://youtu.be/Jzror32wTos</br></br>
#+END_EXPORT


*** 你真的看懂《皇帝的新装》了吗？心知肚明和说出来有啥区别？李永乐老师讲“呐喊”的力量（2018最新）

http://www.youtube.com/watch?v=b7NZfkqFc6k

#+BEGIN_EXPORT HTML
有小朋友学习了《皇帝的新装》这篇课文，他问我明明大家都知道皇帝没有穿衣服，为什么小孩喊出这句话却造成了这么大的影响呢</br>这是因为:“大家都知道”和“大家知道大家都知道”是不一样的</br>在这个视频中，我通过一个经典逻辑问题:红眼睛和蓝眼睛来带大家了解一下共有知识和公共知识的区别</br>在社会中，有许多大家彼此心知肚明的事情，就是共有知识</br>而经过讨论之后，共有知识才能变成公共知识</br>比如一只垃圾股票，大家都知道它是垃圾</br>但是大家不知道别人是不是知道它是垃圾，所以股票的价格可能还会很高</br>一旦大家都清楚大家都知道这个股票是没有价值的，那么就不会有人再买它，它的价格就会一下子跌下来</br>这个过程很可能是一个事件一篇报道等，这就是呐喊的力量</br></br>
#+END_EXPORT


*** 假疫苗事件：疫苗到底有啥用？天花是怎么被消灭的？李永乐老师讲免疫系统（2018最新）

http://www.youtube.com/watch?v=Sxl_zoy1HoQ

#+BEGIN_EXPORT HTML
最近疫苗这个词非常流行</br>很多小朋友问我说疫苗到底是干嘛用的</br>不打疫苗行不行</br>今天我们就想讨论一下这个问题</br>我们都知道疫苗是为了防止传染病的</br>我们不妨就从人类历史上一个谈虎色变的传染病天花说起</br>天花这种传染病历史非常悠久</br></br>天花这种疾病非常可怕 首先是因为它死亡率高</br>它有30%的死亡率这么高 1/3</br>同时就算你不死</br>那么你康复了之后你的身上也会留下非常难看的疤痕</br>让人感觉非常恐怖 所以这个人基本就废了</br></br>那么人们是怎么攻克天花病毒的？</br>人们又是如何防御外界病毒或者细菌的呢？</br>疫苗对人到底有多重要呢？</br>今天这个视频给大家讲讲覆盖全身的防卫网络——免疫系统</br>人的免疫系统有基本可分有三道防线</br>具体情况，打开视频看看吧</br></br>
#+END_EXPORT


*** 学数学能解决脱发秃头问题吗？李永乐老师讲数学归纳法和模糊数学（2018最新）

http://www.youtube.com/watch?v=NCP8AWINxAo

#+BEGIN_EXPORT HTML
热门视频推荐：</br>疫苗到底有啥用？https://youtu.be/Sxl_zoy1HoQ</br>你真的看懂《皇帝的新装》了吗？https://youtu.be/b7NZfkqFc6k</br></br>数学归纳法是一种重要的数学方法，它是指证明一个与自然数有关的命题</br>可以按照如下步骤: 证明n=1时命题是成立的</br>假设n=k时结论成立，证明n=k+1时候结论也成立</br>这样从n=1成立推导出n=2成立，再从n=2成立推导出n=3成立。。。</br>这就像一个多米诺骨牌，一个倒下后面就都会倒下</br>用数学归纳法去解释生活中的现象时，有时候会得到一些有趣的结论</br>比如著名的秃子悖论: 一个人满头秀发，如果拔下一根，不会变成秃子</br>如果拔了k根都不是秃子， 再拔一根也不会变成秃子</br>如此这般，这个人无论如何拔头发都不会变成秃子</br>为了解释这个悖论，数学家扎德提出了模糊数学的概念</br>模糊数学在控制论 图像识别 人工智能等领域都有广泛的应用</br>数学归纳法是什么？模糊数学又是啥？</br>点开视频看看吧!</br></br>
#+END_EXPORT


*** 天文奇观：火星大冲是怎么回事？ 李永乐老师8分钟讲太阳系的行星运动（2018最新）

http://www.youtube.com/watch?v=iHCrjke80cE

#+BEGIN_EXPORT HTML
2018年7月27日，火星大冲，是观测火星的最佳时间</br>错过了再等17年</br>太阳系有八大行星，分别是水星、金星、地球、火星、木星、土星、天王星、海王星</br>其中水星和金星轨道半径小于地球，称为内地行星</br>当内地行星运行到太阳和地球连线上时，称为凌日</br>轨道比地球轨道大的5颗行星称为地外行星</br>当地球运行到地外行星与太阳连线上时称为冲日</br>在行星冲日的时候，太阳会把行星朝向地球的一面照亮</br>并且行星距离地球最近，此时行星最亮最大</br>火星冲日的周期大约两年多</br>但是如果冲日是发生在火星轨道的近日点，那火星距离地球就更近了</br>称之为火星大冲</br></br>在这个视频中，我还给大家介绍了开普勒第三定律</br>他告诉我们距离太阳越近的行星周期越小，距离太阳越远的行星周期</br>越大</br>具体怎么回事？点开视频看看吧!</br></br>
#+END_EXPORT


*** 月亮为什么会有“血色”的？李永乐老师5分钟讲日食与月食

http://www.youtube.com/watch?v=V-th5PUesl8

#+BEGIN_EXPORT HTML
热门视频推荐：</br></br>疫苗到底有啥用？https://youtu.be/Sxl_zoy1HoQ</br>——————————————————————————————————————</br>你真的看懂《皇帝的新装》了吗？https://youtu.be/b7NZfkqFc6k</br>——————————————————————————————————————</br>帝王为啥总要杀有功之臣？https://youtu.be/qXg1r_FwkvA</br>——————————————————————————————————————</br></br>
#+END_EXPORT


*** 为啥家长“喜欢”对孩子进行超前教育？李永乐老师讲博弈论之旅行者困境（2018最新）

http://www.youtube.com/watch?v=Pqv6mcC7i5s

#+BEGIN_EXPORT HTML
你真的看懂《皇帝的新装》了吗？https://youtu.be/b7NZfkqFc6k</br>————————————————————————————</br>帝王为啥总要杀有功之臣？https://youtu.be/qXg1r_FwkvA</br>————————————————————————————</br></br>许多家长对孩子的学习非常焦虑</br>总觉得不能输在起跑线上，让孩子提前学习各种知识</br>参加各种补习班，造成孩子、家长都非常累</br>为什么会出现这种情况昵？</br>其实，许多家长并非真想让孩子承受这么大压力</br>只是看到其他孩子都学了，自己不学就落后了</br>所以硬着头皮也要上</br>其实，这并不符合教育规律</br>在经济学上有一个模型旅行者困境</br>讲的就是这样一个问题</br>点开视频看看这种心理如何从博弈论进行解释吧!</br></br>
#+END_EXPORT


*** 2月为啥只有28天？竟然与凯撒和屋大维有关！李永乐老师讲公历演化（2018最新）

http://www.youtube.com/watch?v=dbPmMDiKW-g

#+BEGIN_EXPORT HTML
经济学视频推荐：</br>——————————————————————————————————————</br>你存银行的钱都去哪了？https://youtu.be/OTe3Bbcixow</br>————————————————————————————————</br>贷款 买房，利息怎么算？https://youtu.be/T6FBfNpiBYw</br>————————————————————————————————</br></br>值得深思的视频推荐：</br>——————————————————————————————————————</br>你真的看懂《皇帝的新装》了吗？https://youtu.be/b7NZfkqFc6k</br>————————————————————————————————</br>帝王为啥总要杀有功之臣？https://youtu.be/qXg1r_FwkvA</br>————————————————————————————————</br></br>人们在很早以前就通过天文观测知道了一年的时间是365天多一点</br>由于不是整数，所以需要通过设置闰年或者闰月的方法来补足差别</br>古罗马时代， 一年有十个月，平年355天，闰年377天</br>由于闰年设置由天文官决定，通讯不发达的古代老百姓往往无法及时获知，造成整个社会对日期的混乱</br></br>古罗马共和国末代执政官凯撒决心改变这个局面， 听取天文学家的建议，创立了儒略历</br>儒略历将一年分为12个月，大月31天，小月30天，又将2月设置为29天。4年一闰，闰年2月30天，这就是现代公历的雏形</br></br>公园1582年，教皇格里高利13世颁布教令，删除了十天</br>并规定“四年一闰，百年不闰，四百年再闰”的闰年新规，称为格里历</br></br>
#+END_EXPORT


*** 电影里车轮为啥会倒转？水滴为啥会向上流？李永乐老师讲频闪效应

http://www.youtube.com/watch?v=fMxRxk-HQ4c

#+BEGIN_EXPORT HTML
大家如果有想看的内容可能在评论区留言！</br></br>引用的不同车速下车轮的转动情况链接：https://youtu.be/nR5JSk06_l0</br></br>引用的水滴逆流视频链接：https://www.masters.tw/138111/strobe-light</br></br>火热视频推荐：</br>——————————————————————————————————————</br>WIFI和微波炉加热食物会对人有害吗？致癌吗？https://youtu.be/4h-h2vYmMtg</br>————————————————————————————————</br>老哥的一句“我先走了”，成了生命中最后一句话！https://youtu.be/Yn851GQBsWw</br>————————————————————————————————</br>宇宙中最大的数是啥？https://youtu.be/eSYN2UN3SXM</br>————————————————————————————————</br>支配宇宙的法则：什么是因果？https://youtu.be/0auDcESroEA</br></br>相对论视频推荐：</br>——————————————————————————————————————</br>光速为什么不能被超越？https://youtu.be/zY11529Uia0</br>————————————————————————————————</br>支配宇宙的法则：什么是因果？https://youtu.be/0auDcESroEA</br>————————————————————————————————</br>狭义相对论：时间膨胀是怎么回事？https://youtu.be/h6tbHSyVmfo</br></br>经济学视频推荐：</br>——————————————————————————————————————</br>你存银行的钱都去哪了？https://youtu.be/OTe3Bbcixow</br>————————————————————————————————</br>贷款 买房，利息怎么算？https://youtu.be/T6FBfNpiBYw</br>————————————————————————————————</br></br>值得深思的视频推荐：</br>——————————————————————————————————————</br>你真的看懂《皇帝的新装》了吗？https://youtu.be/b7NZfkqFc6k</br>————————————————————————————————</br>帝王为啥总要杀有功之臣？https://youtu.be/qXg1r_FwkvA</br>————————————————————————————————</br></br>
#+END_EXPORT


*** 七夕节想浪漫又不花钱？李永乐老师观星指南：教你卧看牛郎织女星

http://www.youtube.com/watch?v=ZRDtZjGCkgo

#+BEGIN_EXPORT HTML
大家如果有想看的内容可能在评论区留言！</br></br>农历七月初七是传统节日七夕</br>相传是牛郎织女相会的日子，被称为中国的情人节</br> 在这一天你想到哪种又浪漫又省钱的过节方法了吗？</br>其实，坐在草地上看星星是一个不错的选择</br>夏季和初秋， 我们很容易在天顶附近找到它们</br>我们也可以使用手机辅助我们寻找星星， 就可以了解更多的天文知识了。</br>我还会给大家介绍星等，告诉大家星星的亮暗是如何描述的。快点开视频看看吧！</br></br>火热视频推荐：</br>——————————————————————————————————————</br>宇宙中最大的数是啥？https://youtu.be/eSYN2UN3SXM</br>————————————————————————————————</br>支配宇宙的法则：什么是因果？https://youtu.be/0auDcESroEA</br></br>相对论视频推荐：</br>——————————————————————————————————————</br>光速为什么不能被超越？https://youtu.be/zY11529Uia0</br>————————————————————————————————</br>支配宇宙的法则：什么是因果？https://youtu.be/0auDcESroEA</br>————————————————————————————————</br>狭义相对论：时间膨胀是怎么回事？https://youtu.be/h6tbHSyVmfo</br></br>经济学视频推荐：</br>——————————————————————————————————————</br>你存银行的钱都去哪了？https://youtu.be/OTe3Bbcixow</br>————————————————————————————————</br>贷款 买房，利息怎么算？https://youtu.be/T6FBfNpiBYw</br>————————————————————————————————</br></br>值得深思的视频推荐：</br>——————————————————————————————————————</br>你真的看懂《皇帝的新装》了吗？https://youtu.be/b7NZfkqFc6k</br>————————————————————————————————</br>帝王为啥总要杀有功之臣？https://youtu.be/qXg1r_FwkvA</br>————————————————————————————————</br></br>
#+END_EXPORT


*** 台风是如何形成的？台风”山竹“为啥是涡旋形状的？李永乐老师讲台风眼和地转偏向力

http://www.youtube.com/watch?v=rt48YkeqvM8

#+BEGIN_EXPORT HTML
每到夏季我们经常听到台风这个词</br>台风一来就会造成大范围的降雨</br>有小朋友就问我说台风是怎么形成的？</br>为什么台风会有台风眼呢？</br>台风为什么是涡旋形状的？</br>台风是如何命名的？</br>今天我们就来研究一下这个问题</br></br>相对论视频推荐：</br>——————————————————————————————————————</br>光速为什么不能被超越？https://youtu.be/zY11529Uia0</br>————————————————————————————————</br>支配宇宙的法则：什么是因果？https://youtu.be/0auDcESroEA</br>————————————————————————————————</br>狭义相对论：时间膨胀是怎么回事？https://youtu.be/h6tbHSyVmfo</br>————————————————————————————————</br>支配宇宙的法则：什么是因果？https://youtu.be/0auDcESroEA</br></br>经济学视频推荐：</br>——————————————————————————————————————</br>你存银行的钱都去哪了？https://youtu.be/OTe3Bbcixow</br>————————————————————————————————</br>贷款 买房，利息怎么算？https://youtu.be/T6FBfNpiBYw</br>————————————————————————————————</br></br>
#+END_EXPORT


*** 特斯拉线圈 | 如何制造百万伏级的闪电？无线输电技术的困难在哪？李永乐老师告诉你

http://www.youtube.com/watch?v=_d5USXhvd6U

#+BEGIN_EXPORT HTML
有小朋友在看完了我讲的</br>《特斯拉和爱迪生谁更猛》这一期节目之后</br>就对特斯拉产生了浓厚的兴趣</br>整天问我说特斯拉线圈到底是怎么回事</br>特斯拉研究了一辈子的无线输电技术到底成功了没有呢</br>今天我们就一起来说一下这个问题</br>首先我们先来说一下特斯拉线圈</br>特斯拉最出名的就是他的人造闪电</br>所以他也被称之为闪电大师</br>那么他怎么产生人造闪电 就是使用特斯拉线圈</br>详见视频</br></br>大家有什么相看的视频内容可以在评论区留言！</br></br>火热视频推荐：</br>——————————————————————————————————————</br>宇宙中最大的数是啥？https://youtu.be/eSYN2UN3SXM</br>————————————————————————————————</br>支配宇宙的法则：什么是因果？https://youtu.be/0auDcESroEA</br></br>历史上的三次数学危机推荐：</br>——————————————————————————————————————</br>第一次数学危机是什么？https://youtu.be/nAOVQEcqjSM</br>————————————————————————————————</br>第二次数学危机是什么？https://youtu.be/S5z7xYfGNXs</br>————————————————————————————————</br>第三次数学危机是什么？https://youtu.be/GWTVAYQytJ8</br></br>经济学视频推荐：</br>——————————————————————————————————————</br>你存银行的钱都去哪了？https://youtu.be/OTe3Bbcixow</br>————————————————————————————————</br>贷款 买房，利息怎么算？https://youtu.be/T6FBfNpiBYw</br></br>
#+END_EXPORT


*** 揭秘：这个学霸，他为啥不怕百万伏的高压电？李永乐老师讲《加油向未来》的精彩实验

http://www.youtube.com/watch?v=3DLg84Eku8g

#+BEGIN_EXPORT HTML
不知大家有没有看上周末晚上</br>中央一套的节目《加油! 向未来》</br>里面有一个清华大学大二物理系的学生陈鲲羽</br>他凭借自己精彩的表现震惊了全场 被授予“鲲神”的称号</br>而且在一周的时间内刷爆了朋友圈</br>他最精彩的一个实验是坐在一个装到盐水的水池里</br>然后通上了高压电 结果发现他什么事都没有</br>他甚至用手去接触这个高压电</br>结果发现他还是镇定自若</br>有同学就问我说 那这个事到底是为啥呢</br>今天呢 我们就来解释一下这个现象</br></br>大家有什么相看的视频内容可以在评论区留言！</br></br>火热视频推荐：</br>——————————————————————————————————————</br>宇宙中最大的数是啥？https://youtu.be/eSYN2UN3SXM</br>————————————————————————————————</br>支配宇宙的法则：什么是因果？https://youtu.be/0auDcESroEA</br>————————————————————————————————</br>特斯拉线圈 | 如何制造百万伏级的闪电？https://youtu.be/_d5USXhvd6U</br>————————————————————————————————</br>烧脑面试题：老鼠和毒药问题怎么解？https://youtu.be/jYQEkkwUBxQ</br></br>
#+END_EXPORT


*** 飞蛾为什么会扑火？蜜蜂为什么要跳“8字舞”？李永乐老师8分钟告诉你

http://www.youtube.com/watch?v=lcAHliAX91I

#+BEGIN_EXPORT HTML
千百年来飞蛾都一定要扑火</br>难道不知道遇到火的之后会被烧死吗</br>今天我们就来讲一下飞蛾扑火的问题</br>飞蛾扑火的问题归结于飞蛾的习性：光线导航</br>详见视频！</br></br>另外</br>什么是蜜蜂的“8字舞”？</br>笛卡尔的等角螺旋是什么？</br>也会在视频中提及</br></br>大家有什么喜欢看的内容可以在下方留言！</br></br>
#+END_EXPORT


*** 什么液体能够实现“轻功水上飘”？李永乐老师讲神奇的非牛顿流体！

http://www.youtube.com/watch?v=vLj9z_8E9Uo

#+BEGIN_EXPORT HTML
在开学第一课中，撒贝宁带着小朋友做了一个有趣的实验，在一个装满淀粉和水的池子里</br>小朋友可以跑来跑去而不陷进去，但是如果停下来，人就会慢慢陷进池子里</br> 这实际上是涨流型非牛顿流体的特点:速度慢时阻力小，速度快时阻力大</br> 另外还有伪塑性非牛顿流体，宾汉非牛顿流体等</br>比如番茄酱，油漆，牙膏，它们都有一些神奇的特点</br>在这个视频中，我会给大家介绍非牛顿流体的分类，以及它们的典型特征</br>点开视频看看，你也可以模拟这些实验的哦。</br></br>火热视频推荐：</br>——————————————————————————————————————</br>宇宙中最大的数是啥？https://youtu.be/eSYN2UN3SXM</br>————————————————————————————————</br>支配宇宙的法则：什么是因果？https://youtu.be/0auDcESroEA</br></br>
#+END_EXPORT


*** 台风山竹来袭，在玻璃上贴胶带有用吗？李永乐老师讲台风破坏力（2018最新）

http://www.youtube.com/watch?v=WIOfyTZv7Qg

#+BEGIN_EXPORT HTML
台风山竹来啦！这是今年最强台风，登陆风力14级，瞬间风力达到17级。每当台风来袭，沿海人民总喜欢在窗户上贴胶带。这样做有用吗？我们首先要了解为什么在大风天玻璃容易碎，这是因为空气流速不同造成的伯努利原理。从台湾和美国几个实验结果来看，贴胶带其实并没有什么用。美国大气与海洋局甚至给出警示：贴胶带可能会造成大块碎玻璃，更容易伤人。风到底能造成多大压力？贴胶带为什么没用？有什么办法来保护窗户吗？点开视频看看吧！</br></br>
#+END_EXPORT


*** 打火机为啥一按就打火？超声波怎么发出来？李永乐老师讲压电效应

http://www.youtube.com/watch?v=-ZjlExDxE0o

#+BEGIN_EXPORT HTML
打火机是日常生活中最常见的工具之一</br>轻轻一按，打火机就能冒出火苗</br>它的主要原理是压电效应：</br>石英或者压电陶瓷在受到压力时两面会产生电压，瞬时可以有数万伏的高压，从而产生火花</br></br>压电效应还有逆效应</br>就是在压电元件上加交变电压，这样压电元件就可以振动</br>超声波发射器就是利用这个原理制作的</br>声呐这个现在船上必备的工具也是估计这一原理</br>压电效应谁发现的？为啥一按就有电？</br>点开视频看看吧！</br></br>
#+END_EXPORT


*** 光纤：光为什么能通讯？高锟为啥能得诺贝尔奖？李永乐老师追忆光纤之父

http://www.youtube.com/watch?v=E-j-6X9yh44

#+BEGIN_EXPORT HTML
前两天著名的科学家高锟去世了</br>他被称为是“光纤之父”</br>在光纤领域做出了杰出的贡献</br>那么有小朋友跟我说</br>他们家每天都使用光纤宽带</br>但不知道光纤是什么原理</br>今天我们就一起来介绍一下光纤的原理</br></br>
#+END_EXPORT


*** 激光啥原理？居然比太阳温度还高？李永乐老师讲诺贝尔物理奖之激光（上）

http://www.youtube.com/watch?v=U-WlZxjIGUU

#+BEGIN_EXPORT HTML
2018年诺贝尔物理学奖揭晓了</br>颁发给三位科学家</br>以表彰他们在激光应用方面做出的贡献</br>有人说他们三个人只是在技术领域做了一点进展</br>但是没有在理论方面有什么突破</br>但是绝大多数物理学家都对他们获奖表示实至名归</br>因为他们发明的光电技术啁啾放大技术</br>在最近30年为许多学科的发展铺平了道路</br>尤其是在生物学领域里面取得了许多的突破性进展</br>那么有小朋友就问我说激光到底是什么呢</br>他们发明的这些技术到底是怎么回事呢</br>我们准备用两期节目给大家介绍一下</br>这一期我们首先来介绍一下激光原理</br>详见视频</br></br>
#+END_EXPORT


*** 古人如何计时？摆钟，机械手表为啥拆了就装不回去？李永乐老师讲钟表的发展

http://www.youtube.com/watch?v=dsqS9dyieOw

#+BEGIN_EXPORT HTML
在古代，人们使用天象计时，也就是利用日月星辰的位置变化感知时间和日期</br>由此发明了日晷和圭表</br>后来，为了获得更加精确的时间，人们使用流体进行计时，如沙漏和水漏</br>为了进一步提高精确度， 人们发明了钟表</br>科学家伽利略发现了单摆的等时性， 惠更斯据此发明了摆钟</br> 再后来，拿破仑为了讨好他的皇后，命人造了一个可以带在手腕上的钟，就是最初的手表</br>机械手表是相当精密的工具</br>它的工作原理是怎样的？</br></br>视频中的相关知识点：</br>1 什么是日晷和圭表？</br>2 沙漏和水漏是怎么发明出来的？</br>3 秒摆是怎么回事？</br>4 谁发明的第一个表？</br>5 游丝又是什么神奇的东西？</br></br>点开视频看看吧！</br></br>
#+END_EXPORT


*** 时间到底是什么？1秒究竟有多长？李永乐老师讲石英钟和原子钟

http://www.youtube.com/watch?v=cXX_f_pWLQI

#+BEGIN_EXPORT HTML
相关视频：</br>打火机为啥一按就打火？什么是压电效应？https://youtu.be/-ZjlExDxE0o</br>————————————————————————————————————</br>激光啥原理？能级的概念是怎么解释？https://youtu.be/U-WlZxjIGUU</br>————————————————————————————————————</br></br>时间是什么？</br>从物理学角度讲，时间其实代表了物体有规律的运动！</br>我们观察日月星辰，就有了一年 一天 一时和一秒的概念</br>最近一百年， 随着科技的进步，人们已经不满足于使用自然规律计时</br>而希望通过物理规律定义时间，就发明了石英钟和原子钟</br>石英钟利用石英晶体的振动计时，大约每270年才会差出1秒</br>原子钟利用铯原子两个精细结构之间辐射的电磁波计时</br>精确度可以达到几千万年甚至几十亿年才差1秒</br>因为它的精确度如此之高，人们就用它来作为“秒”的定义</br>高精度的原子钟在航天领域和物理学研究上都有很重要的作用</br>具体怎么回事？</br>点开视频看看吧！</br></br>火热视频推荐：</br>————————————————————————————————</br>基因编辑是啥？CRISPR/cas9技术如何修改DNA？https://youtu.be/o1MdiW5UZh0</br></br>为什么久赌必输？https://youtu.be/AadaEc6pJpw</br></br>人造太阳EAST装置啥原理？https://youtu.be/q-9wxg9tQRk</br></br>什么样的投资值得做？https://youtu.be/RwbsL0JUmbM</br>————————————————————————————————</br></br>
#+END_EXPORT


*** 1米有多长？美国人知道千米和千克吗？李永乐老师讲国际单位制

http://www.youtube.com/watch?v=ICXSQclLefw

#+BEGIN_EXPORT HTML
昨天咱们讲了一秒是如何定义的，</br>就有小朋友问我说：</br>那么一米到底是多长呢 它又是如何定义的呢？</br>咱们不妨今天就来讲一讲国际单位制。</br>国际单位制即国际通用的计量制度。</br>1960年第11届国际计量大会通过，</br>以长度的「米」、质量的「千克」、时间的「秒」、电流量的「安培」、热力学温度的「开尔文」、物质量的「摩尔」、发光强度的「坎德拉」，</br>7个单位为基本单位；</br>以平面角的「弧度」、立体角的「球面度」，</br>2个单位为辅助单位；</br>国际符号是SI。</br></br>
#+END_EXPORT


*** 帆船竟然可以逆风航行？而且还有圆筒形的风帆？李永乐老师讲帆船的原理

http://www.youtube.com/watch?v=UG-e3KUutXw

#+BEGIN_EXPORT HTML
帆船是一种古老的交通工具</br>它前进的动力来源于鼓起的帆两侧空气流速的不同</br>伯努利原理会造成气压差</br>通过之字形的路线，帆船也可以逆风航行</br>除了传统的横桅帆船和纵桅帆船之外</br></br>现代还出现了旋筒风帆</br>看起来这种帆船连帆都没有</br>但是依靠伯努利原理</br>这种船依然可以获得前进的动力</br>具体怎么回事</br>点开视频看看吧!</br></br>
#+END_EXPORT


*** 李永乐老师和西瓜妹现场解析：什么是爱情？如何寻找自己的真命天子？

http://www.youtube.com/watch?v=YLMjah4SMOA

#+BEGIN_EXPORT HTML
视频是现场版的；</br>喜欢看的老铁可以看一下！</br></br>教学版的在2018年10月20日也有发。</br></br>
#+END_EXPORT


*** 金庸武侠：左脚踩右脚能飞上天吗？轻功、内力都是啥？李永乐老师告诉你

http://www.youtube.com/watch?v=RtV2BlUsrDI

#+BEGIN_EXPORT HTML
在武侠小说里有许多神奇的武功， 这些武功有科学依据吗？</br>普通人能练成所谓的绝世神功吗？</br>在视频里我解析了金庸笔下的两个经典桥段的：</br>洪七公跌落山崖时左脚踩右脚飞回地面</br>和郭靖守襄阳时使出的“上天梯”</br>探讨了这两个桥段中涉及的内力、摩擦力问题</br>以此缅怀一代武侠宗师金庸先生。</br></br>视频还包括以下知识点：</br>物理学上，什么是内力和外力？</br>产和摩擦力的三个条件是什么？</br>自行车的车轮摩擦力是怎么样的？</br></br>
#+END_EXPORT


*** 基因编辑是啥？CRISPR/cas9技术如何修改DNA？李永乐老师讲基因工程（1）

http://www.youtube.com/watch?v=o1MdiW5UZh0

#+BEGIN_EXPORT HTML
最近，中国深圳的科学家贺建奎宣布：</br>自己通过CRISPR/cas9技术修改了人类胚胎细胞的基因</br>并且利用这个胚胎降生了一对双胞胎</br>这个消息犹如一颗炸弹迅速在全世界范围内引发了激烈了批评</br>许多科学家斥责贺建奎不负责任，打破了人类的共识</br>基因工程是最近发展起来的生物技术</br>CRISPR/cas9是人类从细菌对抗噬菌体的过程中获得启发开拓的新方法</br>让人类可以高效低价的修改DNA</br>利用基因工程，人类可以“随心所欲”的更改动植物甚至人类自身的基因</br>从而让农作物和牲畜生长的更好，或者对抗人类自身的疾病</br>但是， 如果允许修改人类的胚胎细胞</br>除了面临医学风险外，还可能不可逆的改变人类基因库</br>造成不平等或引发更深刻的伦理学问题</br>世界各国都对人体胚胎细胞修改有严格的限制</br>CRISPR/cas9技术到底是什么？ </br>为什么能够修改基因？ </br>点开视频看看吧！</br></br>火热视频推荐：</br>————————————————————————————————</br>为什么久赌必输？https://youtu.be/AadaEc6pJpw</br></br>人造太阳EAST装置啥原理？https://youtu.be/q-9wxg9tQRk</br></br>什么样的投资值得做？https://youtu.be/RwbsL0JUmbM</br></br>怎么做生意更吸引顾客？https://youtu.be/xlmep_us15I</br>————————————————————————————————</br></br>
#+END_EXPORT


*** 基因工程对人类的重大贡献：胰岛素是如何制作的？李永乐老师讲糖尿病医疗简史

http://www.youtube.com/watch?v=2UtZHz3OfJg

#+BEGIN_EXPORT HTML
上一回咱们讲了基因工程是什么</br>那么这一回</br>咱们就来聊一下 基因工程对人类最大的一个贡献</br>那就是糖尿病人使用的药物 胰岛素的生产</br>我们首先从糖尿病说起</br>... ...</br></br>详见视频！</br></br>基因编辑是啥？CRISPR/cas9技术如何修改DNA？https://youtu.be/o1MdiW5UZh0</br></br>
#+END_EXPORT


*** 霍尔效应是什么？车速表是如何测量汽车速度的？李永乐老师讲霍尔传感器

http://www.youtube.com/watch?v=rax16bKNpKE

#+BEGIN_EXPORT HTML
上一回咱们讲到了汽车ABS系统的原理</br>那么中间谈到了一个元件叫做霍尔传感器</br>有小朋友就问我说 霍尔传感器到底是什么</br>今天我们就来研究一下这个问题</br>我们首先从霍尔效应说起</br>内容详见视频~</br></br>火热视频推荐：</br>————————————————————————————————</br>基因编辑是啥？CRISPR/cas9技术如何修改DNA？https://youtu.be/o1MdiW5UZh0</br></br>为什么久赌必输？https://youtu.be/AadaEc6pJpw</br></br>人造太阳EAST装置啥原理？https://youtu.be/q-9wxg9tQRk</br></br>什么样的投资值得做？https://youtu.be/RwbsL0JUmbM</br>————————————————————————————————</br></br>
#+END_EXPORT


*** 人推墙壁没推动，不做功但为啥也会累？肌肉是咋工作的？李永乐老师告诉你

http://www.youtube.com/watch?v=XCf8kIC5vbE

#+BEGIN_EXPORT HTML
最近有一个小朋友给我发来私信说</br>他已经上了初二了 学习了做功的概念</br>说做功等于力乘以力方向上运动的距离</br>他说假如一个人去推墙用了很大的力气 但是却没有推动</br>这个时候没有运动 所以也不做功</br>但是这个时候人为什么也会费劲 也会累</br>今天我们就想研究一下这个问题</br></br>
#+END_EXPORT




** 生物
https://www.youtube.com/playlist?list=PLOrDt87s8A3pNKtB_4KzUC7eus-LK2l96



https://i.ytimg.com/vi/UUnAiuoxQc4/sddefault.jpg


*** 正常夫妻为啥也能生色盲孩子？李永乐老师带你了解色盲的遗传原理

http://www.youtube.com/watch?v=UUnAiuoxQc4

#+BEGIN_EXPORT HTML
色盲基因遗传教学；什么是显性基因？什么是隐性基因，这里都告诉你</br>这里是李永乐老师唯一Youtube频道</br></br>
#+END_EXPORT


*** 星星为什么是黑白的？牛为什么是色盲？李永乐老师解释眼睛的色觉

http://www.youtube.com/watch?v=av8I6wAXbVs

#+BEGIN_EXPORT HTML
带你了解人与动物的视锥细胞和视杆细胞！</br>李永乐老师唯一Youtube频道</br></br>
#+END_EXPORT


*** 盯着星星看它就消失了是为什么？李永乐老师带你做有趣的盲点实验

http://www.youtube.com/watch?v=cMHfAJxT7i0

#+BEGIN_EXPORT HTML
李永乐老师唯一Youtube频道</br></br>
#+END_EXPORT


*** 《我不是药神》里的格列卫凭什么这么贵？仿制药到底是不是假药？李永乐老师讲白血病（2018最新）

http://www.youtube.com/watch?v=Jzror32wTos

#+BEGIN_EXPORT HTML
最近一部电影《我不是药神》大热</br>电影里的慢性粒细胞性白血病经过人类几十年的研究</br>已经了解了致病原因</br>并且人类也研发出了针对这种疾病的靶向药物格列卫</br>长期使用格列卫可以非常好的控制病情</br>但是，因为新药研发需要投入大量的资金人力和时间</br>格列卫这种药物非常昂贵</br>于是就出现了仿制药仿制</br>药与原研药的药效相差无几</br>但是价格却非常便宜，印度在这方面做得比较多</br>慢性粒细胞性白血病到底是怎么回事？</br>格列卫为什么这么神奇？</br>仿制药是怎么做出来的？</br>为什么印度可以仿制我们却不仿制？</br>点开视频，一起了解一下</br></br>
#+END_EXPORT


*** 基因工程对人类的重大贡献：胰岛素是如何制作的？李永乐老师讲糖尿病医疗简史

http://www.youtube.com/watch?v=2UtZHz3OfJg

#+BEGIN_EXPORT HTML
上一回咱们讲了基因工程是什么</br>那么这一回</br>咱们就来聊一下 基因工程对人类最大的一个贡献</br>那就是糖尿病人使用的药物 胰岛素的生产</br>我们首先从糖尿病说起</br>... ...</br></br>详见视频！</br></br>基因编辑是啥？CRISPR/cas9技术如何修改DNA？https://youtu.be/o1MdiW5UZh0</br></br>
#+END_EXPORT


*** 车轮抱死时，汽车为啥会不受控制？ABS系统有啥用？李永乐老师告诉你

http://www.youtube.com/watch?v=ZY09nRQs6WQ

#+BEGIN_EXPORT HTML
有一位小朋友最近买了一辆新车</br>销售跟他说这辆车装有ABS防抱死系统</br>这个系统可以防止汽车在刹车的过程中打滑减短刹车距离</br>他问我ABS系统真的这么神奇吗 它是怎么工作的呢</br>今天我们就来研究一下这个问题</br></br>火热视频推荐：</br>————————————————————————————————</br>基因编辑是啥？CRISPR/cas9技术如何修改DNA？https://youtu.be/o1MdiW5UZh0</br></br>为什么久赌必输？https://youtu.be/AadaEc6pJpw</br></br>人造太阳EAST装置啥原理？https://youtu.be/q-9wxg9tQRk</br></br>什么样的投资值得做？https://youtu.be/RwbsL0JUmbM</br>————————————————————————————————</br></br>
#+END_EXPORT




** 数学
https://www.youtube.com/playlist?list=PLOrDt87s8A3p3CA1kCR0jebK9vVaVHf5o



https://i.ytimg.com/vi/AbMTG8bzVfY/sddefault.jpg


*** 宇宙中最大的数是啥？居然能让人脑变黑洞？李永乐老师讲葛立恒数（2018最新）

http://www.youtube.com/watch?v=eSYN2UN3SXM

#+BEGIN_EXPORT HTML
历史上的三次数学危机</br>——————————————————————————————————</br>第一次数学危机是什么？https://youtu.be/nAOVQEcqjSM</br>————————————————————————————————</br>第二次数学危机是什么？https://youtu.be/S5z7xYfGNXs</br>————————————————————————————————</br>第三次数学危机是什么？https://youtu.be/GWTVAYQytJ8</br></br>经济学视频推荐：</br>——————————————————————————————————————</br>你存银行的钱都去哪了？https://youtu.be/OTe3Bbcixow</br>————————————————————————————————</br>贷款 买房，利息怎么算？https://youtu.be/T6FBfNpiBYw</br>————————————————————————————————</br></br>值得深思的视频推荐：</br>——————————————————————————————————————</br>你真的看懂《皇帝的新装》了吗？https://youtu.be/b7NZfkqFc6k</br>————————————————————————————————</br>帝王为啥总要杀有功之臣？https://youtu.be/qXg1r_FwkvA</br>————————————————————————————————</br></br>有想看的内容可能在下面留言！</br></br>
#+END_EXPORT


*** 1+2+3+4+...=-1/12？李永乐老师讲黎曼猜想（1）

http://www.youtube.com/watch?v=T93SayXhw2w

#+BEGIN_EXPORT HTML
最近数学圈爆出一个大新闻</br>英国数学家阿蒂亚(Michael Atiyah)爵士</br>宣布自己证明了黎曼猜想</br>并将在9月24号的获奖者论坛上宣读自己的论文</br>因为阿蒂亚爵士是阿贝尔奖和菲尔兹奖的双料得主</br>世界顶级的数学家之一</br>而黎曼猜想又是150多年来没有人能够解决</br>但是又特别重要的数学猜想</br>所以这则新闻一出一下子就引爆了人们的神经</br>那么许多小朋友就问我说 黎曼猜想到底是什么呢</br>因为黎曼猜想的内容实在是太丰富了</br>所以我们一期内容没有办法讲完</br>我们准备用三期的时间给大家介绍一下黎曼猜想</br>那今天我们不妨先来解决一下</br>小朋友们以前一直在问我的问题</br>全体自然数的和到底是不是-1/12</br></br>——————————————————————————————————</br>最美的数学公式是哪个？自然数是如何拓展出复数的？https://youtu.be/eEiNep19W5U</br></br>
#+END_EXPORT


*** 成功学有用吗？幸存者偏差，一个活着就该明白的事！李永乐老师聊聊大牌球星的身价（2018最新）

http://www.youtube.com/watch?v=AbMTG8bzVfY

#+BEGIN_EXPORT HTML
高考刚刚结束 世界杯马上就要开始了</br>有人看到的这些天价球员 梅西 C罗</br>就说呀 唉 我运气不好</br>没有当一个踢足球 否则我现在就像他们一样有钱了</br>事实上真的是这样吗</br>今天我们来讨论一下这个问题</br>我们首先从高考全国二卷一个作文题目开始讲解</br></br>二战 " 期间，为了加强对战机的防护，英美军方调查了作战后幸存飞机上弹痕的分布，决定哪里弹痕多就加强哪里。然而统计学家沃德力排众议，指出更应该注意弹痕少的部位，因为这些部位受到重创的战机，很难有机会返航，而这部分数据被忽略了。事实证明，沃德是正确的。</br></br>为充分解答这个问题</br>得先明白幸存者偏差是什么</br></br>幸存者偏差的意思就是说</br>你只考察了幸存者所满足的特征</br>这并不能得出一个有说服力的结论来</br></br>这个结论能解释很多现象</br>比如</br>淹死的拜神者</br>用了20年不钝的刀</br>验证药物疗效的双房实验</br></br>比如，我们看到世界杯上那些天价球员</br>梅西 C罗 内马尔他们，就以为踢足球都会很有钱</br>但事实上中国许多球员工资还不到10万元</br></br>还有许多人研究成功学</br>从许多成功人士身上找到共同点</br>但却忽视了那些也具有同样特征的失败者</br>等等</br></br>反正就是</br>幸存者偏差，一个活着就该明白的事！</br></br>
#+END_EXPORT


*** 悬赏100万美元的“黎曼猜想”有多难？李永乐老师讲什么是黎曼猜想（3）

http://www.youtube.com/watch?v=NeoDdnSlRjk

#+BEGIN_EXPORT HTML
1+2+3+4+...=-1/12？黎曼猜想（1）https://youtu.be/T93SayXhw2w</br>质数有多重要？黎曼猜想（2）https://youtu.be/4vbcC4TcMGc</br></br>经过前两期的学习 我们已经知道了黎曼函数是什么</br>我们也知道黎曼猜想与素数有很强的关系</br>那么今天我们终于要讲一讲 黎曼猜想到底是什么了</br></br>
#+END_EXPORT


*** 烧脑面试题：老鼠和毒药问题怎么解？二进制和易经八卦有啥关系？李永乐老师告诉你

http://www.youtube.com/watch?v=jYQEkkwUBxQ

#+BEGIN_EXPORT HTML
视频题目：</br>有100瓶液体 其中99瓶是水儿 有1瓶是毒药</br>如果老鼠吃了带毒药的水的话。那么这个老鼠在一周后就会死亡</br>现在问，给你一周的时间至少需要多少只小白鼠</br>才能知道哪一瓶是毒药</br></br>类似题目：</br>有 1000 个一模一样的瓶子，其中有 999 瓶是普通的水，有一瓶是毒药</br>任何喝下毒药的生物都会在一星期之后死亡</br>现在，你只有 10 只小白鼠和一星期的时间</br>如何检验出哪个瓶子里有毒药？</br>答案详见视频</br></br>火热视频推荐：</br>——————————————————————————————————————</br>宇宙中最大的数是啥？https://youtu.be/eSYN2UN3SXM</br>————————————————————————————————</br>支配宇宙的法则：什么是因果？https://youtu.be/0auDcESroEA</br></br>相对论视频推荐：</br>——————————————————————————————————————</br>光速为什么不能被超越？https://youtu.be/zY11529Uia0</br>————————————————————————————————</br>支配宇宙的法则：什么是因果？https://youtu.be/0auDcESroEA</br>————————————————————————————————</br>狭义相对论：时间膨胀是怎么回事？https://youtu.be/h6tbHSyVmfo</br></br>
#+END_EXPORT


*** 无穷大和无穷大+1谁更大？直线上的点多还是平面上的点多？李永乐老师讲神奇的希尔伯特旅馆

http://www.youtube.com/watch?v=M2apWwvOqko

#+BEGIN_EXPORT HTML
数学家希尔伯特提出了一个著名的问题：</br>如果一个旅店有无穷多个房间，每个房间都住满了人，现在又来了一个人，还能把所有人安排进旅店吗？</br>这个问题还有许多变形，</br>例如来了3个人，来了无穷多个人， 来了无穷多个巴士，每个巴士上有无穷多个人，又能不能安排好呢？</br>按照数学原理，这些情况下旅客其实都可以住进去。</br>这涉及到无限集合中“势”的概念。</br>只要能够建立一一对应的关系， 两个集合就是等势的，元素个数就是一样多的。</br>所以全体正整数和全体正偶数一样多，全体正数和全体实数一样多，</br>直线上的点和平面上的点一样多。。。</br>具体怎么回事？点开视频看看吧!</br></br>大家有什么喜欢看的视频内容可以在评论区留言！</br></br>火热视频推荐：</br>——————————————————————————————————————</br>宇宙中最大的数是啥？https://youtu.be/eSYN2UN3SXM</br>————————————————————————————————</br>支配宇宙的法则：什么是因果？https://youtu.be/0auDcESroEA</br></br>
#+END_EXPORT


*** 四维空间到底是什么样子的？李永乐老师6分钟解释高维空间

http://www.youtube.com/watch?v=_8PYYnuoZP8

#+BEGIN_EXPORT HTML
频道中有字幕，看不到的请自己设置一下！</br>四维空间过一个点能做出四条相互垂直的直线，你能想象吗？</br>空间距离s=-√(x^2+y^2+z^2+m^2)</br>三体里的降维打击是什么？</br></br>这里都会告诉你！</br></br>这里是李永乐老师唯一Youtube频道</br></br>
#+END_EXPORT


*** 第三次数学危机是什么？这次数学家都弄疯了！（2018最新）

http://www.youtube.com/watch?v=GWTVAYQytJ8

#+BEGIN_EXPORT HTML
第三次数学危机是咋回事？李永乐老师带你了解刮胡子的理发师悖论。数学家罗素对康托尔的诘难！</br>集合理论永久的瑕疵，现在人们还没有完美解决</br>这里是李永乐老师唯一Youtube频道</br></br>
#+END_EXPORT


*** 第二次数学危机是什么？李永乐老师告诉你（2018最新）

http://www.youtube.com/watch?v=S5z7xYfGNXs

#+BEGIN_EXPORT HTML
神与乌龟赛跑的故事； 相关的数学谬论； 微积分的基础是什么； 这里都会告诉你</br>这里是李永乐老师唯一Youtube频道</br></br>
#+END_EXPORT


*** 圆周率是怎么计算的？祖冲之的缀术已经失传？李永乐老师5分钟带你了解割圆法（2018）

http://www.youtube.com/watch?v=lS1gnJxHPX4

#+BEGIN_EXPORT HTML
圆周率是一个数学常数，为一个圆的周长和其直径的比率，约等于3.14159265358979323846264338327。它在18世纪中期之后一般用希腊字母π指代，有时也拼写为“pi”（/paɪ/）</br></br>π常用定义为圆的周长C与直径d的比值</br></br>第一个有纪录、严谨计算π数值的演算法是透过正多边形的几何算法，是在西元前250年由希腊数学家阿基米德所发明</br></br>中国</br>在263年由刘徽使用割圆术计算出了5位准确数值π=3.14159</br>在480年由祖冲之计算出了7位准确数值π=3.1415926，领先西方1000多年</br></br>
#+END_EXPORT


*** 史上最精彩的一个数学谜题——费马大定理；李永乐老师6分钟带你了解民科费马（2018最新）

http://www.youtube.com/watch?v=SB-Ad14jvH8

#+BEGIN_EXPORT HTML
费马是17世纪的法国律师</br>这个法国律师特别喜欢数学</br>他经常会在图书馆里看书</br>当他看到有意思的地 有一些自己的想法之后</br>他就会把自己的想法写在书的空白处</br>而且写上一句话</br>这个定理我已经证明完毕了 但是书的空白太小了我就不写了</br></br>费马大定理被一批又一批的数学家前仆后继地进行研究</br>时间持续了300年</br>在300年间 世界上第一流的数学家几乎都参与了这个问题证明</br>比如说欧拉 高斯 刘维尔 柯西等等一些人</br>这个定理无数次被人们宣布已经证明完毕了</br>但是又无数次被宣布证明过程是有问题的</br></br>最后被世界上第一流的数学家英国人怀尔斯所证明</br></br>
#+END_EXPORT


*** 第一次数学危机，天才是怎么被扼杀的？

http://www.youtube.com/watch?v=nAOVQEcqjSM

#+BEGIN_EXPORT HTML
这里是李永乐老师唯一Youtube频道</br></br>
#+END_EXPORT


*** 植物中隐藏的数学—— 斐波那契数列是什么？李永乐老师讲神奇的斐波那契数列（2018最新）

http://www.youtube.com/watch?v=VCJsUYeuqaY

#+BEGIN_EXPORT HTML
在1202年的时候 有一个人名字叫斐波那契</br>这个斐波那契他是一个意大利人</br>这个人他写了一本书 名字叫算盘书</br>里面介绍了一些数学问题</br>在这本书里面它提出的一个著名的叫兔子数列的问题</br>兔子数列 那么兔子数列被称为斐波那契数列</br></br>在800年前提出的理论 上个世纪的时候突然就火了</br>因为人们发现现实生活中有很多东西跟斐波那契数列是很像的</br>人们发现生活中很多东西都具有斐波那契的性质</br>举个例子 比如说花瓣、树枝和向日葵等植物的生长特性</br></br>那么为什么自然界总是存在着斐波那契数规律来生长呢</br>开始人们并没有深刻的认识</br>后来人们才逐渐发现了</br>原来这样的一个排布可以使得种子它的堆积效率最高</br>所以自然界在进化过程中自然而然形成了这种效果</br></br>如果把斐波那契数做比</br>它总是往一个数靠近</br>其实就是0.618……</br>黄金分割</br></br>
#+END_EXPORT


*** 银行密码系统安全吗？质数（素数）到底有啥用？李永乐老师11分钟讲RSA加密算法（2018最新）

http://www.youtube.com/watch?v=D_kMadCtKp8

#+BEGIN_EXPORT HTML
人们花这么大力气去研究这些数学问题有什么意义</br>今天我就给大家来说一下数学的意义</br>比如说我们去银行存钱取钱 用到密码</br>那么密码就是基于数学的</br></br>有一种加密算法叫对称加密</br>对称加密是以前比较常见的一种加密方式</br>另一种最典型的非对称加密方式</br>叫做RSA加密算法 </br></br>RSA加密算法</br>是在1978年的时候 麻省理工MIT有三位数学教授</br>他们一起发明了这种算法</br>这种算法 三个人的名字分别叫R S和A打头</br>所以就叫RSA算法</br>RSA加密算法的原理在视频可以了解</br></br>有没有什么方式可以比较快的计算大数的质因数分解</br>有 那就是量子计算机</br>普通计算机算十年大数的质因数分解 它可能算一个星期就算出来了</br>那如果这样的话 这个我们的银行系统什么的可能都要更新</br>否则就没有办法保证安全</br>我们现在也知道每隔一段时间我们银行的系统都需要更新一次的</br>我们的数字证书都是要重新更新 否则就不能用了 这是为什么</br>因为我们要不停的更换我们算法和密钥以保证我们的安全性</br></br>
#+END_EXPORT


*** 一笔能不能写出一个“田”字？李永乐老师4分钟带你了解七桥问题

http://www.youtube.com/watch?v=WcTGWpGosgA

#+BEGIN_EXPORT HTML
李永乐老师唯一Youtube频道</br></br>
#+END_EXPORT


*** 爱因斯坦的数学很差吗？什么是罗氏几何和黎曼几何？它们曾经可是数学家的噩梦！

http://www.youtube.com/watch?v=_l7gyzguikE

#+BEGIN_EXPORT HTML
爱因斯坦的数学是不是非常差</br>其实这是一个谬误</br>爱因斯坦的数学其实很厉害</br>只是他在最开始自己解释广义相对论的时候</br>一直找不到合适的数学工具来阐述自己的思想</br>直到他发现了非欧几何这个有力的工具</br>广义相对论才得以提出</br>那么什么叫非欧几何</br>详见视频</br></br>
#+END_EXPORT


*** 黄金分割是什么？如何拍摄出美丽的照片？李永乐老师带你了解黄金比例的美（2018最新）

http://www.youtube.com/watch?v=kKP08ozDjus

#+BEGIN_EXPORT HTML
斐波那契数列两个数之比会越来越接近黄金分割</br>那么黄金分割到底是什么呢</br></br>黄金分割相传最早是由古希腊的数学家毕达哥拉斯发现的</br>说达格拉斯 有一次在街上走</br>发现有一个铁匠敲打这个铁锤的声音特别有节奏特别美</br>结果他回去一研究发现 和原来敲击的频率有一个关系</br>于是他就提出了一个比例</br>这个比例就被人称之为黄金分割</br></br>黄金比例应该等于(-1+√5)/2</br>黄金分割被人们认为是非常美的</br></br>比如说断臂的维纳斯</br>比如说舞蹈演员穿高跟鞋</br>比如说金字塔</br>比如说东方明珠</br></br>所谓黄金矩形是指有这么一个矩形</br>这个矩形它的宽大概是0.618 而这个长大概是1</br>也就是说宽和长之比是黄金比例</br>在黄金矩形里就可以作出黄金曲线或者黄金螺旋</br></br>蒙娜丽莎在她的这幅画里边也大量运用了黄金螺旋和黄金分割</br></br>同时我们在学习绘画学习摄影过程中可能也会用到黄金分割点</br>摄影有九宫格的这种说法</br>而学会运用九宫格</br>你的摄影和拍照技术将有大大提高</br></br>
#+END_EXPORT


*** 中国古代虽然有很多的数学成就，为什么都不被承认呢？ 李永乐老师带你了解《孙子算经》中的鸡兔同笼问题（2018最新）

http://www.youtube.com/watch?v=tnKaBeDVFLU

#+BEGIN_EXPORT HTML
今天呢我们想带着大家一起回忆一下</br>我们小学时候学过的一个经典问题</br>鸡兔同笼问题</br>大家小学的时候基本都学过</br>这个问题出自什么地方呢 它出自南北朝时的一本书</br>叫做《孙子算经》</br>这是一个经典的数学问题</br>这个孙子算经里面怎么描述这个问题</br></br>有一个笼子里面关了一些鸡和一些兔子</br>鸡和兔子呢 头数一共是35个</br>而它们的脚数 一共是94个</br>求鸡有几个 兔子有几个</br>这就是所谓的鸡兔同笼问题</br></br>这个孙子算经上的解法</br>它说用94/2=47</br>然后再用47-35=12</br>这个数字呢 就是兔子的个数</br>大家可以稍作思考</br>为什么这个结果就是兔子的个数？</br></br>孙子算经其实 使用的基本上也是方程法</br>但是很遗憾 那个时候呢我们没有采用阿拉伯数字的写法</br>同时我们也没有系统地提出方程的概念</br>就差那一层窗户纸捅不上去</br>因此呢 我们中国古代虽然有很多的数学成就</br>但是基本上都不被别人承认</br>所以我们现在提出一个数学定理 都叫西方人的名字</br></br>
#+END_EXPORT


*** 中国古代稀有的一个数学定理，孙子定理是什么？韩信点兵又是怎么回事？李永乐老师带你了解中国剩余定理（2018最新）

http://www.youtube.com/watch?v=Ope18waS1GU

#+BEGIN_EXPORT HTML
昨天我们讲了鸡兔同笼问题</br>今天我们再来讲一下中国历史上另外一个著名问题</br>韩信点兵问题</br>韩信点兵 现在 在各种考试中也经常会出现</br></br>说传说 韩信有一次想知道自己的兵有多少</br>他就让自己的兵</br> 每3个人排成一列 余两人</br>又让这些兵5人一列  发现还剩下3个人</br>又让这些兵7人一列  还剩两个人</br>然后问你 请问这些人一共有多少个</br></br>这个问题最早也是鉴于我们那本</br>古典的数学名著《孙子算经》</br></br>孙子算经给出的解题口诀是：</br>三人同行七十稀</br>五树梅花二十一</br>七子团圆正半月</br>减百零五便得知</br></br>这个定理被我们称为什么呢</br>被我们称为孙子定理 或者是中国剩余定理</br>所以我们的古代 其实还是有很多的数学成就的</br></br>
#+END_EXPORT


*** 椭圆，抛物线，双曲线为啥都是圆锥曲线？为什么长期能观测到的行星都是椭圆运行的？李永乐老师带你了解原因（2018最新）

http://www.youtube.com/watch?v=dmhgsLhLTM4

#+BEGIN_EXPORT HTML
有同学问 椭圆 抛物线 双曲线</br>这是几种曲线有什么联系呢</br>为什么它们一起叫做圆锥曲线呢</br>今天我们来讲一下这个问题</br></br>圆锥曲线这个词</br>其实是在古希腊的时候就已经被人提出了</br>那么 它的提出者名字叫做阿波罗尼斯</br></br>为什么名字叫圆锥曲线呢</br>因为它可以通过切割圆锥的办法得到</br></br>所以圆锥曲线可以大致分为三种</br>椭圆 抛物线和双曲线</br></br>而天体运动的轨迹也基本上是圆锥曲线</br>我们可以通过“牛顿大炮”来解决这个问题</br></br>在太阳系内部的这些行星都做椭圆运动</br>这就是因为它们速度不够</br>假如你把这个行星速度加速到一定程度</br>它就会做抛物线或双曲线运动</br>但问题是 一旦一个行星做抛物线和双曲线运动</br>它就再也不会回到太阳系了</br>我们知道抛物线和双曲线都不是闭合的</br>所以它会离我们而去</br>因此我们能长期观察到的行星都是椭圆运动的</br></br>
#+END_EXPORT


*** 芯片内部是如何实现加法运算的？模拟信号和数字信号有什么区别？李永乐老师讲解门电路（2018最新）

http://www.youtube.com/watch?v=pUwYvJtfbsY

#+BEGIN_EXPORT HTML
有同学问我 这模拟信号和数字信号有什么区别呢</br>我们又是如何对信号进行处理的呢</br>这个问题实在是太大了</br>我们不可能一次把它都讲完</br>今天我们就来简单介绍一下</br>关于信号处理的一些基本问题</br></br>1、模拟信号和数字信号的区别</br>2、如何把十进制数转换为二进制数</br>3、高电平和低电平是什么</br>4、布尔代数运算怎么计算</br>5、门电路 与门 或门 非门  异或门是什么</br>6、半加器和全加器如何实现</br></br>我们对信号的处理远远不只是加法这么简单</br>在一个CPU内部 它的逻辑关系是非常复杂的</br>芯片代表了人类智慧的最高成就</br>它的难度是远远超过原子弹 航天飞机的</br></br>
#+END_EXPORT


*** 人生中最重要的概念：复利，是什么？想贷款和分期就必须要了解它；李永乐老师讲自然对数的底e （2018最新）

http://www.youtube.com/watch?v=2a6gDHfWQGA

#+BEGIN_EXPORT HTML
有同学问我</br>这个自然对数的底e到底是什么</br>这个复利和单利到底有什么样的差别</br>今天我们把这两个问题一起来讨论一下</br></br>首先我们先来讨论一下自然对数的底</br>自然对数的底</br>其实这个数还有一个名字叫欧拉数</br>它一般是用字母e来表示的</br></br>当n趋近无穷大的时候，(1+1/n)^n=e</br>有一个更好计算的方法就是泰勒展开</br>1/0! +1/1! +1/2! +1/3! +…</br></br>那么e在工程应用非常多</br>在利息计算中，连续复利就是跟e有很大关系</br></br>PV×(1+r/n)^n=FV</br></br>当n趋于无穷时，FV=PV×e^r</br></br>连续复利它跟这个利率关系很大</br>如果这个利息比较高的话</br>那么连续复利就比普通利息要高出很多了</br></br>
#+END_EXPORT


*** 最美的数学公式是哪个？自然数是如何拓展出复数的？李永乐老师讲欧拉公式（2018最新）

http://www.youtube.com/watch?v=eEiNep19W5U

#+BEGIN_EXPORT HTML
这个世界上最美的数学公式</br>是欧拉恒等式</br>这欧拉恒等式到底是什么</br>今天就带着大家一起来研究一下</br>为了明白欧拉恒等式</br>我们要先讲一下数系</br></br>什么是自然数</br>它如何拓展成整数的</br>什么是有理数</br>它如何拓展成无理数的</br>什么是实数</br>它如何拓展成复数的</br></br>e^iπ+1=0 欧拉方程如何证明?</br>详见视频</br></br>
#+END_EXPORT


*** 52岁数学家笛卡尔是如何表达爱意的?李永乐老师讲心形曲线（2018最新）

http://www.youtube.com/watch?v=G13Odth_nyY

#+BEGIN_EXPORT HTML
有一个流传很广的故事,讲的是52岁的笛卡尔流浪到瑞典街头</br>邂逅了18岁的瑞典公主克里斯蒂娜</br>瑞典公主把笛卡尔接回王宫教自己数学</br>两人日久生情</br>但是此事被国王发现了,国王就下令驱逐了笛卡尔</br>笛卡尔回到法国之后,一直给公主写信</br>但是公主从来没有接到过,因为都被国王拦截了</br>笛卡尔失望之余,给公主写了最后一封信</br>上面只有一行字：r=a(1-sinx) 这就是著名的心形曲线</br>这封信国王看不懂,就转交给公主</br>公主拿到之后非常开心,知道笛卡尔还想着自己</br>公主即位之后,就去找笛卡尔 可是笛卡尔已经死了</br>这个故事是假的</br>但是还被拍成了广告</br>实际上笛卡尔就是因为给公主当私人教师 所以感染了肺炎,死在了瑞典</br>而且两个人主要讨论的是哲学问题</br></br>顺便一说</br>笛卡儿也是伟大的哲学家</br>记住他的名言：我思故我在</br></br>
#+END_EXPORT


*** 圆的面积公式怎么来的？李永乐老师4分钟带你了解微积分基本原理！

http://www.youtube.com/watch?v=Br_OQ0Zznz4

#+BEGIN_EXPORT HTML
火热视频推荐：《我不是药神》里的格列卫凭什么这么贵？仿制药到底是不是假药？</br>视频链接：https://youtu.be/Jzror32wTos</br></br>老视频，新剪切</br></br>
#+END_EXPORT


*** 学数学能解决脱发秃头问题吗？李永乐老师讲数学归纳法和模糊数学（2018最新）

http://www.youtube.com/watch?v=NCP8AWINxAo

#+BEGIN_EXPORT HTML
热门视频推荐：</br>疫苗到底有啥用？https://youtu.be/Sxl_zoy1HoQ</br>你真的看懂《皇帝的新装》了吗？https://youtu.be/b7NZfkqFc6k</br></br>数学归纳法是一种重要的数学方法，它是指证明一个与自然数有关的命题</br>可以按照如下步骤: 证明n=1时命题是成立的</br>假设n=k时结论成立，证明n=k+1时候结论也成立</br>这样从n=1成立推导出n=2成立，再从n=2成立推导出n=3成立。。。</br>这就像一个多米诺骨牌，一个倒下后面就都会倒下</br>用数学归纳法去解释生活中的现象时，有时候会得到一些有趣的结论</br>比如著名的秃子悖论: 一个人满头秀发，如果拔下一根，不会变成秃子</br>如果拔了k根都不是秃子， 再拔一根也不会变成秃子</br>如此这般，这个人无论如何拔头发都不会变成秃子</br>为了解释这个悖论，数学家扎德提出了模糊数学的概念</br>模糊数学在控制论 图像识别 人工智能等领域都有广泛的应用</br>数学归纳法是什么？模糊数学又是啥？</br>点开视频看看吧!</br></br>
#+END_EXPORT


*** 周长一定，为什么圆的面积最大？这个定理被证明了2000多年！李永乐老师讲等周定理

http://www.youtube.com/watch?v=aCxbeC3RTIU

#+BEGIN_EXPORT HTML
说为什么在同等周长的所有图形当中</br>圆形的面积是最大的</br>说为什么在所有等面积的立体之中</br>球体的体积是最大的</br>这个问题听起来好像是很简单，但实际上证明起来非常麻烦</br>人们证明这个定理证明了2000多年</br>那我们今天就再一起研究一下这个问题</br></br>火热视频推荐：</br>——————————————————————————————————————</br>WIFI和微波炉加热食物会对人有害吗？致癌吗？https://youtu.be/4h-h2vYmMtg</br>————————————————————————————————</br>宇宙中最大的数是啥？https://youtu.be/eSYN2UN3SXM</br>————————————————————————————————</br>支配宇宙的法则：什么是因果？https://youtu.be/0auDcESroEA</br></br>相对论视频推荐：</br>——————————————————————————————————————</br>光速为什么不能被超越？https://youtu.be/zY11529Uia0</br>————————————————————————————————</br>支配宇宙的法则：什么是因果？https://youtu.be/0auDcESroEA</br>————————————————————————————————</br>狭义相对论：时间膨胀是怎么回事？https://youtu.be/h6tbHSyVmfo</br></br>经济学视频推荐：</br>——————————————————————————————————————</br>你存银行的钱都去哪了？https://youtu.be/OTe3Bbcixow</br>————————————————————————————————</br>贷款 买房，利息怎么算？https://youtu.be/T6FBfNpiBYw</br>————————————————————————————————</br></br>值得深思的视频推荐：</br>——————————————————————————————————————</br>你真的看懂《皇帝的新装》了吗？https://youtu.be/b7NZfkqFc6k</br>————————————————————————————————</br>帝王为啥总要杀有功之臣？https://youtu.be/qXg1r_FwkvA</br>————————————————————————————————</br></br>
#+END_EXPORT


*** 如何证明：任意三角形都是等腰三角形？李永乐老师讲几何证明悖论

http://www.youtube.com/watch?v=HrYDXTOJQT0

#+BEGIN_EXPORT HTML
最近有小朋友给我发来私信</br>说他有一个同学给他出了一个神秘的几何题</br>通过这个几何问题可以证明任意三角形都是等腰三角形</br>他百思不得其解 然后就问我是怎么回事</br>今天我们就一起来研究一下这种证明方法</br></br>火热视频推荐：</br>——————————————————————————————————————</br>WIFI和微波炉加热食物会对人有害吗？致癌吗？https://youtu.be/4h-h2vYmMtg</br>————————————————————————————————</br>宇宙中最大的数是啥？https://youtu.be/eSYN2UN3SXM</br>————————————————————————————————</br>支配宇宙的法则：什么是因果？https://youtu.be/0auDcESroEA</br></br>相对论视频推荐：</br>——————————————————————————————————————</br>光速为什么不能被超越？https://youtu.be/zY11529Uia0</br>————————————————————————————————</br>支配宇宙的法则：什么是因果？https://youtu.be/0auDcESroEA</br></br>经济学视频推荐：</br>——————————————————————————————————————</br>你存银行的钱都去哪了？https://youtu.be/OTe3Bbcixow</br>————————————————————————————————</br>贷款 买房，利息怎么算？https://youtu.be/T6FBfNpiBYw</br>————————————————————————————————</br></br>值得深思的视频推荐：</br>——————————————————————————————————————</br>你真的看懂《皇帝的新装》了吗？https://youtu.be/b7NZfkqFc6k</br>————————————————————————————————</br>帝王为啥总要杀有功之臣？https://youtu.be/qXg1r_FwkvA</br>————————————————————————————————</br></br>
#+END_EXPORT


*** 三角形的五心你知道？但三角形的费马点你肯定不知道！李永乐老师讲三角形的“心”

http://www.youtube.com/watch?v=lFap2nXN0Wg

#+BEGIN_EXPORT HTML
火热视频推荐：</br>——————————————————————————————————————</br>宇宙中最大的数是啥？https://youtu.be/eSYN2UN3SXM</br>————————————————————————————————</br>支配宇宙的法则：什么是因果？https://youtu.be/0auDcESroEA</br></br>历史上的三次数学危机推荐：</br>——————————————————————————————————————</br>第一次数学危机是什么？https://youtu.be/nAOVQEcqjSM</br>————————————————————————————————</br>第二次数学危机是什么？https://youtu.be/S5z7xYfGNXs</br>————————————————————————————————</br>第三次数学危机是什么？https://youtu.be/GWTVAYQytJ8</br></br>经济学视频推荐：</br>——————————————————————————————————————</br>你存银行的钱都去哪了？https://youtu.be/OTe3Bbcixow</br>————————————————————————————————</br>贷款 买房，利息怎么算？https://youtu.be/T6FBfNpiBYw</br>————————————————————————————————</br></br>值得深思的视频推荐：</br>——————————————————————————————————————</br>你真的看懂《皇帝的新装》了吗？https://youtu.be/b7NZfkqFc6k</br>————————————————————————————————</br>帝王为啥总要杀有功之臣？https://youtu.be/qXg1r_FwkvA</br>————————————————————————————————</br></br>有想看的内容可能在下面留言！</br></br>
#+END_EXPORT


*** 一片雪花的周长竟然能超过地球的直径？1.26维的图形是啥样？李永乐老师讲分形几何（2018最新）

http://www.youtube.com/watch?v=tEqKrJUwiHQ

#+BEGIN_EXPORT HTML
有小朋友给我提出了这样一个奇怪的问题</br>他说一片雪花的周长有多大</br>一片雪花和地球的直径相比哪个更大</br>他所问的这个问题其实涉及到分形几何的问题</br>所以今天我们就来研究一下分形几何</br></br>视频中的主要知识点：</br>英国的海岸线有多长？</br>科赫雪花是什么样子的？</br>谢尔宾斯基地毯斯是怎么回事？</br>豪斯托夫维度怎么计算？</br></br>想看，就打开视频看看吧！</br></br>
#+END_EXPORT


*** 老铁粉丝必会做的题：五点共圆怎么证？李永乐老师带你证明和演示

http://www.youtube.com/watch?v=OKac_-u05XQ

#+BEGIN_EXPORT HTML
有小朋友给我发来私信向我求助一道几何题</br>称之为“五点共圆的证明”</br>这个问题十几年前报纸上就登出来过</br>有几百位朋友都得到了正确的答案</br>那今天就带着大家一步一步的来求解一下这个问题</br></br>
#+END_EXPORT


*** 质数有多重要？数学家欧拉和高斯是如何研究质数的 ？李永乐老师讲黎曼猜想（2）

http://www.youtube.com/watch?v=4vbcC4TcMGc

#+BEGIN_EXPORT HTML
推荐相关视频</br>1+2+3+4+...=-1/12？什么是黎曼猜想（1）https://youtu.be/T93SayXhw2w</br>银行密码系统安全吗？质数（素数）到底有啥用？https://youtu.be/D_kMadCtKp8</br>——————————————————————————————————</br>今天我们继续来研究黎曼猜想</br>黎曼猜想为什么这么重要呢</br>因为它与现在数学中的许多结论都紧密的联系在一起</br>尤其是与质数的分布联系在一起</br>质数是数学界几千年以来一直非常感兴趣的一个话题</br>现在的密码学也是基于质数的</br>如果质数被人们彻底破解 那么现在的密码学就要重新改写</br>所谓的比特币 数字货币这些东西都要重新设计</br>那么质数到底有什么特点呢 质数是有限个还是无限个呢</br>它与黎曼猜想有什么关系</br>今天我们来稍微说一下 我们首先来了解一下质数</br></br>
#+END_EXPORT


*** 网上热搜：警察抓酒鬼的概率如何求？体检的意义何在？李永乐老师讲贝叶斯公式！

http://www.youtube.com/watch?v=RqvIVZHVS1I

#+BEGIN_EXPORT HTML
已知某酒鬼有90%的日子都会出去喝酒</br>喝酒只去固定三家酒吧</br>今天警察找了其中两家酒吧都没有找到酒鬼</br>那么酒鬼在第三家酒吧的几率多少?</br></br>今天给大家讲解一下这个问题</br>视频中涉及的知识有：</br>什么是概率？</br>条件概率又如何计算？</br></br>详见视频</br></br>
#+END_EXPORT


*** 什么是爱情？怎么谈恋爱，才能有效的找到自己的真命天子？李永乐老师讲爱情数学

http://www.youtube.com/watch?v=pelPCK22W7k

#+BEGIN_EXPORT HTML
曾有弟子问苏格拉底，什么是爱情？</br>苏格拉底让他走过一个麦田，只能向前，只能捡一个麦穗</br>要求他捡到最大的麦穗</br>有的弟子没走几步就捡了一个</br>然后发现了更大的后悔不已</br>有的弟子总觉得后面有更大的麦穗，结果空手而归</br>苏格拉底说：这就是爱情！</br>这个问题在近代被称为秘书问题</br>所解决的是如何在类似的情况中找出最优秀的人</br>我们的策略是在全部备选中划出一部分样本</br>考察并拒绝所有的样本</br>从样本后面的第一个人开始</br>只要发现比所有样本都好的人，就接受他</br>我们选择自己伴侣的时候，也可以使用这个策略</br>样本应该占备选者的百分之多少？</br>我们有多大概率找到真命天子？</br>打开视频看看吧！</br></br>火热视频推荐：</br>——————————————————————————————————————</br>宇宙中最大的数是啥？https://youtu.be/eSYN2UN3SXM</br>————————————————————————————————</br>支配宇宙的法则：什么是因果？https://youtu.be/0auDcESroEA</br></br></br>经济学视频推荐：</br>——————————————————————————————————————</br>你存银行的钱都去哪了？https://youtu.be/OTe3Bbcixow</br>————————————————————————————————</br>贷款 买房，利息怎么算？https://youtu.be/T6FBfNpiBYw</br></br>大家有什么喜欢的视频可以评论留言！</br></br>
#+END_EXPORT


*** 数学家有嫉妒心是有多可怕？李永乐老师讲最速降线和伯努利家族“宫斗”

http://www.youtube.com/watch?v=GKetjzfQG70

#+BEGIN_EXPORT HTML
最速降线问题最早是由伽利略提出的</br>从某一个A点建立一个光滑的轨道到侧下方的一点B</br>使得小球在重力作用下从A运动到B的时间最短</br></br>伽利略认为这个轨道应该是圆，但是很快被人否定了</br>伯努利家族的约翰伯努利解出了这个问题，并且向全欧洲的数学家挑战</br>最终他收到了来自老师莱布尼兹、老师的死敌牛顿、哥哥雅各布伯努利、学生洛必达以及自己的五份答案</br>这些答案都指向了同样的结果: 摆线</br>雅各布去世后，约翰的儿子丹尼尔伯努利也成长成一名出色的数学家</br>并且写出了巨著 《流体力学》。约翰由于嫉妒儿子</br>居然抄袭自己儿子的书，并抢在儿子之前发表</br>好在丹尼尔写书的过程中与很多科学家交流过</br>人们才戳穿了约翰的伎俩，这成为了伯努利家族的笑话</br>具体怎么回事？</br>点开视频看看吧！</br></br>
#+END_EXPORT


*** “相互保”是骗局吗？保费会比普通保险贵吗？李永乐老师讲大数定律（2018最新）

http://www.youtube.com/watch?v=x3yToesPtzo

#+BEGIN_EXPORT HTML
最近支付宝上线了一种新型保险：相互保</br>相互保的特点是:</br>加入免费</br>一旦有参保人员生大病</br>则获得一定救助由其他参保人员平摊费用</br>短短几天时间，相互保吸引了近千万人加入</br></br>根据伯努利大数定律</br>在一个相当大的群体中</br>生病的人数比例几乎是固定的</br>只要参保人数足够多，相互保的保费不会大规模的波动</br>相比于传统保险，相互保保费相对较低，赔付率较高</br>而且具有去中心化的特点，更容易为大众接受</br> 相互保的具体原理是什么？</br>保费是如何计算出来的？</br>点开视频看看吧！</br></br>
#+END_EXPORT


*** 输了钱就加倍下注，能回本？股票下跌就补仓？李永乐老师讲赌徒谬误

http://www.youtube.com/watch?v=yoOocF47BRI

#+BEGIN_EXPORT HTML
上一回咱们讲了雅各布·伯努力所提出的大数定律</br>有小朋友非常高兴地跟我说</br>他终于找到了一种可以提高彩票中奖率的方法</br>彩票中每一个数字出现的概率都是相等的</br>因此根据大数定律在很长的时间开出这些数字也应该是等频率的</br>所以如果有一个数字很长时间没有开出来 我们就应该买它</br>这样中奖的概率就特别大</br>这个说法对不对 今天我们就来研究一下这个问题</br>其实这个问题很早以前人们就提出来了</br>并被称之为赌徒谬误</br></br>具体内容，打开视频看看吧！</br></br>
#+END_EXPORT


*** 为什么久赌必输？股票加杠杆，风险为啥这么大？李永乐老师讲赌徒输光原理

http://www.youtube.com/watch?v=AadaEc6pJpw

#+BEGIN_EXPORT HTML
有一个经典的问题：如果有两个赌徒</br>他们玩一个公平的游戏：每局游戏输赢1元钱</br>且每次游戏两个人获胜的概率都是50%</br>游戏重复多次，直到一方输光，另一方赢到全部的钱为止</br>那么，最终两人谁输谁赢的概率与两人最初的资金量有关</br>资金量大的一方有更大的概率赢到全部的钱</br>资金量小的一方有更大的概率输光所有的钱</br>如果有一方的资金量是无限的</br>那么另一方有100%的概率会输光</br></br>赌徒与赌场对赌</br>由于赌场的资金相比于赌徒接近于无限</br>只要赌徒一直下注，即使是公平游戏，最终也一定会输光</br>这个问题同样可以解释在股票市场上加杠杆时的风险性</br>杠杆比例越高，输光的概率就越大</br>普希金的童话《渔夫与金鱼》也说明了同样的问题：</br>贪婪的人最终将一无所有</br>数学原理是什么？</br>点开视频看看吧！</br></br>
#+END_EXPORT


*** 什么样的投资值得做？圣彼得堡悖论是怎么回事？李永乐老师讲边际效用递减

http://www.youtube.com/watch?v=RwbsL0JUmbM

#+BEGIN_EXPORT HTML
最近有小朋友问我说 他的朋友让他进行一项投资</br>他知道这个投资有一定的概率会赚到很多钱</br>但是也有亏本的可能</br>他问我如何去评估这个项目该不该投呢</br>我们今天就来研究一下这个问题</br></br>详见视频！</br>大家有喜欢的话题内容可以在评论区留言。</br></br>火热视频推荐：</br>————————————————————————————————</br>为什么久赌必输？https://youtu.be/AadaEc6pJpw</br>输了钱就加倍下注吗？https://youtu.be/yoOocF47BRI</br>1+2+3+4+...=-1/12？https://youtu.be/T93SayXhw2w</br>————————————————————————————————</br></br>
#+END_EXPORT


*** 面对风险、机遇和挑战，你为什么总是赚小亏大？李永乐老师讲阿莱悖论

http://www.youtube.com/watch?v=8Tz1WAp4vRE

#+BEGIN_EXPORT HTML
火热视频推荐：</br>————————————————————————————————</br>为什么久赌必输？https://youtu.be/AadaEc6pJpw</br>输了钱就加倍下注吗？https://youtu.be/yoOocF47BRI</br>1+2+3+4+...=-1/12？https://youtu.be/T93SayXhw2w</br>什么样的投资值得做？https://youtu.be/RwbsL0JUmbM</br>————————————————————————————————</br>上一回我们讲了期望效用理论</br>我们知道了获得两块钱的满意度提升</br>并不等于获得一块钱满意度提升的两倍</br>但是无论是期望还是效用</br>这都属于传统经济学范畴</br>传统经济学认为人是理性的</br>但是现在我们在投资股票证券的时候</br>发现了很多的非理性行为</br>这又如何解释呢</br>今天我们就来研究一下这个问题</br></br>详见视频！</br>大家有喜欢的话题内容可以在评论区留言。</br></br>
#+END_EXPORT


*** 杨辉三角有多神奇？如何计算弹珠抽奖游戏的中奖概率？李永乐老师讲手算开方

http://www.youtube.com/watch?v=w6HYlUNGq4I

#+BEGIN_EXPORT HTML
最近有个小朋友给我发来私信</br>说他在街上看到了一个抽奖的游戏</br>就是一个弹珠下面有很多的横梁 横梁下面有槽</br>球落入不同的槽里边会有对应不同的奖品</br>他想问我这个概率怎么算</br>今天就一起来研究一下这个问题</br>为了研究这个问题</br>我们首先从一个著名的杨辉三角说起</br></br>
#+END_EXPORT


*** 数学家阿基米德的羊皮书是如何重见天日的？李永乐老师讲球的体积公式如何推导

http://www.youtube.com/watch?v=xE_j6SIjmhM

#+BEGIN_EXPORT HTML
最近有小朋友问我</br>说几千年前科学家们写的著作是如何流传到今天的</br>因为古代没有印刷术也没有电脑这些东西</br>所以著作都需要靠一次又一次的手抄来流传</br>但是在手抄的过程中 可能某些重要的作品就佚失掉了</br>也有一些作品可能中间遗失了好几百年</br>但是突然在某一天又重见天日了</br>今天就想给大家讲这么一个故事</br>那也就是《阿基米德的羊皮书》</br>详见视频……</br></br>火热视频推荐：</br>————————————————————————————————</br>为什么久赌必输？https://youtu.be/AadaEc6pJpw</br></br>人造太阳EAST装置啥原理？https://youtu.be/q-9wxg9tQRk</br></br>什么样的投资值得做？https://youtu.be/RwbsL0JUmbM</br></br>怎么做生意更吸引顾客？https://youtu.be/xlmep_us15I</br>————————————————————————————————</br></br>
#+END_EXPORT


*** “牟合方盖”是什么？古代数学家如何推导出球体积公式的？李永乐老师告诉你

http://www.youtube.com/watch?v=TBL7x0mBC1Q

#+BEGIN_EXPORT HTML
上一回咱们讲了《阿基米德的羊皮书》</br>并且介绍了阿基米德是如何计算出球的体积的</br>那么有小朋友就问我说</br>中国古代的数学家有没有计算出球的体积</br>今天咱们就来介绍一下这个问题</br>内容详见视频</br></br>火热视频推荐：</br>——————————————————————————————————————</br>宇宙中最大的数是啥？https://youtu.be/eSYN2UN3SXM</br>————————————————————————————————</br>支配宇宙的法则：什么是因果？https://youtu.be/0auDcESroEA</br></br>
#+END_EXPORT




** 物理
https://www.youtube.com/playlist?list=PLOrDt87s8A3rgc-wMLze9WG_-k-bblrOe



https://i.ytimg.com/vi/6L37Nwffy74/sddefault.jpg


*** 薛定谔的猫与平行宇宙到底怎么回事？李永乐老师7分钟讲解量子力学

http://www.youtube.com/watch?v=6L37Nwffy74

#+BEGIN_EXPORT HTML
总小朋友问我薛定谔的猫是什么</br>还让我解释一下平行宇宙</br>那么今天我们就把这两个问题一起给大家介绍一下</br>为了理解这个问题</br>首先我们要先明白经典物理学或者叫经典力学</br>它与量子力学之间有什么样的差别</br></br>在经典的世界里 它最主要的一个观点叫确定性</br>而在量子力学里最重要的特点是不确定性</br>不确定的状态就称之为纠缠态</br>这个确定的状态就称之为本征态</br></br>如果对一个粒子进行测量</br>你就会把它的纠缠变成了本征态</br></br>量子力学的很多创立者本身对量子力学也有怀疑</br>比如说著名的科学家薛定谔</br>薛定锷他提出了薛定谔方程</br>但是他对量子力学也持怀疑态度</br>认为量子力学是一个不完备的理论</br></br>于是就提出来著名的试验</br>薛定谔的猫</br></br>而对于薛定谔的猫进一步的思考</br>有个人提出了一种更加奇妙的观点</br>就叫平行宇宙</br></br>具体内容详见视频</br></br>
#+END_EXPORT


*** 海市蜃楼的原理是什么？十个人有十人不懂；让李永乐老师带你了解其中的秘密

http://www.youtube.com/watch?v=4JWNdtXcT48

#+BEGIN_EXPORT HTML
光在不同介质中传播的速度不同</br>折射和全反射现象是什么</br>海市蜃楼</br>沙市蜃楼</br>它们的不同地方在哪？</br>这里都会告诉你</br></br>李永乐老师唯一Youtube频道</br></br>
#+END_EXPORT


*** 原子弹的原理是什么？清华李永乐剖析《无问西东》中“奔跑的核”

http://www.youtube.com/watch?v=QOuTayXBTTA

#+BEGIN_EXPORT HTML
不知大家最近有没有看一部电影叫作《无问西东》</br>这部电影里有一个主角叫陈鹏</br>陈鹏他拉着王敏佳在清华校园里跑了一圈</br>并且给王敏佳解释了一下原子核反应的原理</br>陈鹏所去的单位九所，现在叫北京应用物理与计算数学研究所</br>它是中国工程物理研究院的下属单位</br>那么这个研究所为我们原子弹和氢弹的制造做了很大的贡献</br>原子弹和氢弹到底是什么原理？</br>为什么它们可以释放出这么大能量？</br>今天我们就来研究一下这个问题</br></br>
#+END_EXPORT


*** 量子力学和相对论的开端是什么？李永乐老师8分钟告诉你（2018最新）

http://www.youtube.com/watch?v=deBr1ybSf_8

#+BEGIN_EXPORT HTML
19世纪物理学的天空中还有两朵乌云是什么</br>量子力学和相对论到底是啥玩意？</br>黑体具有哪些性质？</br>光是波还是粒子？</br>什么是瑞利-金斯公式？</br>爱因斯坦光电效应最后就得了诺贝尔奖；这里都会告诉你</br>这里是李永乐老师唯一Youtube频道</br></br>
#+END_EXPORT


*** 电脑显示器为啥能显示这么多种颜色？RGB颜色代码啥意思？李永乐老师5分钟讲三原色（2018最新）

http://www.youtube.com/watch?v=7JGIcnI_C5c

#+BEGIN_EXPORT HTML
红绿蓝三种颜色按照不同的比例配比可以得到许多种颜色</br>所以这种模式我们就叫它RGB模式</br>RGB其实就表示的是</br>红，RED</br>绿，GREED</br>蓝色，BLUE</br></br>这三个颜色我们称它为三元色 </br></br>电脑显示屏或者计算机显示屏或者是电视显示器</br>基本靠这种方式来产生各种颜色的</br></br>颜色代码是全都是零的意思是红绿蓝全都不给，就是黑色</br>如果全都是FFFFFF就是红绿蓝满的，就是白色</br>这个就是RGB模式的由来</br></br>
#+END_EXPORT


*** 光为啥沿直线传播？最小作用量又是什么？李永乐老师带你了解“民科王”费马的贡献（2018最新）

http://www.youtube.com/watch?v=SBqipeI1xwI

#+BEGIN_EXPORT HTML
为什么光是沿直线传播的</br>可以从历史上最伟大的民科费马的观点</br>来解释一下这个问题</br>费马他不仅仅是一个数学家</br>同时也是一个物理学家</br>他提出了费马原理</br>费马原理说 光在传播过程中</br>它的传播时间总是什么 总是最短的</br>或者说 它总是延时间最短的路径传播 </br></br>大多数情况下光传播的时间是最短的</br>也有一些时候光传播时间是最长的</br>但是光传播以最稳定的光程（optical length）传播，不一定是最小，也不一定是最大，但是最稳定</br></br>人们从一个光传播沿直线的这样一个简单问题</br>逐渐研究研究 研究到变分法 这么一个复杂的问题</br>这就是科学的发展过程</br>费马不光在数学上很厉害 物理学上也很厉害 称之为民科之王</br></br>
#+END_EXPORT


*** 手机定位和导航是啥原理？GPS和北斗有啥区别？李永乐老师讲卫星定位（2018最新）

http://www.youtube.com/watch?v=Rhq18MV6LtU

#+BEGIN_EXPORT HTML
现在世界上用得最多的是美国的卫星定位系统</br>也就是全球卫星定位系统GPS</br>这是美国在上世纪70年代开始由军队主导的一个项目</br>那么现在中国也开始研究卫星定位系统</br>我们已经逐渐的开始布置北斗卫星导航系统</br>除了中国和美国以外</br>你像欧盟还有俄罗斯，他们也有卫星定位系统</br>那么，不同国家的卫星定位系统基本原理都是一样的</br>那么它们提供的服务都是这么几个</br>一个叫授时，就告诉你的时间是什么</br>一个叫定位，告诉你你的位置是什么</br>一个是导航，告诉你前面可能会有拥堵，路怎么走这些功能，是吧！</br></br>修正误差实际上是卫星定位最大的障碍</br>比如说现在比较常见的一种方法，我们称为差分定位的方法</br>差分定位，什么叫差分定位？ </br>就是说，你想知道这个人的空间坐标和时间坐标</br>我旁边有一个非常精密的基站</br>这个基站上面有一个高精密的定位仪器</br>不光你和卫星联络，同时这个基站它也和这四颗卫星联动</br>那么因为基站的数据比较准确，所以它就可以通过跟这些卫星联络</br>知道到你这个位置的时候大概会有多少误差</br>因为你和基站离得比较近，比如说几十公里或者一百公里以内</br>这个时候它就可以把误差作用在你的手机上对你进行修正</br>这样一来你的效果就会比较好</br></br></br>比如我们现在一般的卫星定位都要求定位精度在十米范围以内的</br>我们大部分的时候是采用这种差分定位的方法进行修正</br>现在我们大部分的定位系统还是采用美国的GPS</br>比如我们的手机一般是这样的</br>但是随着我们的导航系统，北斗导航越来越先进之后</br>我们以后得很多定位设备都会采用我们国产的北斗导航系统</br></br>
#+END_EXPORT


*** 天天在家用电，可是你知道电是怎么发出来的吗？李永乐老师讲科学巨匠法拉第的事迹，学着点（2018最新）

http://www.youtube.com/watch?v=hBIJXVsuXOs

#+BEGIN_EXPORT HTML
我们都知道家用电是有发电厂发出来的</br>但是发电厂为什么就可以发电</br></br>为了解释这个问题</br>我们首先必须从一个人物 法拉第说起</br>法拉第是英国的物理学家</br>在最开始的时候 人们认为电和磁是两个完全不同的现象</br>但是丹麦物理学家奥斯特发现电流可以产生磁场</br>于是法拉第又想 那么既然电流可以产生磁场</br>磁场能不能够产生电流</br></br></br>通过四年的实验法拉第终于发明了发电机</br></br>法拉第制作了最早的发电机之后 有人就问</br>英国的一个财务大臣就问他 说你这个东西有什么用</br>法拉第当时对英国财务大臣说</br>也许你很快就可以对它进行收税了</br>果然后来人们用电用的越来越多</br>从此之后就收了很多钱用做电费</br></br></br>我们的家用交流电是220V 50Hz</br>220V 50Hz交流电是什么意思</br>就是说 这个电压随着时间是一直在变化的</br>而且是正弦形式变化的 一个周期是0.02s，</br>所以一秒内有50个周期 这就叫50Hz</br>220V叫有效值</br>而电压的峰值并不是220V 峰值是220V×√2 大约是311V</br></br>
#+END_EXPORT


*** 无线电报是什么原理？李永乐老师带你了解什么是无线电报和摩尔斯电码！（2018最新）

http://www.youtube.com/watch?v=iKvDAwj4FXg

#+BEGIN_EXPORT HTML
为了说明电报</br>首先我们还是要从麦克斯韦说起</br>法拉第发现了电磁感应现象</br>但是他难以用数学去解释自己的观点</br></br>麦克斯韦预言了电磁波的存在</br>但是他没有亲手证实这件事就去世了</br></br>而证实麦克斯韦理论的人</br>是德国科学家海因里希·鲁道夫·赫兹</br></br></br>无线电报的发明者说起来比较乱</br>至少有三个人</br>第一个人就是咱们所熟知的尼古拉特斯拉</br>另外一个人是意大利人马可尼</br>还有一个人是俄国科学家波波夫</br></br>最开始使用无线电报的时候传输能力很有限</br>所以说人们必须把信号进行编码</br>而摩尔斯电码就是把A到Z这26个字母还有0到9这十个数字等符号</br>变成短的电磁脉和长的电磁脉冲进行编码</br></br>而摩尔斯电码中SOS本身没有任何含义</br>它只是因为在摩尔斯代码中</br>它的表式方法非常简单</br></br>摩尔斯代码现在用处很少</br>很多无线电爱好者喜欢用这种代码进行沟通</br></br>
#+END_EXPORT


*** 熵到底是什么？一副牌中抽三张为同花的概率是多大？李永乐老师带你了解自然界的发展发向（2018最新）

http://www.youtube.com/watch?v=084cwqiKzx0

#+BEGIN_EXPORT HTML
熵到底是什么</br>熵其实表示的是自然界的一个发展方向</br></br>熵等于k×ln(Ω)</br>这个k叫玻尔兹曼常数</br>玻尔兹曼常数为1.38×10^-23 J/K</br></br>这个Ω会越来越大 所以熵也会越来越大</br>Ω在自然的发展方向是变大的 所以熵也是变大的</br>也就是说在一个孤立系统</br>孤立系统中 熵是不减少的</br>这个就叫熵增加理论 </br></br></br>熵增加理论有一个比较有争议的话题</br>麦克斯韦他提出了一种理论</br>他说宇宙的熵是有上限的</br>因为热力学第二定律或者说熵增加理论造成宇宙的熵越来越大</br>当宇宙的熵达到无限大了之后</br>那么这个宇宙发展就结束了</br>或者说这个宇宙就死亡了</br>所以宇宙总有一天会死亡</br>他把这个事起了一个名字叫做热寂</br>当达到热寂的时候 这个宇宙就Game Over了</br></br>但也有些科学家认为因为宇宙在膨胀</br>它的熵的上限也在不停的膨胀</br>所以宇宙的熵永远不会达到上限</br>这个宇宙可以一直持续下去</br>这样就是比较乐观的一种观点 </br>当时麦克斯韦提出这观点之后</br>科学界的争议非常大</br>谁知道呢 反正这件事更类似于一个哲学理论</br>是吧</br></br>
#+END_EXPORT


*** 科学家才能弄懂这十个公式！李永乐老师带你了解十个最美物理公式（2018最新）

http://www.youtube.com/watch?v=ngLMlJ9hbPA

#+BEGIN_EXPORT HTML
最近 中科院的科学开放日</br>科学家们在井盖上绘制发不同的科学公式和图案 非常皮</br>现在的中科院里面有很多年轻的科学家</br>我们将带大家了解一下这些公式到底是什么含义</br></br>第一个公式称之为傅里叶变换</br>第二个公式叫斯涅耳定律 </br>第三个公式麦克斯韦方程组</br>第四个公式称之为伯努利方程</br>第五个公式称之为薛定谔方程</br>第六个公式叫做海森堡不确定性原理</br>第七个公式是阿基米德浮力原理</br>第八个公式叫做质能方程</br>第九个公式叫做卡诺定理</br>第十个公式表示的叫熵</br></br>
#+END_EXPORT


*** 一滴水如何浮起万吨巨轮？如何测量人的心脏体积？李永乐老师带你学阿基米德浮力原理（2018最新）

http://www.youtube.com/watch?v=OKWRNzB5b10

#+BEGIN_EXPORT HTML
不知道大家最近有没有看一个新闻</br>说我国新建造的一艘航母</br>这艘航母和我们从国外买的那艘辽宁号</br>两艘航母在大连碰了个面，还拍了一个合影</br>有人就问我说 航母的排水量是多少多少吨</br>这是什么意思呢</br></br>我们为了想研究这个问题</br>我们首先呢 从一个故事开始</br>就是阿基米德的王冠（详见视频）</br></br>这是一个故事 是不是真实的 不一定</br>但是阿基米德的确由这个问题出发</br>思考出了阿基米德浮力定律</br>他得出物体浮力大小</br>只跟物体排开的水的重力有关</br></br>所以舰船排水量就是舰船的质量</br>当然这还要分空载和满载</br></br>视频中还讲解了一个奇葩的问题</br>就是如何测量心脏的体积</br>详见视频</br></br>
#+END_EXPORT


*** 围棋的走法和宇宙原子总量谁更多？李永乐老师讲有争议的奇葩高考题（2018最新）

http://www.youtube.com/watch?v=EidjMIlQ3x4

#+BEGIN_EXPORT HTML
柯洁为什么战胜不了AlphaGo?</br>一个乒乓球的直径与分子更接近还是与气球更接近</br>围棋实在太复杂了，没有一个人有办法算过电脑</br>那么围棋的复杂度究竟是多少</br>和宇宙中原子个数相比差了多少</br>2017年北京高考数学最后一个选择题就是这么一个题</br>李永乐老师带你了解其中的争议</br></br>
#+END_EXPORT


*** 特斯拉和爱迪生谁更猛？李永乐老师9分钟解读特斯拉的传奇一生

http://www.youtube.com/watch?v=VYZGKj3Iyx8

#+BEGIN_EXPORT HTML
今天我们想一起带大家了解一下</br>科学界的一个传奇人物尼古拉特斯拉</br>我们今天生活的方方面面都在得益于特斯拉的贡献</br>但是特斯拉却没有因此获得巨大的商业成功</br>晚年的时候穷困潦倒 究竟是怎么一回事</br>详见视频</br></br>科学界一直有公认说有两个科学家是一直被人类低估的</br>这两个科学家 一个是尼古拉·特斯达</br>还有一个就是莱奥纳多·达芬奇</br></br>
#+END_EXPORT


*** 超球现象——足球放乒乓球下面一起下落会发生什么？李永乐老师讲弹性碰撞（2018最新）

http://www.youtube.com/watch?v=j1BEulgbVWs

#+BEGIN_EXPORT HTML
大家会发现</br>当这一个小物体和大物体</br>一起从同一个高度往下落的时候</br>反弹的时候那个小物体上升的会非常高</br>这个现象我们称之为超球实验</br></br>为了解释这个问题大家必须懂得两个概念</br>1 什么情况下是动量守恒</br>2 什么情况下是能量守恒</br>3 牛顿摆又是怎么回事</br></br>详见视频</br></br>
#+END_EXPORT


*** 两小儿辩日，一个孔子都解答不了的问题！为什么穿黑丝显瘦？李永乐老师讲太阳什么时候最热？（2018最新）

http://www.youtube.com/watch?v=AE3NeCKR4tI

#+BEGIN_EXPORT HTML
很多同学小的时候都学过一篇课文</br> 叫做《孔子见两小儿辩日 》</br>这篇课文讲的是两个小孩 讨论太阳远近的问题 </br>今天我们就想讲一讲这篇课文</br>到底太阳什么时候远 什么时候近</br></br>穿那些短波长的衣服</br>比如蓝紫色或者是黑色</br>人就显瘦</br></br>你有没有这种感觉</br>很多人喜欢穿黑丝 是吧</br>因为黑丝显得腿特别长</br>这原因就是因为它这个光色光的颜色不一样</br>对人的感觉是不一样的</br>这些是可以从物理学上进行解释的</br></br>
#+END_EXPORT


*** 原子到底是不是世界上最小的微粒？原子的行星模型是什么？李永乐老师讲原子结构（2018最新）

http://www.youtube.com/watch?v=dX2iJRtI6s8

#+BEGIN_EXPORT HTML
最初人们认为原子是世界上最小的微粒</br>但是上个世纪初，人们逐渐认识到有许多比原子更小的微粒</br></br>例如：卡文迪许实验室主</br>任J.J.汤姆孙通过阴极射线实验发现了电子，并提出了原子的枣糕模型：</br>正电荷均匀分布，负电荷镶嵌其中</br></br>后来，卢瑟福通过阿尔法粒子散射实验推翻了汤姆孙的观点，提出了行星模型：</br>原子中有一个很小的原子核，集中了全部的正电荷和绝大部分的质量</br>负电荷在核外的空间中围绕原子核高速旋转。这就像行星围绕太阳运动一样</br></br>不仅如此，人们还发现原子核也有结构，是由质子和中子构成的</br>那么质子和中子有没有结构昵？人们还在一直探索之中</br>具体怎么回事，点开视频看看吧</br></br>
#+END_EXPORT


*** 轮船在风浪中如何保持稳定？李永乐老师解读普吉岛翻船事故（2018最新）

http://www.youtube.com/watch?v=dHcqKG6T1NA

#+BEGIN_EXPORT HTML
轮船在海上遇到风浪,就会左右摇摆</br>如果轮船设计合理</br>轮船在重力和浮力作用下,就会恢复原状</br>这就是稳定平衡</br></br>轮船稳定平衡要求轮船的重心必须低于稳心</br>而且重心和稳心距离越大,轮船稳定性就越好</br>轮船依靠舭龙骨可以减弱摇摆振幅,防止船的侧翻</br>稳心到底在哪?</br>舭龙骨是啥? </br>点开视频看看吧</br></br>
#+END_EXPORT


*** 天文奇观：火星大冲是怎么回事？ 李永乐老师8分钟讲太阳系的行星运动（2018最新）

http://www.youtube.com/watch?v=iHCrjke80cE

#+BEGIN_EXPORT HTML
2018年7月27日，火星大冲，是观测火星的最佳时间</br>错过了再等17年</br>太阳系有八大行星，分别是水星、金星、地球、火星、木星、土星、天王星、海王星</br>其中水星和金星轨道半径小于地球，称为内地行星</br>当内地行星运行到太阳和地球连线上时，称为凌日</br>轨道比地球轨道大的5颗行星称为地外行星</br>当地球运行到地外行星与太阳连线上时称为冲日</br>在行星冲日的时候，太阳会把行星朝向地球的一面照亮</br>并且行星距离地球最近，此时行星最亮最大</br>火星冲日的周期大约两年多</br>但是如果冲日是发生在火星轨道的近日点，那火星距离地球就更近了</br>称之为火星大冲</br></br>在这个视频中，我还给大家介绍了开普勒第三定律</br>他告诉我们距离太阳越近的行星周期越小，距离太阳越远的行星周期</br>越大</br>具体怎么回事？点开视频看看吧!</br></br>
#+END_EXPORT


*** 月亮为什么会有“血色”的？李永乐老师5分钟讲日食与月食

http://www.youtube.com/watch?v=V-th5PUesl8

#+BEGIN_EXPORT HTML
热门视频推荐：</br></br>疫苗到底有啥用？https://youtu.be/Sxl_zoy1HoQ</br>——————————————————————————————————————</br>你真的看懂《皇帝的新装》了吗？https://youtu.be/b7NZfkqFc6k</br>——————————————————————————————————————</br>帝王为啥总要杀有功之臣？https://youtu.be/qXg1r_FwkvA</br>——————————————————————————————————————</br></br>
#+END_EXPORT


*** 老哥的一句“我先走了”，成了生命中最后一句话！高空跳水有多危险？李永乐老师讲重力加速度与缓冲

http://www.youtube.com/watch?v=Yn851GQBsWw

#+BEGIN_EXPORT HTML
火热视频推荐：</br>——————————————————————————————————————</br>宇宙中最大的数是啥？https://youtu.be/eSYN2UN3SXM</br>————————————————————————————————</br>支配宇宙的法则：什么是因果？https://youtu.be/0auDcESroEA</br></br>历史上的三次数学危机推荐：</br>——————————————————————————————————————</br>第一次数学危机是什么？https://youtu.be/nAOVQEcqjSM</br>————————————————————————————————</br>第二次数学危机是什么？https://youtu.be/S5z7xYfGNXs</br>————————————————————————————————</br>第三次数学危机是什么？https://youtu.be/GWTVAYQytJ8</br></br>经济学视频推荐：</br>——————————————————————————————————————</br>你存银行的钱都去哪了？https://youtu.be/OTe3Bbcixow</br>————————————————————————————————</br>贷款 买房，利息怎么算？https://youtu.be/T6FBfNpiBYw</br>————————————————————————————————</br></br>值得深思的视频推荐：</br>——————————————————————————————————————</br>你真的看懂《皇帝的新装》了吗？https://youtu.be/b7NZfkqFc6k</br>————————————————————————————————</br>帝王为啥总要杀有功之臣？https://youtu.be/qXg1r_FwkvA</br>————————————————————————————————</br></br>有想看的内容可能在下面留言！</br></br>
#+END_EXPORT


*** 飞机被雷击会发生什么？手机防辐射贴有用吗？李永乐老师讲静电屏蔽

http://www.youtube.com/watch?v=rT4dnHyXyGE

#+BEGIN_EXPORT HTML
相关视频推荐：</br>——————————————————————————————————————</br>闪电是如何形成的？如何快速回避闪电？https://youtu.be/qyshX7qiG2I</br></br>火热视频推荐：</br>——————————————————————————————————————</br>老哥的一句“我先走了”，成了生命中最后一句话！https://youtu.be/Yn851GQBsWw</br>————————————————————————————————</br>宇宙中最大的数是啥？https://youtu.be/eSYN2UN3SXM</br>————————————————————————————————</br>支配宇宙的法则：什么是因果？https://youtu.be/0auDcESroEA</br></br>相对论视频推荐：</br>——————————————————————————————————————</br>光速为什么不能被超越？https://youtu.be/zY11529Uia0</br>————————————————————————————————</br>支配宇宙的法则：什么是因果？https://youtu.be/0auDcESroEA</br>————————————————————————————————</br>狭义相对论：时间膨胀是怎么回事？https://youtu.be/h6tbHSyVmfo</br></br>经济学视频推荐：</br>——————————————————————————————————————</br>你存银行的钱都去哪了？https://youtu.be/OTe3Bbcixow</br>————————————————————————————————</br>贷款 买房，利息怎么算？https://youtu.be/T6FBfNpiBYw</br>————————————————————————————————</br></br>值得深思的视频推荐：</br>——————————————————————————————————————</br>你真的看懂《皇帝的新装》了吗？https://youtu.be/b7NZfkqFc6k</br>————————————————————————————————</br>帝王为啥总要杀有功之臣？https://youtu.be/qXg1r_FwkvA</br>————————————————————————————————</br></br>有想看的内容可能在下面留言！</br></br>
#+END_EXPORT


*** 电影里车轮为啥会倒转？水滴为啥会向上流？李永乐老师讲频闪效应

http://www.youtube.com/watch?v=fMxRxk-HQ4c

#+BEGIN_EXPORT HTML
大家如果有想看的内容可能在评论区留言！</br></br>引用的不同车速下车轮的转动情况链接：https://youtu.be/nR5JSk06_l0</br></br>引用的水滴逆流视频链接：https://www.masters.tw/138111/strobe-light</br></br>火热视频推荐：</br>——————————————————————————————————————</br>WIFI和微波炉加热食物会对人有害吗？致癌吗？https://youtu.be/4h-h2vYmMtg</br>————————————————————————————————</br>老哥的一句“我先走了”，成了生命中最后一句话！https://youtu.be/Yn851GQBsWw</br>————————————————————————————————</br>宇宙中最大的数是啥？https://youtu.be/eSYN2UN3SXM</br>————————————————————————————————</br>支配宇宙的法则：什么是因果？https://youtu.be/0auDcESroEA</br></br>相对论视频推荐：</br>——————————————————————————————————————</br>光速为什么不能被超越？https://youtu.be/zY11529Uia0</br>————————————————————————————————</br>支配宇宙的法则：什么是因果？https://youtu.be/0auDcESroEA</br>————————————————————————————————</br>狭义相对论：时间膨胀是怎么回事？https://youtu.be/h6tbHSyVmfo</br></br>经济学视频推荐：</br>——————————————————————————————————————</br>你存银行的钱都去哪了？https://youtu.be/OTe3Bbcixow</br>————————————————————————————————</br>贷款 买房，利息怎么算？https://youtu.be/T6FBfNpiBYw</br>————————————————————————————————</br></br>值得深思的视频推荐：</br>——————————————————————————————————————</br>你真的看懂《皇帝的新装》了吗？https://youtu.be/b7NZfkqFc6k</br>————————————————————————————————</br>帝王为啥总要杀有功之臣？https://youtu.be/qXg1r_FwkvA</br>————————————————————————————————</br></br>
#+END_EXPORT


*** 七夕节想浪漫又不花钱？李永乐老师观星指南：教你卧看牛郎织女星

http://www.youtube.com/watch?v=ZRDtZjGCkgo

#+BEGIN_EXPORT HTML
大家如果有想看的内容可能在评论区留言！</br></br>农历七月初七是传统节日七夕</br>相传是牛郎织女相会的日子，被称为中国的情人节</br> 在这一天你想到哪种又浪漫又省钱的过节方法了吗？</br>其实，坐在草地上看星星是一个不错的选择</br>夏季和初秋， 我们很容易在天顶附近找到它们</br>我们也可以使用手机辅助我们寻找星星， 就可以了解更多的天文知识了。</br>我还会给大家介绍星等，告诉大家星星的亮暗是如何描述的。快点开视频看看吧！</br></br>火热视频推荐：</br>——————————————————————————————————————</br>宇宙中最大的数是啥？https://youtu.be/eSYN2UN3SXM</br>————————————————————————————————</br>支配宇宙的法则：什么是因果？https://youtu.be/0auDcESroEA</br></br>相对论视频推荐：</br>——————————————————————————————————————</br>光速为什么不能被超越？https://youtu.be/zY11529Uia0</br>————————————————————————————————</br>支配宇宙的法则：什么是因果？https://youtu.be/0auDcESroEA</br>————————————————————————————————</br>狭义相对论：时间膨胀是怎么回事？https://youtu.be/h6tbHSyVmfo</br></br>经济学视频推荐：</br>——————————————————————————————————————</br>你存银行的钱都去哪了？https://youtu.be/OTe3Bbcixow</br>————————————————————————————————</br>贷款 买房，利息怎么算？https://youtu.be/T6FBfNpiBYw</br>————————————————————————————————</br></br>值得深思的视频推荐：</br>——————————————————————————————————————</br>你真的看懂《皇帝的新装》了吗？https://youtu.be/b7NZfkqFc6k</br>————————————————————————————————</br>帝王为啥总要杀有功之臣？https://youtu.be/qXg1r_FwkvA</br>————————————————————————————————</br></br>
#+END_EXPORT


*** 台风是如何形成的？台风”山竹“为啥是涡旋形状的？李永乐老师讲台风眼和地转偏向力

http://www.youtube.com/watch?v=rt48YkeqvM8

#+BEGIN_EXPORT HTML
每到夏季我们经常听到台风这个词</br>台风一来就会造成大范围的降雨</br>有小朋友就问我说台风是怎么形成的？</br>为什么台风会有台风眼呢？</br>台风为什么是涡旋形状的？</br>台风是如何命名的？</br>今天我们就来研究一下这个问题</br></br>相对论视频推荐：</br>——————————————————————————————————————</br>光速为什么不能被超越？https://youtu.be/zY11529Uia0</br>————————————————————————————————</br>支配宇宙的法则：什么是因果？https://youtu.be/0auDcESroEA</br>————————————————————————————————</br>狭义相对论：时间膨胀是怎么回事？https://youtu.be/h6tbHSyVmfo</br>————————————————————————————————</br>支配宇宙的法则：什么是因果？https://youtu.be/0auDcESroEA</br></br>经济学视频推荐：</br>——————————————————————————————————————</br>你存银行的钱都去哪了？https://youtu.be/OTe3Bbcixow</br>————————————————————————————————</br>贷款 买房，利息怎么算？https://youtu.be/T6FBfNpiBYw</br>————————————————————————————————</br></br>
#+END_EXPORT


*** 特斯拉线圈 | 如何制造百万伏级的闪电？无线输电技术的困难在哪？李永乐老师告诉你

http://www.youtube.com/watch?v=_d5USXhvd6U

#+BEGIN_EXPORT HTML
有小朋友在看完了我讲的</br>《特斯拉和爱迪生谁更猛》这一期节目之后</br>就对特斯拉产生了浓厚的兴趣</br>整天问我说特斯拉线圈到底是怎么回事</br>特斯拉研究了一辈子的无线输电技术到底成功了没有呢</br>今天我们就一起来说一下这个问题</br>首先我们先来说一下特斯拉线圈</br>特斯拉最出名的就是他的人造闪电</br>所以他也被称之为闪电大师</br>那么他怎么产生人造闪电 就是使用特斯拉线圈</br>详见视频</br></br>大家有什么相看的视频内容可以在评论区留言！</br></br>火热视频推荐：</br>——————————————————————————————————————</br>宇宙中最大的数是啥？https://youtu.be/eSYN2UN3SXM</br>————————————————————————————————</br>支配宇宙的法则：什么是因果？https://youtu.be/0auDcESroEA</br></br>历史上的三次数学危机推荐：</br>——————————————————————————————————————</br>第一次数学危机是什么？https://youtu.be/nAOVQEcqjSM</br>————————————————————————————————</br>第二次数学危机是什么？https://youtu.be/S5z7xYfGNXs</br>————————————————————————————————</br>第三次数学危机是什么？https://youtu.be/GWTVAYQytJ8</br></br>经济学视频推荐：</br>——————————————————————————————————————</br>你存银行的钱都去哪了？https://youtu.be/OTe3Bbcixow</br>————————————————————————————————</br>贷款 买房，利息怎么算？https://youtu.be/T6FBfNpiBYw</br></br>
#+END_EXPORT


*** 揭秘：这个学霸，他为啥不怕百万伏的高压电？李永乐老师讲《加油向未来》的精彩实验

http://www.youtube.com/watch?v=3DLg84Eku8g

#+BEGIN_EXPORT HTML
不知大家有没有看上周末晚上</br>中央一套的节目《加油! 向未来》</br>里面有一个清华大学大二物理系的学生陈鲲羽</br>他凭借自己精彩的表现震惊了全场 被授予“鲲神”的称号</br>而且在一周的时间内刷爆了朋友圈</br>他最精彩的一个实验是坐在一个装到盐水的水池里</br>然后通上了高压电 结果发现他什么事都没有</br>他甚至用手去接触这个高压电</br>结果发现他还是镇定自若</br>有同学就问我说 那这个事到底是为啥呢</br>今天呢 我们就来解释一下这个现象</br></br>大家有什么相看的视频内容可以在评论区留言！</br></br>火热视频推荐：</br>——————————————————————————————————————</br>宇宙中最大的数是啥？https://youtu.be/eSYN2UN3SXM</br>————————————————————————————————</br>支配宇宙的法则：什么是因果？https://youtu.be/0auDcESroEA</br>————————————————————————————————</br>特斯拉线圈 | 如何制造百万伏级的闪电？https://youtu.be/_d5USXhvd6U</br>————————————————————————————————</br>烧脑面试题：老鼠和毒药问题怎么解？https://youtu.be/jYQEkkwUBxQ</br></br>
#+END_EXPORT


*** 什么液体能够实现“轻功水上飘”？李永乐老师讲神奇的非牛顿流体！

http://www.youtube.com/watch?v=vLj9z_8E9Uo

#+BEGIN_EXPORT HTML
在开学第一课中，撒贝宁带着小朋友做了一个有趣的实验，在一个装满淀粉和水的池子里</br>小朋友可以跑来跑去而不陷进去，但是如果停下来，人就会慢慢陷进池子里</br> 这实际上是涨流型非牛顿流体的特点:速度慢时阻力小，速度快时阻力大</br> 另外还有伪塑性非牛顿流体，宾汉非牛顿流体等</br>比如番茄酱，油漆，牙膏，它们都有一些神奇的特点</br>在这个视频中，我会给大家介绍非牛顿流体的分类，以及它们的典型特征</br>点开视频看看，你也可以模拟这些实验的哦。</br></br>火热视频推荐：</br>——————————————————————————————————————</br>宇宙中最大的数是啥？https://youtu.be/eSYN2UN3SXM</br>————————————————————————————————</br>支配宇宙的法则：什么是因果？https://youtu.be/0auDcESroEA</br></br>
#+END_EXPORT


*** 热力学第二定律是什么？“麦克斯韦妖”是什么鬼？李永乐老师告诉你

http://www.youtube.com/watch?v=4JbgLx4_Ets

#+BEGIN_EXPORT HTML
人们认识到能量守恒之后，就知道了第一类永动机是不可能成功的</br>这时有人又发明了第二类永动机： 从一个热源吸热，并把这些热量完全转化成做功</br>如果这种机器能够制造，能量也可以反复利用，造成永动</br> 历史上还真有人靠着这种设计骗了一大笔钱，甚至把美国总统都忽悠了</br>物理学家开尔文和克劳修斯从两个角度阐述了这种做法是无法实现的</br>被称为热力学第二定律</br>不过，麦克斯韦针对这条定律提出了质疑，并设计了一只奇怪的妖怪</br>这只妖怪可以区分速度快和速度慢的粒子</br>从而让本来温度相同的两部分气体变得温度不同</br>从而违背热力学第二定律</br></br>热力学第一定律视频推荐：</br>“永动机”、“水变油”为啥都是骗局？https://youtu.be/u-6gHRvFm2w</br></br>
#+END_EXPORT


*** 宇宙中的最低温度是多少？李永乐老师讲绝对零度和热力学第三定律

http://www.youtube.com/watch?v=Xx7tLZ1c9FQ

#+BEGIN_EXPORT HTML
局座张召忠在一期节目中说：</br>我们的红外探测装置可以探测到零下700度以上的物体</br>这句话一时间成为了笑谈</br>这是因为：宇宙中最低温度是零下273。15度</br>而且根据热力学第三定律，绝对零度是无法达到的</br>温度到底是什么含义？为什么绝对零度是-273。15度？</br>在物体趋近绝对零度时会发生什么？</br>点开视频看看吧！</br></br>
#+END_EXPORT


*** 光纤：光为什么能通讯？高锟为啥能得诺贝尔奖？李永乐老师追忆光纤之父

http://www.youtube.com/watch?v=E-j-6X9yh44

#+BEGIN_EXPORT HTML
前两天著名的科学家高锟去世了</br>他被称为是“光纤之父”</br>在光纤领域做出了杰出的贡献</br>那么有小朋友跟我说</br>他们家每天都使用光纤宽带</br>但不知道光纤是什么原理</br>今天我们就一起来介绍一下光纤的原理</br></br>
#+END_EXPORT


*** 激光啥原理？居然比太阳温度还高？李永乐老师讲诺贝尔物理奖之激光（上）

http://www.youtube.com/watch?v=U-WlZxjIGUU

#+BEGIN_EXPORT HTML
2018年诺贝尔物理学奖揭晓了</br>颁发给三位科学家</br>以表彰他们在激光应用方面做出的贡献</br>有人说他们三个人只是在技术领域做了一点进展</br>但是没有在理论方面有什么突破</br>但是绝大多数物理学家都对他们获奖表示实至名归</br>因为他们发明的光电技术啁啾放大技术</br>在最近30年为许多学科的发展铺平了道路</br>尤其是在生物学领域里面取得了许多的突破性进展</br>那么有小朋友就问我说激光到底是什么呢</br>他们发明的这些技术到底是怎么回事呢</br>我们准备用两期节目给大家介绍一下</br>这一期我们首先来介绍一下激光原理</br>详见视频</br></br>
#+END_EXPORT


*** 诺贝尔物理学奖深度解读：光学镊子和啁啾放大技术是什么？李永乐老师告诉你

http://www.youtube.com/watch?v=fMLYKEAfLn4

#+BEGIN_EXPORT HTML
2018年诺贝尔物理学奖颁发给美国法国和加拿大的三位科学家</br>以表彰他们在激光应用方面的贡献</br>阿什金所发明的激光镊子可以精确的操控很小的物体</br>比如束缚细胞</br>而啁啾放大技术则是在很短的时间里集中了很大的能量的脉冲激光</br>甚至可以在活的细胞上钻洞</br>激光应用方面的诺贝尔奖其实还有很多</br>例如1971年诺贝尔奖授予给全息成像技术</br>1997年诺贝尔奖授予给激光制冷技术</br>激光——为许多学科尤其是生物学的发展铺平了道路</br></br>视频涉及相关知识点</br>什么是全息成像，它是如何实现的？</br>激光冷却又是怎么回事？</br>神奇的光学镊子是如何夹起细菌等微小粒子的？</br>飞秒激光和啁啾放大技术各是什么？</br></br>具体怎么回事，点开视频看看吧</br></br>
#+END_EXPORT


*** 古人如何计时？摆钟，机械手表为啥拆了就装不回去？李永乐老师讲钟表的发展

http://www.youtube.com/watch?v=dsqS9dyieOw

#+BEGIN_EXPORT HTML
在古代，人们使用天象计时，也就是利用日月星辰的位置变化感知时间和日期</br>由此发明了日晷和圭表</br>后来，为了获得更加精确的时间，人们使用流体进行计时，如沙漏和水漏</br>为了进一步提高精确度， 人们发明了钟表</br>科学家伽利略发现了单摆的等时性， 惠更斯据此发明了摆钟</br> 再后来，拿破仑为了讨好他的皇后，命人造了一个可以带在手腕上的钟，就是最初的手表</br>机械手表是相当精密的工具</br>它的工作原理是怎样的？</br></br>视频中的相关知识点：</br>1 什么是日晷和圭表？</br>2 沙漏和水漏是怎么发明出来的？</br>3 秒摆是怎么回事？</br>4 谁发明的第一个表？</br>5 游丝又是什么神奇的东西？</br></br>点开视频看看吧！</br></br>
#+END_EXPORT


*** 时间到底是什么？1秒究竟有多长？李永乐老师讲石英钟和原子钟

http://www.youtube.com/watch?v=cXX_f_pWLQI

#+BEGIN_EXPORT HTML
相关视频：</br>打火机为啥一按就打火？什么是压电效应？https://youtu.be/-ZjlExDxE0o</br>————————————————————————————————————</br>激光啥原理？能级的概念是怎么解释？https://youtu.be/U-WlZxjIGUU</br>————————————————————————————————————</br></br>时间是什么？</br>从物理学角度讲，时间其实代表了物体有规律的运动！</br>我们观察日月星辰，就有了一年 一天 一时和一秒的概念</br>最近一百年， 随着科技的进步，人们已经不满足于使用自然规律计时</br>而希望通过物理规律定义时间，就发明了石英钟和原子钟</br>石英钟利用石英晶体的振动计时，大约每270年才会差出1秒</br>原子钟利用铯原子两个精细结构之间辐射的电磁波计时</br>精确度可以达到几千万年甚至几十亿年才差1秒</br>因为它的精确度如此之高，人们就用它来作为“秒”的定义</br>高精度的原子钟在航天领域和物理学研究上都有很重要的作用</br>具体怎么回事？</br>点开视频看看吧！</br></br>火热视频推荐：</br>————————————————————————————————</br>基因编辑是啥？CRISPR/cas9技术如何修改DNA？https://youtu.be/o1MdiW5UZh0</br></br>为什么久赌必输？https://youtu.be/AadaEc6pJpw</br></br>人造太阳EAST装置啥原理？https://youtu.be/q-9wxg9tQRk</br></br>什么样的投资值得做？https://youtu.be/RwbsL0JUmbM</br>————————————————————————————————</br></br>
#+END_EXPORT


*** 1米有多长？美国人知道千米和千克吗？李永乐老师讲国际单位制

http://www.youtube.com/watch?v=ICXSQclLefw

#+BEGIN_EXPORT HTML
昨天咱们讲了一秒是如何定义的，</br>就有小朋友问我说：</br>那么一米到底是多长呢 它又是如何定义的呢？</br>咱们不妨今天就来讲一讲国际单位制。</br>国际单位制即国际通用的计量制度。</br>1960年第11届国际计量大会通过，</br>以长度的「米」、质量的「千克」、时间的「秒」、电流量的「安培」、热力学温度的「开尔文」、物质量的「摩尔」、发光强度的「坎德拉」，</br>7个单位为基本单位；</br>以平面角的「弧度」、立体角的「球面度」，</br>2个单位为辅助单位；</br>国际符号是SI。</br></br>
#+END_EXPORT


*** 如何利用太阳光压飞出太阳系？李永乐老师10分钟讲光帆飞船！

http://www.youtube.com/watch?v=cNwAwMg_agU

#+BEGIN_EXPORT HTML
爱因斯坦告诉我们</br>光具有粒子性</br>所以光撞击到物体表面上也会产生压力</br>叫做光压</br> 光帆飞船就是利用太阳光的光压前进的飞船</br>它曾经是人们的设想</br></br>但是2010年</br>日本发射的飞船伊卡洛斯号实践了这一梦想</br>它成功的利用光帆飞行到金星附近</br></br>有朝一日</br>人们可能会乘坐光帆飞船，飞出太阳系，飞向更加遥远的宇宙</br></br>
#+END_EXPORT


*** 帆船竟然可以逆风航行？而且还有圆筒形的风帆？李永乐老师讲帆船的原理

http://www.youtube.com/watch?v=UG-e3KUutXw

#+BEGIN_EXPORT HTML
帆船是一种古老的交通工具</br>它前进的动力来源于鼓起的帆两侧空气流速的不同</br>伯努利原理会造成气压差</br>通过之字形的路线，帆船也可以逆风航行</br>除了传统的横桅帆船和纵桅帆船之外</br></br>现代还出现了旋筒风帆</br>看起来这种帆船连帆都没有</br>但是依靠伯努利原理</br>这种船依然可以获得前进的动力</br>具体怎么回事</br>点开视频看看吧!</br></br>
#+END_EXPORT


*** 太阳为啥不会瞬间就炸掉？核聚变比人体放热还缓慢吗？李永乐老师讲人造太阳（1）

http://www.youtube.com/watch?v=vqXkZOL1nQs

#+BEGIN_EXPORT HTML
不知大家最近有没有看新闻</br>我们国家在可控核聚变方面取得了突破性的进展</br>造出了所谓的人造太阳</br>有小朋友就问我说人造太阳到底是怎么回事呢</br>今天我们再来研究一下这个问题</br>我们分两期节目来说谈 首先我们来研究一下太阳</br>太阳为什么能够稳定的发光呢</br>太阳发光的原理到底是什么呢</br></br>大家有喜欢的视频可以在评论区留言！</br></br>火热视频推荐：</br>————————————————————————————————</br>为什么久赌必输？https://youtu.be/AadaEc6pJpw</br></br>输了钱就加倍下注吗？https://youtu.be/yoOocF47BRI</br></br>什么样的投资值得做？https://youtu.be/RwbsL0JUmbM</br></br>怎么做生意更吸引顾客？https://youtu.be/xlmep_us15I</br>————————————————————————————————</br></br>
#+END_EXPORT


*** 车轮抱死时，汽车为啥会不受控制？ABS系统有啥用？李永乐老师告诉你

http://www.youtube.com/watch?v=ZY09nRQs6WQ

#+BEGIN_EXPORT HTML
有一位小朋友最近买了一辆新车</br>销售跟他说这辆车装有ABS防抱死系统</br>这个系统可以防止汽车在刹车的过程中打滑减短刹车距离</br>他问我ABS系统真的这么神奇吗 它是怎么工作的呢</br>今天我们就来研究一下这个问题</br></br>火热视频推荐：</br>————————————————————————————————</br>基因编辑是啥？CRISPR/cas9技术如何修改DNA？https://youtu.be/o1MdiW5UZh0</br></br>为什么久赌必输？https://youtu.be/AadaEc6pJpw</br></br>人造太阳EAST装置啥原理？https://youtu.be/q-9wxg9tQRk</br></br>什么样的投资值得做？https://youtu.be/RwbsL0JUmbM</br>————————————————————————————————</br></br>
#+END_EXPORT


*** 霍尔效应是什么？车速表是如何测量汽车速度的？李永乐老师讲霍尔传感器

http://www.youtube.com/watch?v=rax16bKNpKE

#+BEGIN_EXPORT HTML
上一回咱们讲到了汽车ABS系统的原理</br>那么中间谈到了一个元件叫做霍尔传感器</br>有小朋友就问我说 霍尔传感器到底是什么</br>今天我们就来研究一下这个问题</br>我们首先从霍尔效应说起</br>内容详见视频~</br></br>火热视频推荐：</br>————————————————————————————————</br>基因编辑是啥？CRISPR/cas9技术如何修改DNA？https://youtu.be/o1MdiW5UZh0</br></br>为什么久赌必输？https://youtu.be/AadaEc6pJpw</br></br>人造太阳EAST装置啥原理？https://youtu.be/q-9wxg9tQRk</br></br>什么样的投资值得做？https://youtu.be/RwbsL0JUmbM</br>————————————————————————————————</br></br>
#+END_EXPORT


*** “千克”是如何被重新定义的？它和量子霍尔效应有啥关系？李永乐老师讲功率秤

http://www.youtube.com/watch?v=E-IBVXNHyKc

#+BEGIN_EXPORT HTML
在2018年11月16号的时候 国际计量局召开一个会议</br>决定自2019年5月20号重新更改千克的定义</br>有同学就问我说这个千克是为什么要重新定义呢</br>它是怎么重新定义的呢</br>今天我们就来研究一下这个问题</br>为了研究这件事 我们首先来研究一下量子霍尔效应</br>详见视频！</br></br>火热视频推荐：</br>————————————————————————————————</br>基因编辑是啥？CRISPR/cas9技术如何修改DNA？https://youtu.be/o1MdiW5UZh0</br></br>为什么久赌必输？https://youtu.be/AadaEc6pJpw</br></br>人造太阳EAST装置啥原理？https://youtu.be/q-9wxg9tQRk</br></br>什么样的投资值得做？https://youtu.be/RwbsL0JUmbM</br>————————————————————————————————</br></br>
#+END_EXPORT


*** 人推墙壁没推动，不做功但为啥也会累？肌肉是咋工作的？李永乐老师告诉你

http://www.youtube.com/watch?v=XCf8kIC5vbE

#+BEGIN_EXPORT HTML
最近有一个小朋友给我发来私信说</br>他已经上了初二了 学习了做功的概念</br>说做功等于力乘以力方向上运动的距离</br>他说假如一个人去推墙用了很大的力气 但是却没有推动</br>这个时候没有运动 所以也不做功</br>但是这个时候人为什么也会费劲 也会累</br>今天我们就想研究一下这个问题</br></br>
#+END_EXPORT



