#+title: 黑箱社会：控制金钱和信息的数据法则

在过去的10年间，通过隐藏技术获取的巨额财富让保密行为越来越具有诱惑性。在跃升为科技老大的过程中，Google公司一直在不遗余力地护卫着它的“秘密武器”——用于对网站进行排名的复杂算法。投资银行和对冲基金可以通过诱骗伎俩从卖家和买家那里获得数十亿美元的收益，因为这些卖家根本不清楚他们所持股份的价值，买家也不知道他们所购股份中存在的问题。

当我们点击一则打折广告时，很可能幕后就有一个程序正在计算如何进行额外加价，而加价的依据可能是我们所处的位置，也可能是我们正在使用的电脑（苹果电脑还是普通电脑），甚至可能是我们的法庭记录。不只是国家安全局渴望拥有一个庞大的数据库，市场营销者们也抱有同样的目标，他们希望利用无穷无尽的数据集来建立起关于我们的详细档案。

数据经纪商可以利用私密和公开信息，例如结婚、离婚、置业、投票或成千上万的其他事项来影响我们任何一个人的生活。法律禁止政府收集某些类型的信息，但数据经纪商并不受此限制。并且一旦信息被收集上来，政府便可以随意购买。于是，企业和政府在“数据监督”方面开始协同合作，并对个人生活的私密信息进行交易。

去哪儿揭秘”网站的事例就突出表现了这种不可预测性。如果这些评分规则不能公之于众，那么即使是循规蹈矩的公民也难免会陷入麻烦。当某个用户主动降低自己的信贷限额时，他可能只是想预防诈骗或者节约开支，可他也许不知道征信局会专门留意那些缩小自己信用额度的用户，于是他不但没有因为自己的谨慎而获得一个更高的信用评分，反而会惊讶地发现随之升高的“债信比”在不断地拉低他的评分。

由于1%的病人占据着5%以上的医保成本，而且5%的病人会占据将近一半以上的成本，所以保险商希望“优选出”那些健康的投保人，同时“筛选掉”患病概率大的人群。相对于为所有申请人投保的做法，“筛选”法可以大大提升保险商的利润。

相对于不良数据，不良推论可能会产生更大的问题。因为公司可以将它们以“意见”而非“事实”的形式加以呈现。我们可以对谎言提起诉讼，但对于意见却难以证其真伪，因此很难根据美国宪法第一修正案提出质询。例如

但试想，一位负责医疗案件的律师可能完全有能力处理有关区域项目整体协约（ZPIC）的事务，但由于他的简历中没有采用“区域项目整体协约”的缩写形式，而自动软件的搜索目标又恰好设置成了缩写形式，那么她就很可能连面试的机会都无法获得。她也许永远不会知道这个小小的失误就是造成她求职失利的主要或者是唯一的原因。

人们对于黑箱评分的持续焦虑表明，自然科学方法常常被错误地应用到社会领域。土木工程师们可能会使用来自1 000座桥梁的数据来评估接下来会有哪座桥倒塌；如今，数量分析专家们通过成百上千万笔交易来预测哪些用户可能违约。但不同的是，土木工程师的研究不会对桥梁构成影响，而信用评分系统一旦将某人定为高风险用户并随即提高贷款利率，那么就会增加这个客户的违约概率。另外，秘密评分的“科学”并没有采用科学的方法来提供核心保障：公开可测的公平化程序和监督。只要分析过程处于保密状态，社会歧视问题便会依然存在并且难以解决。

现在我们知道，美国政府一直都热衷于建立有关美国公民的“情报库”。美国国家安全局的过度干涉和不负责任的行为让人们感到非常愤怒。但我不想谈论这个问题，我们只看其中的一个方面：政府在勤于情报采集的过程中已经和许多利益集团建立了强大的秘密联盟，而这些利益集团关注的不是公众福祉，而是私人利益和个人成就。

军队和密探向来都隐秘行事，毕竟如俗语所言：口风不严战舰沉。然而，保密行为也会牵涉到利益问题。当Google在网络监测方面与国土安全部和美国国家安全局并肩作战时，它还用得着担心可能会违犯反垄断条款吗？就像那些“大到不可能倒闭”的银行一样，Google公司“在监测方面的地位太重要了”，以至于政府要对其维护到底。事实上，2013年的泄密文件已经揭示出，美国国家安全局（或英国的合作伙伴）曾与负责调查Google违反欧盟竞争法的官员进行过接洽。更多的资料显示，政府和企业之间不仅是交易关系，它们还在利益交换方面存在着一种隐秘的联姻关系。

人员流动的问题也很显著。有些政府官员会极力创造机会，以便将来能够在他们当前管辖的公司中谋职。很多安全局的官员在离开公共事业岗位后都会任职于收入颇丰的私营部门。“国土安全部——行业联合企业”对威胁认知进行着操纵，这不但符合公司的利益，也充盈了政府部门的钱袋。
